[package]
name = "kajit-reprs"
version = "0.1.0"
edition = "2024"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
ariadne = "0.5"
chumsky = "1.0.0-alpha.8"
kajit-ir = { path = "../kajit-ir" }
kajit-ir-text = { path = "../kajit-ir-text" }
kajit-lir = { path = "../kajit-lir" }
kajit-mir = { path = "../kajit-mir" }
kajit-mir-text = { path = "../kajit-mir-text" }
kajit-types = { path = "../kajit-types" }
