[package]
name = "kajit-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kajit"
path = "src/main.rs"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[features]
default = []

[dependencies]
chumsky = { workspace = true }
facet = { workspace = true }
figue = { workspace = true }
kajit-asm = { workspace = true }
kajit-mir = { workspace = true }
kajit-reprs = { workspace = true }
kajit-wares = { workspace = true }
tokio = { workspace = true }
tower-lsp = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
