// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#![allow(dead_code, unused_variables)]
use super::*;

#[derive(Default)]
struct ErrorSink(Vec<String>);

impl ErrorSink {
    fn push(&mut self, error: String) {
        self.0.push(error);
    }
    fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
    fn into_vec(self) -> Vec<String> {
        self.0
    }
}

#[derive(Default)]
struct ValidationContext {
    block_ids: Vec<std::collections::BTreeSet<BlockId>>,

    edge_ids: Vec<std::collections::BTreeSet<EdgeId>>,

    function_ids: Vec<std::collections::BTreeSet<FunctionId>>,

    inst_ids: Vec<std::collections::BTreeSet<InstId>>,

    terminator_ids: Vec<std::collections::BTreeSet<TermId>>,
}
fn key_of_block(value: &Block) -> BlockId {
    value.id
}
fn key_of_edge(value: &Edge) -> EdgeId {
    value.id
}
fn key_of_function(value: &Function) -> FunctionId {
    value.function_id
}
fn key_of_inst(value: &Inst) -> InstId {
    value.id
}
fn key_of_terminator(value: &Terminator) -> TermId {
    match value {
        Terminator::Branch { id, .. } => *id,
        Terminator::BranchIf { id, .. } => *id,
        Terminator::BranchIfZero { id, .. } => *id,
        Terminator::JumpTable { id, .. } => *id,
        Terminator::Return { id, .. } => *id,
    }
}
fn validate_block(value: &Block, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    if let Some(value) = value.docs.as_ref() {}
    for value in value.insts.iter() {
        if !ctx.inst_ids.iter().rev().any(|ids| ids.contains(value)) {
            errors.push(format!(
                "Block.insts references {:?} but no live Inst collection in scope contains it",
                value
            ));
        }
    }
    for value in value.params.iter() {}
    for value in value.preds.iter() {
        if !ctx.edge_ids.iter().rev().any(|ids| ids.contains(value)) {
            errors.push(format!(
                "Block.preds references {:?} but no live Edge collection in scope contains it",
                value
            ));
        }
    }
    for value in value.succs.iter() {
        if !ctx.edge_ids.iter().rev().any(|ids| ids.contains(value)) {
            errors.push(format!(
                "Block.succs references {:?} but no live Edge collection in scope contains it",
                value
            ));
        }
    }
    if !ctx
        .terminator_ids
        .iter()
        .rev()
        .any(|ids| ids.contains(&value.term))
    {
        errors.push(format!(
            "Block.term references {:?} but no live Terminator collection in scope contains it",
            value.term
        ));
    }
}
fn validate_const_ref(value: &ConstRef, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    match value {
        ConstRef::Named { name, prov, .. } => {
            let _ = (ctx, errors);
        }
        ConstRef::Value { prov, value, .. } => {
            let _ = (ctx, errors);
        }
    }
}
fn validate_data_args_line(
    value: &DataArgsLine,

    ctx: &mut ValidationContext,

    errors: &mut ErrorSink,
) {
    for value in value.args.iter() {}
    if let Some(value) = value.docs.as_ref() {}
}
fn validate_data_results_line(
    value: &DataResultsLine,

    ctx: &mut ValidationContext,

    errors: &mut ErrorSink,
) {
    if let Some(value) = value.docs.as_ref() {}
    for value in value.results.iter() {}
}
fn validate_edge(value: &Edge, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    for value in value.args.iter() {
        validate_edge_arg(value, ctx, errors);
    }
    if let Some(value) = value.docs.as_ref() {}
    if !ctx
        .block_ids
        .iter()
        .rev()
        .any(|ids| ids.contains(&value.from))
    {
        errors.push(format!(
            "Edge.from references {:?} but no live Block collection in scope contains it",
            value.from
        ));
    }
    if !ctx
        .block_ids
        .iter()
        .rev()
        .any(|ids| ids.contains(&value.to))
    {
        errors.push(format!(
            "Edge.to references {:?} but no live Block collection in scope contains it",
            value.to
        ));
    }
}
fn validate_edge_arg(value: &EdgeArg, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    match value {
        EdgeArg::Identity { prov, vreg, .. } => {
            let _ = (ctx, errors);
        }
        EdgeArg::Mapped {
            prov,
            source,
            target,
            ..
        } => {
            let _ = (ctx, errors);
        }
    }
}
fn validate_fixed_reg(value: &FixedReg, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    match value {
        FixedReg::AbiArg { index, prov, .. } => {
            let _ = (ctx, errors);
        }
        FixedReg::AbiRet { index, prov, .. } => {
            let _ = (ctx, errors);
        }
        FixedReg::HwReg { index, prov, .. } => {
            let _ = (ctx, errors);
        }
    }
}
fn validate_function(value: &Function, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    ctx.block_ids
        .push(value.blocks.iter().map(key_of_block).collect());
    ctx.edge_ids
        .push(value.edges.iter().map(key_of_edge).collect());
    ctx.terminator_ids
        .push(value.terms.iter().map(key_of_terminator).collect());
    for value in value.blocks.iter() {
        validate_block(value, ctx, errors);
    }
    validate_data_args_line(&value.data_args, ctx, errors);
    validate_data_results_line(&value.data_results, ctx, errors);
    if let Some(value) = value.docs.as_ref() {}
    for value in value.edges.iter() {
        validate_edge(value, ctx, errors);
    }
    if !ctx
        .block_ids
        .iter()
        .rev()
        .any(|ids| ids.contains(&value.entry))
    {
        errors.push(format!(
            "Function.entry references {:?} but no live Block collection in scope contains it",
            value.entry
        ));
    }
    for value in value.terms.iter() {
        validate_terminator(value, ctx, errors);
    }
    ctx.terminator_ids.pop();
    ctx.edge_ids.pop();
    ctx.block_ids.pop();
}
fn validate_inst(value: &Inst, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    if let Some(value) = value.clobbers.as_ref() {}
    if let Some(value) = value.defs.as_ref() {
        for value in value.iter() {
            validate_operand(value, ctx, errors);
        }
    }
    if let Some(value) = value.docs.as_ref() {}
    validate_inst_op(&value.op, ctx, errors);
    if let Some(value) = value.uses.as_ref() {
        for value in value.iter() {
            validate_operand(value, ctx, errors);
        }
    }
}
fn validate_inst_op(value: &InstOp, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    match value {
        InstOp::BinOp { op, prov, .. } => {
            let _ = (ctx, errors);
        }
        InstOp::CallEffect { func, prov, .. } => {
            validate_intrinsic_ref(func, ctx, errors);
        }
        InstOp::CallIntrinsic { func, prov, .. } => {
            validate_intrinsic_ref(func, ctx, errors);
        }
        InstOp::CallLambda { prov, target, .. } => {
            let _ = (ctx, errors);
        }
        InstOp::CallPure { func, prov, .. } => {
            validate_intrinsic_ref(func, ctx, errors);
        }
        InstOp::Const { prov, value, .. } => {
            validate_const_ref(value, ctx, errors);
        }
        InstOp::Copy(_inner) => {
            let _ = (ctx, errors);
        }
        InstOp::DataAddr { blob_id, prov, .. } => {
            let _ = (ctx, errors);
        }
        InstOp::ExternAddr { prov, symbol, .. } => {
            validate_intrinsic_ref(symbol, ctx, errors);
        }
        InstOp::LoadFromAddr { prov, width, .. } => {
            let _ = (ctx, errors);
        }
        InstOp::ReadFromSlot { prov, slot, .. } => {
            let _ = (ctx, errors);
        }
        InstOp::StackAlloc { id, prov, .. } => {
            let _ = (ctx, errors);
        }
        InstOp::StoreToAddr { prov, width, .. } => {
            let _ = (ctx, errors);
        }
        InstOp::UnaryOp { op, prov, .. } => {
            validate_unary_op(op, ctx, errors);
        }
        InstOp::WriteToSlot { prov, slot, .. } => {
            let _ = (ctx, errors);
        }
    }
}
fn validate_intrinsic_ref(
    value: &IntrinsicRef,

    ctx: &mut ValidationContext,

    errors: &mut ErrorSink,
) {
    match value {
        IntrinsicRef::Address { prov, value, .. } => {
            let _ = (ctx, errors);
        }
        IntrinsicRef::Named { name, prov, .. } => {
            let _ = (ctx, errors);
        }
    }
}
fn validate_operand(value: &Operand, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    if let Some(value) = value.fixed.as_ref() {
        validate_fixed_reg(value, ctx, errors);
    }
}
fn validate_program(value: &Program, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    ctx.function_ids
        .push(value.functions.iter().map(key_of_function).collect());
    if let Some(value) = value.docs.as_ref() {}
    for value in value.functions.iter() {
        validate_function(value, ctx, errors);
    }
    ctx.function_ids.pop();
}
fn validate_terminator(value: &Terminator, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    match value {
        Terminator::Branch { edge, id, prov, .. } => {
            if !ctx.edge_ids.iter().rev().any(|ids| ids.contains(edge)) {
                errors
                    .push(
                        format!(
                            "Terminator.Branch.edge references {:?} but no live Edge collection in scope contains it",
                            edge
                        ),
                    );
            }
        }
        Terminator::BranchIf {
            cond,
            fallthrough,
            id,
            prov,
            taken,
            ..
        } => {
            if !ctx
                .edge_ids
                .iter()
                .rev()
                .any(|ids| ids.contains(fallthrough))
            {
                errors
                    .push(
                        format!(
                            "Terminator.BranchIf.fallthrough references {:?} but no live Edge collection in scope contains it",
                            fallthrough
                        ),
                    );
            }
            if !ctx.edge_ids.iter().rev().any(|ids| ids.contains(taken)) {
                errors
                    .push(
                        format!(
                            "Terminator.BranchIf.taken references {:?} but no live Edge collection in scope contains it",
                            taken
                        ),
                    );
            }
        }
        Terminator::BranchIfZero {
            cond,
            fallthrough,
            id,
            prov,
            taken,
            ..
        } => {
            if !ctx
                .edge_ids
                .iter()
                .rev()
                .any(|ids| ids.contains(fallthrough))
            {
                errors
                    .push(
                        format!(
                            "Terminator.BranchIfZero.fallthrough references {:?} but no live Edge collection in scope contains it",
                            fallthrough
                        ),
                    );
            }
            if !ctx.edge_ids.iter().rev().any(|ids| ids.contains(taken)) {
                errors
                    .push(
                        format!(
                            "Terminator.BranchIfZero.taken references {:?} but no live Edge collection in scope contains it",
                            taken
                        ),
                    );
            }
        }
        Terminator::JumpTable {
            default,
            id,
            predicate,
            prov,
            targets,
            ..
        } => {
            if !ctx.edge_ids.iter().rev().any(|ids| ids.contains(default)) {
                errors
                    .push(
                        format!(
                            "Terminator.JumpTable.default references {:?} but no live Edge collection in scope contains it",
                            default
                        ),
                    );
            }
            for value in targets.iter() {
                if !ctx.edge_ids.iter().rev().any(|ids| ids.contains(value)) {
                    errors
                        .push(
                            format!(
                                "Terminator.JumpTable.targets references {:?} but no live Edge collection in scope contains it",
                                value
                            ),
                        );
                }
            }
        }
        Terminator::Return { id, prov, .. } => {
            let _ = (ctx, errors);
        }
    }
}
fn validate_unary_op(value: &UnaryOp, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    match value {
        UnaryOp::SignExtend {
            from_width, prov, ..
        } => {
            let _ = (ctx, errors);
        }
    }
}
pub fn validate_root_in_graph(graph: &Graph, handle: ProgramHandle) -> Result<(), String> {
    let Some(root) = graph.root(handle) else {
        return Err(format!("unknown root handle {:?}", handle));
    };
    let mut ctx = ValidationContext::default();
    let mut errors = ErrorSink::default();
    ctx.inst_ids
        .push(graph.all_inst().map(key_of_inst).collect());
    for value in graph.all_inst() {
        validate_inst(value, &mut ctx, &mut errors);
    }
    validate_program(root, &mut ctx, &mut errors);
    let errors = errors.into_vec();
    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors.join("\n"))
    }
}
pub fn validate_root_text(source: &str) -> Result<(), String> {
    let mut graph = Graph::new();
    let handle = parse_root_into_graph(&mut graph, source)?;
    validate_root_in_graph(&graph, handle)
}
