[workspace]
members = [
  "kajit",
  "kajit-emit",
  "kajit-emit-text",
  "kajit-format",
  "kajit-hir",
  "kajit-malum",
  "kajit-postcard",
  "kajit-hir-text",
  "kajit-ir",
  "kajit-ir-text",
  "kajit-lir",
  "kajit-mir",
  "kajit-cli",
  "kajit-mir-text",
  "kajit-parse-util",
  "xtask",
  "vendor/lldb-rs",
  "vendor/lldb-sys-rs",
]
resolver = "3"

[profile.profiling]
inherits = "release"
debug = "line-tables-only"
