// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#![allow(dead_code, unused_variables)]
use super::*;
pub fn format_root_text(node: &Program) -> String {
    format_program(node)
}
pub fn format_program_text(node: &Program) -> String {
    format_root_text(node)
}

impl std::fmt::Display for Program {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&format_root_text(self))
    }
}
const INDENT_WIDTH: usize = 4;
struct Writer {

    out: String,

    indent: usize,

    at_line_start: bool,
}

impl Writer {
    fn new() -> Self {
        Self {
            out: String::new(),
            indent: 0,
            at_line_start: false,
        }
    }
    fn text(&mut self, text: &str) {
        for ch in text.chars() {
            if self.at_line_start && ch != '\n' {
                for _ in 0..self.indent {
                    self.out.push(' ');
                }
                self.at_line_start = false;
            }
            self.out.push(ch);
            if ch == '\n' {
                self.at_line_start = true;
            }
        }
    }
    fn with_indent(&mut self, f: impl FnOnce(&mut Self)) {
        self.indent += INDENT_WIDTH;
        f(self);
        self.indent -= INDENT_WIDTH;
    }
    fn finish(self) -> String {
        self.out
    }
}
pub fn format_a64_item(node: &A64Item) -> String {
    let mut w = Writer::new();
    write_a64_item(&mut w, node);
    w.finish()
}
fn write_a64_item(w: &mut Writer, node: &A64Item) {
    match node {
        A64Item::AddImm { imm, op, rd, rn, .. } => {
            write_add_keyword(w, &op);
            w.text(" ");
            write_a64_reg(w, &rd);
            w.text(", ");
            write_a64_reg(w, &rn);
            w.text(", ");
            w.text(&imm.value.to_string());
        }
        A64Item::B { op, target, .. } => {
            write_b_keyword(w, &op);
            w.text(" ");
            w.text(&target.text);
        }
        A64Item::Label { name, .. } => {
            w.text(&name.text);
            w.text(":");
        }
        A64Item::Mov { op, rd, rm, .. } => {
            write_mov_keyword(w, &op);
            w.text(" ");
            write_a64_reg(w, &rd);
            w.text(", ");
            write_a64_reg(w, &rm);
        }
        A64Item::Movz { imm, op, rd, .. } => {
            write_movz_keyword(w, &op);
            w.text(" ");
            write_a64_reg(w, &rd);
            w.text(", ");
            w.text(&imm.value.to_string());
        }
        A64Item::Nop { op, .. } => {
            write_nop_keyword(w, &op);
        }
        A64Item::Ret { op, .. } => {
            write_ret_keyword(w, &op);
        }
    }
}
pub fn format_a64_reg(node: &A64Reg) -> String {
    let mut w = Writer::new();
    write_a64_reg(&mut w, node);
    w.finish()
}
fn write_a64_reg(w: &mut Writer, node: &A64Reg) {
    match node {
        A64Reg::Sp(_value) => {
            w.text("sp");
        }
        A64Reg::X0(_value) => {
            w.text("x0");
        }
        A64Reg::X1(_value) => {
            w.text("x1");
        }
        A64Reg::X2(_value) => {
            w.text("x2");
        }
        A64Reg::X3(_value) => {
            w.text("x3");
        }
    }
}
pub fn format_a_arch64_dialect_keyword(node: &AArch64DialectKeyword) -> String {
    let mut w = Writer::new();
    write_a_arch64_dialect_keyword(&mut w, node);
    w.finish()
}
fn write_a_arch64_dialect_keyword(w: &mut Writer, node: &AArch64DialectKeyword) {
    w.text("aarch64");
}
pub fn format_add_keyword(node: &AddKeyword) -> String {
    let mut w = Writer::new();
    write_add_keyword(&mut w, node);
    w.finish()
}
fn write_add_keyword(w: &mut Writer, node: &AddKeyword) {
    w.text("add");
}
pub fn format_asm_keyword(node: &AsmKeyword) -> String {
    let mut w = Writer::new();
    write_asm_keyword(&mut w, node);
    w.finish()
}
fn write_asm_keyword(w: &mut Writer, node: &AsmKeyword) {
    w.text("asm");
}
pub fn format_b_keyword(node: &BKeyword) -> String {
    let mut w = Writer::new();
    write_b_keyword(&mut w, node);
    w.finish()
}
fn write_b_keyword(w: &mut Writer, node: &BKeyword) {
    w.text("b");
}
pub fn format_jmp_keyword(node: &JmpKeyword) -> String {
    let mut w = Writer::new();
    write_jmp_keyword(&mut w, node);
    w.finish()
}
fn write_jmp_keyword(w: &mut Writer, node: &JmpKeyword) {
    w.text("jmp");
}
pub fn format_mov_keyword(node: &MovKeyword) -> String {
    let mut w = Writer::new();
    write_mov_keyword(&mut w, node);
    w.finish()
}
fn write_mov_keyword(w: &mut Writer, node: &MovKeyword) {
    w.text("mov");
}
pub fn format_movz_keyword(node: &MovzKeyword) -> String {
    let mut w = Writer::new();
    write_movz_keyword(&mut w, node);
    w.finish()
}
fn write_movz_keyword(w: &mut Writer, node: &MovzKeyword) {
    w.text("movz");
}
pub fn format_nop_keyword(node: &NopKeyword) -> String {
    let mut w = Writer::new();
    write_nop_keyword(&mut w, node);
    w.finish()
}
fn write_nop_keyword(w: &mut Writer, node: &NopKeyword) {
    w.text("nop");
}
pub fn format_program(node: &Program) -> String {
    let mut w = Writer::new();
    write_program(&mut w, node);
    w.finish()
}
fn write_program(w: &mut Writer, node: &Program) {
    match node {
        Program::AArch64 { dialect, items, keyword, .. } => {
            write_asm_keyword(w, &keyword);
            w.text(" ");
            write_a_arch64_dialect_keyword(w, &dialect);
            w.text(" ");
            w.text("{");
            w.text("\n");
            for (idx, value) in items.iter().enumerate() {
                if idx != 0 {
                    w.text("\n");
                }
                w.with_indent(|w| {
                    write_a64_item(w, &value);
                });
            }
            w.text("\n}");
        }
        Program::X86_64 { dialect, items, keyword, .. } => {
            write_asm_keyword(w, &keyword);
            w.text(" ");
            write_x86_64_dialect_keyword(w, &dialect);
            w.text(" ");
            w.text("{");
            w.text("\n");
            for (idx, value) in items.iter().enumerate() {
                if idx != 0 {
                    w.text("\n");
                }
                w.with_indent(|w| {
                    write_x64_item(w, &value);
                });
            }
            w.text("\n}");
        }
    }
}
pub fn format_ret_keyword(node: &RetKeyword) -> String {
    let mut w = Writer::new();
    write_ret_keyword(&mut w, node);
    w.finish()
}
fn write_ret_keyword(w: &mut Writer, node: &RetKeyword) {
    w.text("ret");
}
pub fn format_x64_item(node: &X64Item) -> String {
    let mut w = Writer::new();
    write_x64_item(&mut w, node);
    w.finish()
}
fn write_x64_item(w: &mut Writer, node: &X64Item) {
    match node {
        X64Item::AddImm { imm, op, rd, .. } => {
            write_add_keyword(w, &op);
            w.text(" ");
            write_x64_reg(w, &rd);
            w.text(", ");
            w.text(&imm.value.to_string());
        }
        X64Item::Jmp { op, target, .. } => {
            write_jmp_keyword(w, &op);
            w.text(" ");
            w.text(&target.text);
        }
        X64Item::Label { name, .. } => {
            w.text(&name.text);
            w.text(":");
        }
        X64Item::MovImm { imm, op, rd, .. } => {
            write_mov_keyword(w, &op);
            w.text(" ");
            write_x64_reg(w, &rd);
            w.text(", ");
            w.text(&imm.value.to_string());
        }
        X64Item::MovReg { op, rd, rm, .. } => {
            write_mov_keyword(w, &op);
            w.text(" ");
            write_x64_reg(w, &rd);
            w.text(", ");
            write_x64_reg(w, &rm);
        }
        X64Item::Nop { op, .. } => {
            write_nop_keyword(w, &op);
        }
        X64Item::Ret { op, .. } => {
            write_ret_keyword(w, &op);
        }
    }
}
pub fn format_x64_reg(node: &X64Reg) -> String {
    let mut w = Writer::new();
    write_x64_reg(&mut w, node);
    w.finish()
}
fn write_x64_reg(w: &mut Writer, node: &X64Reg) {
    match node {
        X64Reg::Rax(_value) => {
            w.text("rax");
        }
        X64Reg::Rbp(_value) => {
            w.text("rbp");
        }
        X64Reg::Rbx(_value) => {
            w.text("rbx");
        }
        X64Reg::Rcx(_value) => {
            w.text("rcx");
        }
        X64Reg::Rdx(_value) => {
            w.text("rdx");
        }
        X64Reg::Rsp(_value) => {
            w.text("rsp");
        }
    }
}
pub fn format_x86_64_dialect_keyword(node: &X86_64DialectKeyword) -> String {
    let mut w = Writer::new();
    write_x86_64_dialect_keyword(&mut w, node);
    w.finish()
}
fn write_x86_64_dialect_keyword(w: &mut Writer, node: &X86_64DialectKeyword) {
    w.text("x86_64");
}
