// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#![allow(dead_code, unused_variables)]
use super::provenance::HasProvenance;
use super::*;
use crate::HoverEntry;
use kajit_types::Prov;
pub fn hover_entries(source: &str) -> Vec<HoverEntry> {
    let Ok(root) = parse_root_text_rich(source, None) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    collect_program(&root, &mut out);
    out.sort_by_key(|entry| (entry.start, entry.end, entry.priority));
    out.dedup_by(|a, b| a.start == b.start && a.end == b.end && a.markdown == b.markdown);
    out
}
fn emit_hover(prov: &Prov, markdown: &str, priority: u8, out: &mut Vec<HoverEntry>) {
    let Some(span) = prov.span.as_ref() else {
        return;
    };
    if span.end <= span.start {
        return;
    }
    out.push(HoverEntry {
        start: span.start,
        end: span.end,
        markdown: markdown.to_owned(),
        priority,
    });
}
fn collect_a64_item(node: &A64Item, out: &mut Vec<HoverEntry>) {
    match node {
        A64Item::AddImm {
            imm,
            op,
            prov,
            rd,
            rn,
        } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Add an immediate to a register.", 40, out);
            }
            emit_hover(
                &imm.prov,
                "Add an immediate to a register.\n\nImmediate value.",
                30,
                out,
            );
            if let Some(prov) = op.provenance() {
                emit_hover(
                    prov,
                    "Add an immediate to a register.\n\nOpcode keyword.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rd.provenance() {
                emit_hover(
                    prov,
                    "Add an immediate to a register.\n\nDestination register.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rn.provenance() {
                emit_hover(
                    prov,
                    "Add an immediate to a register.\n\nBase register.",
                    30,
                    out,
                );
            }
            collect_add_keyword(op, out);
            collect_a64_reg(rd, out);
            collect_a64_reg(rn, out);
        }
        A64Item::AddReg {
            op,
            prov,
            rd,
            rm,
            rn,
        } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Add a register to a register.", 40, out);
            }
            if let Some(prov) = op.provenance() {
                emit_hover(
                    prov,
                    "Add a register to a register.\n\nOpcode keyword.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rd.provenance() {
                emit_hover(
                    prov,
                    "Add a register to a register.\n\nDestination register.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rm.provenance() {
                emit_hover(
                    prov,
                    "Add a register to a register.\n\nRight-hand operand register.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rn.provenance() {
                emit_hover(
                    prov,
                    "Add a register to a register.\n\nLeft-hand operand register.",
                    30,
                    out,
                );
            }
            collect_add_keyword(op, out);
            collect_a64_reg(rd, out);
            collect_a64_reg(rm, out);
            collect_a64_reg(rn, out);
        }
        A64Item::B { op, prov, target } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Branch to a symbolic label.", 40, out);
            }
            if let Some(prov) = op.provenance() {
                emit_hover(
                    prov,
                    "Branch to a symbolic label.\n\nOpcode keyword.",
                    30,
                    out,
                );
            }
            emit_hover(
                &target.prov,
                "Branch to a symbolic label.\n\nBranch target label.",
                30,
                out,
            );
            collect_b_keyword(op, out);
        }
        A64Item::Label { name, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "A symbolic label definition.", 40, out);
            }
            emit_hover(
                &name.prov,
                "A symbolic label definition.\n\nLabel name.",
                30,
                out,
            );
        }
        A64Item::Mov { op, prov, rd, rm } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Move a register into another register.", 40, out);
            }
            if let Some(prov) = op.provenance() {
                emit_hover(
                    prov,
                    "Move a register into another register.\n\nOpcode keyword.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rd.provenance() {
                emit_hover(
                    prov,
                    "Move a register into another register.\n\nDestination register.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rm.provenance() {
                emit_hover(
                    prov,
                    "Move a register into another register.\n\nSource register.",
                    30,
                    out,
                );
            }
            collect_mov_keyword(op, out);
            collect_a64_reg(rd, out);
            collect_a64_reg(rm, out);
        }
        A64Item::Movz { imm, op, prov, rd } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Move an immediate into a register.", 40, out);
            }
            emit_hover(
                &imm.prov,
                "Move an immediate into a register.\n\nImmediate value.",
                30,
                out,
            );
            if let Some(prov) = op.provenance() {
                emit_hover(
                    prov,
                    "Move an immediate into a register.\n\nOpcode keyword.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rd.provenance() {
                emit_hover(
                    prov,
                    "Move an immediate into a register.\n\nDestination register.",
                    30,
                    out,
                );
            }
            collect_movz_keyword(op, out);
            collect_a64_reg(rd, out);
        }
        A64Item::Nop { op, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "A no-op instruction.", 40, out);
            }
            if let Some(prov) = op.provenance() {
                emit_hover(prov, "A no-op instruction.\n\nOpcode keyword.", 30, out);
            }
            collect_nop_keyword(op, out);
        }
        A64Item::Ret { op, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "A return instruction.", 40, out);
            }
            if let Some(prov) = op.provenance() {
                emit_hover(prov, "A return instruction.\n\nOpcode keyword.", 30, out);
            }
            collect_ret_keyword(op, out);
        }
        A64Item::SubReg {
            op,
            prov,
            rd,
            rm,
            rn,
        } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Subtract a register from a register.", 40, out);
            }
            if let Some(prov) = op.provenance() {
                emit_hover(
                    prov,
                    "Subtract a register from a register.\n\nOpcode keyword.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rd.provenance() {
                emit_hover(
                    prov,
                    "Subtract a register from a register.\n\nDestination register.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rm.provenance() {
                emit_hover(
                    prov,
                    "Subtract a register from a register.\n\nRight-hand operand register.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rn.provenance() {
                emit_hover(
                    prov,
                    "Subtract a register from a register.\n\nLeft-hand operand register.",
                    30,
                    out,
                );
            }
            collect_sub_keyword(op, out);
            collect_a64_reg(rd, out);
            collect_a64_reg(rm, out);
            collect_a64_reg(rn, out);
        }
    }
}
fn collect_a64_reg(node: &A64Reg, out: &mut Vec<HoverEntry>) {
    match node {
        A64Reg::Sp(value) => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Stack pointer register.", 40, out);
            }
        }
        A64Reg::X0(value) => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "General-purpose register x0.", 40, out);
            }
        }
        A64Reg::X1(value) => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "General-purpose register x1.", 40, out);
            }
        }
        A64Reg::X2(value) => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "General-purpose register x2.", 40, out);
            }
        }
        A64Reg::X3(value) => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "General-purpose register x3.", 40, out);
            }
        }
    }
}
fn collect_a_arch64_dialect_keyword(node: &AArch64DialectKeyword, out: &mut Vec<HoverEntry>) {
    if let Some(prov) = node.provenance() {
        emit_hover(prov, "The AArch64 dialect tag in the header.", 10, out);
    }
}
fn collect_add_keyword(node: &AddKeyword, out: &mut Vec<HoverEntry>) {
    if let Some(prov) = node.provenance() {
        emit_hover(prov, "Add an operand to a destination register.", 10, out);
    }
}
fn collect_asm_keyword(node: &AsmKeyword, out: &mut Vec<HoverEntry>) {
    if let Some(prov) = node.provenance() {
        emit_hover(
            prov,
            "The fixed leading keyword in an ASM document header.",
            10,
            out,
        );
    }
}
fn collect_b_keyword(node: &BKeyword, out: &mut Vec<HoverEntry>) {
    if let Some(prov) = node.provenance() {
        emit_hover(prov, "Branch to a label in AArch64.", 10, out);
    }
}
fn collect_jmp_keyword(node: &JmpKeyword, out: &mut Vec<HoverEntry>) {
    if let Some(prov) = node.provenance() {
        emit_hover(prov, "Jump to a label in x86-64.", 10, out);
    }
}
fn collect_mov_keyword(node: &MovKeyword, out: &mut Vec<HoverEntry>) {
    if let Some(prov) = node.provenance() {
        emit_hover(prov, "Move data between registers or operands.", 10, out);
    }
}
fn collect_movz_keyword(node: &MovzKeyword, out: &mut Vec<HoverEntry>) {
    if let Some(prov) = node.provenance() {
        emit_hover(
            prov,
            "Move a zero-extended immediate into a register.",
            10,
            out,
        );
    }
}
fn collect_nop_keyword(node: &NopKeyword, out: &mut Vec<HoverEntry>) {
    if let Some(prov) = node.provenance() {
        emit_hover(prov, "Perform no operation.", 10, out);
    }
}
fn collect_program(node: &Program, out: &mut Vec<HoverEntry>) {
    match node {
        Program::AArch64 {
            dialect,
            docs,
            items,
            keyword,
            prov,
        } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "An AArch64 assembly unit.", 40, out);
            }
            if let Some(prov) = dialect.provenance() {
                emit_hover(
                    prov,
                    "An AArch64 assembly unit.\n\nDialect tag from the header.",
                    30,
                    out,
                );
            }
            if let Some(prov) = keyword.provenance() {
                emit_hover(
                    prov,
                    "An AArch64 assembly unit.\n\nLeading `asm` keyword.",
                    30,
                    out,
                );
            }
            collect_a_arch64_dialect_keyword(dialect, out);
            for value in items {
                collect_a64_item(value, out);
            }
            collect_asm_keyword(keyword, out);
        }
        Program::X86_64 {
            dialect,
            docs,
            items,
            keyword,
            prov,
        } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "An x86-64 assembly unit.", 40, out);
            }
            if let Some(prov) = dialect.provenance() {
                emit_hover(
                    prov,
                    "An x86-64 assembly unit.\n\nDialect tag from the header.",
                    30,
                    out,
                );
            }
            if let Some(prov) = keyword.provenance() {
                emit_hover(
                    prov,
                    "An x86-64 assembly unit.\n\nLeading `asm` keyword.",
                    30,
                    out,
                );
            }
            collect_x86_64_dialect_keyword(dialect, out);
            for value in items {
                collect_x64_item(value, out);
            }
            collect_asm_keyword(keyword, out);
        }
    }
}
fn collect_ret_keyword(node: &RetKeyword, out: &mut Vec<HoverEntry>) {
    if let Some(prov) = node.provenance() {
        emit_hover(prov, "Return from the current function.", 10, out);
    }
}
fn collect_sub_keyword(node: &SubKeyword, out: &mut Vec<HoverEntry>) {
    if let Some(prov) = node.provenance() {
        emit_hover(
            prov,
            "Subtract an operand from a destination register.",
            10,
            out,
        );
    }
}
fn collect_x64_item(node: &X64Item, out: &mut Vec<HoverEntry>) {
    match node {
        X64Item::AddImm { imm, op, prov, rd } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Add an immediate to a register.", 40, out);
            }
            emit_hover(
                &imm.prov,
                "Add an immediate to a register.\n\nImmediate value.",
                30,
                out,
            );
            if let Some(prov) = op.provenance() {
                emit_hover(
                    prov,
                    "Add an immediate to a register.\n\nOpcode keyword.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rd.provenance() {
                emit_hover(
                    prov,
                    "Add an immediate to a register.\n\nDestination register.",
                    30,
                    out,
                );
            }
            collect_add_keyword(op, out);
            collect_x64_reg(rd, out);
        }
        X64Item::AddReg { op, prov, rd, rm } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Add a register to a register.", 40, out);
            }
            if let Some(prov) = op.provenance() {
                emit_hover(
                    prov,
                    "Add a register to a register.\n\nOpcode keyword.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rd.provenance() {
                emit_hover(
                    prov,
                    "Add a register to a register.\n\nDestination register.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rm.provenance() {
                emit_hover(
                    prov,
                    "Add a register to a register.\n\nSource register.",
                    30,
                    out,
                );
            }
            collect_add_keyword(op, out);
            collect_x64_reg(rd, out);
            collect_x64_reg(rm, out);
        }
        X64Item::Jmp { op, prov, target } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Jump to a symbolic label.", 40, out);
            }
            if let Some(prov) = op.provenance() {
                emit_hover(
                    prov,
                    "Jump to a symbolic label.\n\nOpcode keyword.",
                    30,
                    out,
                );
            }
            emit_hover(
                &target.prov,
                "Jump to a symbolic label.\n\nJump target label.",
                30,
                out,
            );
            collect_jmp_keyword(op, out);
        }
        X64Item::Label { name, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "A symbolic label definition.", 40, out);
            }
            emit_hover(
                &name.prov,
                "A symbolic label definition.\n\nLabel name.",
                30,
                out,
            );
        }
        X64Item::MovImm { imm, op, prov, rd } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Move an immediate into a register.", 40, out);
            }
            emit_hover(
                &imm.prov,
                "Move an immediate into a register.\n\nImmediate value.",
                30,
                out,
            );
            if let Some(prov) = op.provenance() {
                emit_hover(
                    prov,
                    "Move an immediate into a register.\n\nOpcode keyword.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rd.provenance() {
                emit_hover(
                    prov,
                    "Move an immediate into a register.\n\nDestination register.",
                    30,
                    out,
                );
            }
            collect_mov_keyword(op, out);
            collect_x64_reg(rd, out);
        }
        X64Item::MovReg { op, prov, rd, rm } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Move a register into another register.", 40, out);
            }
            if let Some(prov) = op.provenance() {
                emit_hover(
                    prov,
                    "Move a register into another register.\n\nOpcode keyword.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rd.provenance() {
                emit_hover(
                    prov,
                    "Move a register into another register.\n\nDestination register.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rm.provenance() {
                emit_hover(
                    prov,
                    "Move a register into another register.\n\nSource register.",
                    30,
                    out,
                );
            }
            collect_mov_keyword(op, out);
            collect_x64_reg(rd, out);
            collect_x64_reg(rm, out);
        }
        X64Item::Nop { op, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "A no-op instruction.", 40, out);
            }
            if let Some(prov) = op.provenance() {
                emit_hover(prov, "A no-op instruction.\n\nOpcode keyword.", 30, out);
            }
            collect_nop_keyword(op, out);
        }
        X64Item::Ret { op, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "A return instruction.", 40, out);
            }
            if let Some(prov) = op.provenance() {
                emit_hover(prov, "A return instruction.\n\nOpcode keyword.", 30, out);
            }
            collect_ret_keyword(op, out);
        }
        X64Item::SubReg { op, prov, rd, rm } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Subtract a register from a register.", 40, out);
            }
            if let Some(prov) = op.provenance() {
                emit_hover(
                    prov,
                    "Subtract a register from a register.\n\nOpcode keyword.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rd.provenance() {
                emit_hover(
                    prov,
                    "Subtract a register from a register.\n\nDestination register.",
                    30,
                    out,
                );
            }
            if let Some(prov) = rm.provenance() {
                emit_hover(
                    prov,
                    "Subtract a register from a register.\n\nSource register.",
                    30,
                    out,
                );
            }
            collect_sub_keyword(op, out);
            collect_x64_reg(rd, out);
            collect_x64_reg(rm, out);
        }
    }
}
fn collect_x64_reg(node: &X64Reg, out: &mut Vec<HoverEntry>) {
    match node {
        X64Reg::Rax(value) => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Return-value and accumulator register.", 40, out);
            }
        }
        X64Reg::Rbp(value) => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Base/frame pointer register.", 40, out);
            }
        }
        X64Reg::Rbx(value) => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Callee-saved general-purpose register.", 40, out);
            }
        }
        X64Reg::Rcx(value) => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Count register.", 40, out);
            }
        }
        X64Reg::Rdx(value) => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Data register.", 40, out);
            }
        }
        X64Reg::Rsp(value) => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Stack pointer register.", 40, out);
            }
        }
    }
}
fn collect_x86_64_dialect_keyword(node: &X86_64DialectKeyword, out: &mut Vec<HoverEntry>) {
    if let Some(prov) = node.provenance() {
        emit_hover(prov, "The x86-64 dialect tag in the header.", 10, out);
    }
}
