// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#![allow(dead_code, unused_variables)]
use super::provenance::HasProvenance;
use super::*;
use crate::SemanticToken;
use kajit_types::Prov;
pub fn semantic_tokens(source: &str) -> Vec<SemanticToken> {
    let Ok(root) = parse_root_text_rich(source, None) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    collect_program(source, &root, &mut out);
    out.sort_by_key(|token| (token.start, token.end, token.kind));
    out.dedup_by(|a, b| a.start == b.start && a.end == b.end && a.kind == b.kind);
    out
}
fn emit_prov_token(prov: &Prov, kind: &'static str, out: &mut Vec<SemanticToken>) {
    let Some(span) = prov.span.as_ref() else {
        return;
    };
    if span.end <= span.start {
        return;
    }
    out.push(SemanticToken {
        start: span.start,
        end: span.end,
        kind,
    });
}
fn emit_literal_token(
    source: &str,

    prov: Option<&Prov>,

    text: &str,

    kind: &'static str,

    out: &mut Vec<SemanticToken>,
) {
    let Some(prov) = prov else {
        return;
    };
    let Some(span) = prov.span.as_ref() else {
        return;
    };
    let start = span.start as usize;
    let end = span.end as usize;
    if start > end || end > source.len() {
        return;
    }
    let Some(offset) = source[start..end].find(text) else {
        return;
    };
    out.push(SemanticToken {
        start: (start + offset) as u32,
        end: (start + offset + text.len()) as u32,
        kind,
    });
}
fn collect_a64_item(source: &str, node: &A64Item, out: &mut Vec<SemanticToken>) {
    match node {
        A64Item::AddImm {
            imm,
            op,
            prov,
            rd,
            rn,
        } => {
            let current_prov = node.provenance();
            emit_prov_token(&imm.prov, "number", out);
            if let Some(prov) = op.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            collect_add_keyword(source, op, out);
            collect_a64_reg(source, rd, out);
            collect_a64_reg(source, rn, out);
        }
        A64Item::B { op, prov, target } => {
            let current_prov = node.provenance();
            if let Some(prov) = op.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            emit_prov_token(&target.prov, "label", out);
            collect_b_keyword(source, op, out);
        }
        A64Item::Label { name, prov } => {
            let current_prov = node.provenance();
            emit_prov_token(&name.prov, "label", out);
        }
        A64Item::Mov { op, prov, rd, rm } => {
            let current_prov = node.provenance();
            if let Some(prov) = op.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            collect_mov_keyword(source, op, out);
            collect_a64_reg(source, rd, out);
            collect_a64_reg(source, rm, out);
        }
        A64Item::Movz { imm, op, prov, rd } => {
            let current_prov = node.provenance();
            emit_prov_token(&imm.prov, "number", out);
            if let Some(prov) = op.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            collect_movz_keyword(source, op, out);
            collect_a64_reg(source, rd, out);
        }
        A64Item::Nop { op, prov } => {
            let current_prov = node.provenance();
            if let Some(prov) = op.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            collect_nop_keyword(source, op, out);
        }
        A64Item::Ret { op, prov } => {
            let current_prov = node.provenance();
            if let Some(prov) = op.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            collect_ret_keyword(source, op, out);
        }
    }
}
fn collect_a64_reg(source: &str, node: &A64Reg, out: &mut Vec<SemanticToken>) {
    match node {
        A64Reg::Sp(value) => {
            let current_prov = node.provenance();
            if let Some(prov) = node.provenance() {
                emit_prov_token(prov, "enumMember", out);
            }
        }
        A64Reg::X0(value) => {
            let current_prov = node.provenance();
            if let Some(prov) = node.provenance() {
                emit_prov_token(prov, "enumMember", out);
            }
        }
        A64Reg::X1(value) => {
            let current_prov = node.provenance();
            if let Some(prov) = node.provenance() {
                emit_prov_token(prov, "enumMember", out);
            }
        }
        A64Reg::X2(value) => {
            let current_prov = node.provenance();
            if let Some(prov) = node.provenance() {
                emit_prov_token(prov, "enumMember", out);
            }
        }
        A64Reg::X3(value) => {
            let current_prov = node.provenance();
            if let Some(prov) = node.provenance() {
                emit_prov_token(prov, "enumMember", out);
            }
        }
    }
}
fn collect_a_arch64_dialect_keyword(
    source: &str,

    node: &AArch64DialectKeyword,

    out: &mut Vec<SemanticToken>,
) {
    let current_prov = node.provenance();
}
fn collect_add_keyword(source: &str, node: &AddKeyword, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
}
fn collect_asm_keyword(source: &str, node: &AsmKeyword, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
}
fn collect_b_keyword(source: &str, node: &BKeyword, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
}
fn collect_jmp_keyword(source: &str, node: &JmpKeyword, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
}
fn collect_mov_keyword(source: &str, node: &MovKeyword, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
}
fn collect_movz_keyword(source: &str, node: &MovzKeyword, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
}
fn collect_nop_keyword(source: &str, node: &NopKeyword, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
}
fn collect_program(source: &str, node: &Program, out: &mut Vec<SemanticToken>) {
    match node {
        Program::AArch64 {
            dialect,
            docs,
            items,
            keyword,
            prov,
        } => {
            let current_prov = node.provenance();
            if let Some(prov) = dialect.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            if let Some(prov) = keyword.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            collect_a_arch64_dialect_keyword(source, dialect, out);
            for value in items {
                collect_a64_item(source, value, out);
            }
            collect_asm_keyword(source, keyword, out);
        }
        Program::X86_64 {
            dialect,
            docs,
            items,
            keyword,
            prov,
        } => {
            let current_prov = node.provenance();
            if let Some(prov) = dialect.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            if let Some(prov) = keyword.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            collect_x86_64_dialect_keyword(source, dialect, out);
            for value in items {
                collect_x64_item(source, value, out);
            }
            collect_asm_keyword(source, keyword, out);
        }
    }
}
fn collect_ret_keyword(source: &str, node: &RetKeyword, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
}
fn collect_x64_item(source: &str, node: &X64Item, out: &mut Vec<SemanticToken>) {
    match node {
        X64Item::AddImm { imm, op, prov, rd } => {
            let current_prov = node.provenance();
            emit_prov_token(&imm.prov, "number", out);
            if let Some(prov) = op.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            collect_add_keyword(source, op, out);
            collect_x64_reg(source, rd, out);
        }
        X64Item::Jmp { op, prov, target } => {
            let current_prov = node.provenance();
            if let Some(prov) = op.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            emit_prov_token(&target.prov, "label", out);
            collect_jmp_keyword(source, op, out);
        }
        X64Item::Label { name, prov } => {
            let current_prov = node.provenance();
            emit_prov_token(&name.prov, "label", out);
        }
        X64Item::MovImm { imm, op, prov, rd } => {
            let current_prov = node.provenance();
            emit_prov_token(&imm.prov, "number", out);
            if let Some(prov) = op.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            collect_mov_keyword(source, op, out);
            collect_x64_reg(source, rd, out);
        }
        X64Item::MovReg { op, prov, rd, rm } => {
            let current_prov = node.provenance();
            if let Some(prov) = op.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            collect_mov_keyword(source, op, out);
            collect_x64_reg(source, rd, out);
            collect_x64_reg(source, rm, out);
        }
        X64Item::Nop { op, prov } => {
            let current_prov = node.provenance();
            if let Some(prov) = op.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            collect_nop_keyword(source, op, out);
        }
        X64Item::Ret { op, prov } => {
            let current_prov = node.provenance();
            if let Some(prov) = op.provenance() {
                emit_prov_token(prov, "keyword", out);
            }
            collect_ret_keyword(source, op, out);
        }
    }
}
fn collect_x64_reg(source: &str, node: &X64Reg, out: &mut Vec<SemanticToken>) {
    match node {
        X64Reg::Rax(value) => {
            let current_prov = node.provenance();
            if let Some(prov) = node.provenance() {
                emit_prov_token(prov, "enumMember", out);
            }
        }
        X64Reg::Rbp(value) => {
            let current_prov = node.provenance();
            if let Some(prov) = node.provenance() {
                emit_prov_token(prov, "enumMember", out);
            }
        }
        X64Reg::Rbx(value) => {
            let current_prov = node.provenance();
            if let Some(prov) = node.provenance() {
                emit_prov_token(prov, "enumMember", out);
            }
        }
        X64Reg::Rcx(value) => {
            let current_prov = node.provenance();
            if let Some(prov) = node.provenance() {
                emit_prov_token(prov, "enumMember", out);
            }
        }
        X64Reg::Rdx(value) => {
            let current_prov = node.provenance();
            if let Some(prov) = node.provenance() {
                emit_prov_token(prov, "enumMember", out);
            }
        }
        X64Reg::Rsp(value) => {
            let current_prov = node.provenance();
            if let Some(prov) = node.provenance() {
                emit_prov_token(prov, "enumMember", out);
            }
        }
    }
}
fn collect_x86_64_dialect_keyword(
    source: &str,

    node: &X86_64DialectKeyword,

    out: &mut Vec<SemanticToken>,
) {
    let current_prov = node.provenance();
}
