// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#![allow(unused_variables)]
use super::*;

pub trait Visit {
    fn visit_a64_item(&mut self, node: &A64Item) {
        walk_a64_item(self, node);
    }
    fn visit_a64_reg(&mut self, node: &A64Reg) {
        walk_a64_reg(self, node);
    }
    fn visit_a_arch64_dialect_keyword(&mut self, node: &AArch64DialectKeyword) {
        walk_a_arch64_dialect_keyword(self, node);
    }
    fn visit_add_keyword(&mut self, node: &AddKeyword) {
        walk_add_keyword(self, node);
    }
    fn visit_asm_keyword(&mut self, node: &AsmKeyword) {
        walk_asm_keyword(self, node);
    }
    fn visit_b_keyword(&mut self, node: &BKeyword) {
        walk_b_keyword(self, node);
    }
    fn visit_jmp_keyword(&mut self, node: &JmpKeyword) {
        walk_jmp_keyword(self, node);
    }
    fn visit_mov_keyword(&mut self, node: &MovKeyword) {
        walk_mov_keyword(self, node);
    }
    fn visit_movz_keyword(&mut self, node: &MovzKeyword) {
        walk_movz_keyword(self, node);
    }
    fn visit_nop_keyword(&mut self, node: &NopKeyword) {
        walk_nop_keyword(self, node);
    }
    fn visit_program(&mut self, node: &Program) {
        walk_program(self, node);
    }
    fn visit_ret_keyword(&mut self, node: &RetKeyword) {
        walk_ret_keyword(self, node);
    }
    fn visit_x64_item(&mut self, node: &X64Item) {
        walk_x64_item(self, node);
    }
    fn visit_x64_reg(&mut self, node: &X64Reg) {
        walk_x64_reg(self, node);
    }
    fn visit_x86_64_dialect_keyword(&mut self, node: &X86_64DialectKeyword) {
        walk_x86_64_dialect_keyword(self, node);
    }
}

pub trait VisitMut {
    fn visit_a64_item_mut(&mut self, node: &mut A64Item) {
        walk_a64_item_mut(self, node);
    }
    fn visit_a64_reg_mut(&mut self, node: &mut A64Reg) {
        walk_a64_reg_mut(self, node);
    }
    fn visit_a_arch64_dialect_keyword_mut(&mut self, node: &mut AArch64DialectKeyword) {
        walk_a_arch64_dialect_keyword_mut(self, node);
    }
    fn visit_add_keyword_mut(&mut self, node: &mut AddKeyword) {
        walk_add_keyword_mut(self, node);
    }
    fn visit_asm_keyword_mut(&mut self, node: &mut AsmKeyword) {
        walk_asm_keyword_mut(self, node);
    }
    fn visit_b_keyword_mut(&mut self, node: &mut BKeyword) {
        walk_b_keyword_mut(self, node);
    }
    fn visit_jmp_keyword_mut(&mut self, node: &mut JmpKeyword) {
        walk_jmp_keyword_mut(self, node);
    }
    fn visit_mov_keyword_mut(&mut self, node: &mut MovKeyword) {
        walk_mov_keyword_mut(self, node);
    }
    fn visit_movz_keyword_mut(&mut self, node: &mut MovzKeyword) {
        walk_movz_keyword_mut(self, node);
    }
    fn visit_nop_keyword_mut(&mut self, node: &mut NopKeyword) {
        walk_nop_keyword_mut(self, node);
    }
    fn visit_program_mut(&mut self, node: &mut Program) {
        walk_program_mut(self, node);
    }
    fn visit_ret_keyword_mut(&mut self, node: &mut RetKeyword) {
        walk_ret_keyword_mut(self, node);
    }
    fn visit_x64_item_mut(&mut self, node: &mut X64Item) {
        walk_x64_item_mut(self, node);
    }
    fn visit_x64_reg_mut(&mut self, node: &mut X64Reg) {
        walk_x64_reg_mut(self, node);
    }
    fn visit_x86_64_dialect_keyword_mut(&mut self, node: &mut X86_64DialectKeyword) {
        walk_x86_64_dialect_keyword_mut(self, node);
    }
}
pub fn walk_a64_item<V: ?Sized + Visit>(v: &mut V, node: &A64Item) {
    match node {
        A64Item::AddImm { op, rd, rn, .. } => {
            v.visit_add_keyword(op);
            v.visit_a64_reg(rd);
            v.visit_a64_reg(rn);
        }
        A64Item::B { op, .. } => {
            v.visit_b_keyword(op);
        }
        A64Item::Label { .. } => {}
        A64Item::Mov { op, rd, rm, .. } => {
            v.visit_mov_keyword(op);
            v.visit_a64_reg(rd);
            v.visit_a64_reg(rm);
        }
        A64Item::Movz { op, rd, .. } => {
            v.visit_movz_keyword(op);
            v.visit_a64_reg(rd);
        }
        A64Item::Nop { op, .. } => {
            v.visit_nop_keyword(op);
        }
        A64Item::Ret { op, .. } => {
            v.visit_ret_keyword(op);
        }
    }
}
pub fn walk_a64_reg<V: ?Sized + Visit>(v: &mut V, node: &A64Reg) {
    match node {
        A64Reg::Sp(..) => {}
        A64Reg::X0(..) => {}
        A64Reg::X1(..) => {}
        A64Reg::X2(..) => {}
        A64Reg::X3(..) => {}
    }
}
pub fn walk_a_arch64_dialect_keyword<V: ?Sized + Visit>(_v: &mut V, _node: &AArch64DialectKeyword) {
}
pub fn walk_add_keyword<V: ?Sized + Visit>(_v: &mut V, _node: &AddKeyword) {}
pub fn walk_asm_keyword<V: ?Sized + Visit>(_v: &mut V, _node: &AsmKeyword) {}
pub fn walk_b_keyword<V: ?Sized + Visit>(_v: &mut V, _node: &BKeyword) {}
pub fn walk_jmp_keyword<V: ?Sized + Visit>(_v: &mut V, _node: &JmpKeyword) {}
pub fn walk_mov_keyword<V: ?Sized + Visit>(_v: &mut V, _node: &MovKeyword) {}
pub fn walk_movz_keyword<V: ?Sized + Visit>(_v: &mut V, _node: &MovzKeyword) {}
pub fn walk_nop_keyword<V: ?Sized + Visit>(_v: &mut V, _node: &NopKeyword) {}
pub fn walk_program<V: ?Sized + Visit>(v: &mut V, node: &Program) {
    match node {
        Program::AArch64 {
            dialect,
            items,
            keyword,
            ..
        } => {
            v.visit_a_arch64_dialect_keyword(dialect);
            for value in items.iter() {
                v.visit_a64_item(value);
            }
            v.visit_asm_keyword(keyword);
        }
        Program::X86_64 {
            dialect,
            items,
            keyword,
            ..
        } => {
            v.visit_x86_64_dialect_keyword(dialect);
            for value in items.iter() {
                v.visit_x64_item(value);
            }
            v.visit_asm_keyword(keyword);
        }
    }
}
pub fn walk_ret_keyword<V: ?Sized + Visit>(_v: &mut V, _node: &RetKeyword) {}
pub fn walk_x64_item<V: ?Sized + Visit>(v: &mut V, node: &X64Item) {
    match node {
        X64Item::AddImm { op, rd, .. } => {
            v.visit_add_keyword(op);
            v.visit_x64_reg(rd);
        }
        X64Item::Jmp { op, .. } => {
            v.visit_jmp_keyword(op);
        }
        X64Item::Label { .. } => {}
        X64Item::MovImm { op, rd, .. } => {
            v.visit_mov_keyword(op);
            v.visit_x64_reg(rd);
        }
        X64Item::MovReg { op, rd, rm, .. } => {
            v.visit_mov_keyword(op);
            v.visit_x64_reg(rd);
            v.visit_x64_reg(rm);
        }
        X64Item::Nop { op, .. } => {
            v.visit_nop_keyword(op);
        }
        X64Item::Ret { op, .. } => {
            v.visit_ret_keyword(op);
        }
    }
}
pub fn walk_x64_reg<V: ?Sized + Visit>(v: &mut V, node: &X64Reg) {
    match node {
        X64Reg::Rax(..) => {}
        X64Reg::Rbp(..) => {}
        X64Reg::Rbx(..) => {}
        X64Reg::Rcx(..) => {}
        X64Reg::Rdx(..) => {}
        X64Reg::Rsp(..) => {}
    }
}
pub fn walk_x86_64_dialect_keyword<V: ?Sized + Visit>(_v: &mut V, _node: &X86_64DialectKeyword) {}
pub fn walk_a64_item_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut A64Item) {
    match node {
        A64Item::AddImm { op, rd, rn, .. } => {
            v.visit_add_keyword_mut(op);
            v.visit_a64_reg_mut(rd);
            v.visit_a64_reg_mut(rn);
        }
        A64Item::B { op, .. } => {
            v.visit_b_keyword_mut(op);
        }
        A64Item::Label { .. } => {}
        A64Item::Mov { op, rd, rm, .. } => {
            v.visit_mov_keyword_mut(op);
            v.visit_a64_reg_mut(rd);
            v.visit_a64_reg_mut(rm);
        }
        A64Item::Movz { op, rd, .. } => {
            v.visit_movz_keyword_mut(op);
            v.visit_a64_reg_mut(rd);
        }
        A64Item::Nop { op, .. } => {
            v.visit_nop_keyword_mut(op);
        }
        A64Item::Ret { op, .. } => {
            v.visit_ret_keyword_mut(op);
        }
    }
}
pub fn walk_a64_reg_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut A64Reg) {
    match node {
        A64Reg::Sp(..) => {}
        A64Reg::X0(..) => {}
        A64Reg::X1(..) => {}
        A64Reg::X2(..) => {}
        A64Reg::X3(..) => {}
    }
}
pub fn walk_a_arch64_dialect_keyword_mut<V: ?Sized + VisitMut>(
    _v: &mut V,

    _node: &mut AArch64DialectKeyword,
) {
}
pub fn walk_add_keyword_mut<V: ?Sized + VisitMut>(_v: &mut V, _node: &mut AddKeyword) {}
pub fn walk_asm_keyword_mut<V: ?Sized + VisitMut>(_v: &mut V, _node: &mut AsmKeyword) {}
pub fn walk_b_keyword_mut<V: ?Sized + VisitMut>(_v: &mut V, _node: &mut BKeyword) {}
pub fn walk_jmp_keyword_mut<V: ?Sized + VisitMut>(_v: &mut V, _node: &mut JmpKeyword) {}
pub fn walk_mov_keyword_mut<V: ?Sized + VisitMut>(_v: &mut V, _node: &mut MovKeyword) {}
pub fn walk_movz_keyword_mut<V: ?Sized + VisitMut>(_v: &mut V, _node: &mut MovzKeyword) {}
pub fn walk_nop_keyword_mut<V: ?Sized + VisitMut>(_v: &mut V, _node: &mut NopKeyword) {}
pub fn walk_program_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut Program) {
    match node {
        Program::AArch64 {
            dialect,
            items,
            keyword,
            ..
        } => {
            v.visit_a_arch64_dialect_keyword_mut(dialect);
            for value in items.iter_mut() {
                v.visit_a64_item_mut(value);
            }
            v.visit_asm_keyword_mut(keyword);
        }
        Program::X86_64 {
            dialect,
            items,
            keyword,
            ..
        } => {
            v.visit_x86_64_dialect_keyword_mut(dialect);
            for value in items.iter_mut() {
                v.visit_x64_item_mut(value);
            }
            v.visit_asm_keyword_mut(keyword);
        }
    }
}
pub fn walk_ret_keyword_mut<V: ?Sized + VisitMut>(_v: &mut V, _node: &mut RetKeyword) {}
pub fn walk_x64_item_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut X64Item) {
    match node {
        X64Item::AddImm { op, rd, .. } => {
            v.visit_add_keyword_mut(op);
            v.visit_x64_reg_mut(rd);
        }
        X64Item::Jmp { op, .. } => {
            v.visit_jmp_keyword_mut(op);
        }
        X64Item::Label { .. } => {}
        X64Item::MovImm { op, rd, .. } => {
            v.visit_mov_keyword_mut(op);
            v.visit_x64_reg_mut(rd);
        }
        X64Item::MovReg { op, rd, rm, .. } => {
            v.visit_mov_keyword_mut(op);
            v.visit_x64_reg_mut(rd);
            v.visit_x64_reg_mut(rm);
        }
        X64Item::Nop { op, .. } => {
            v.visit_nop_keyword_mut(op);
        }
        X64Item::Ret { op, .. } => {
            v.visit_ret_keyword_mut(op);
        }
    }
}
pub fn walk_x64_reg_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut X64Reg) {
    match node {
        X64Reg::Rax(..) => {}
        X64Reg::Rbp(..) => {}
        X64Reg::Rbx(..) => {}
        X64Reg::Rcx(..) => {}
        X64Reg::Rdx(..) => {}
        X64Reg::Rsp(..) => {}
    }
}
pub fn walk_x86_64_dialect_keyword_mut<V: ?Sized + VisitMut>(
    _v: &mut V,

    _node: &mut X86_64DialectKeyword,
) {
}
