// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

pub mod hir;

#[derive(Clone, Copy)]
pub struct ReprSpec {
    pub name: &'static str,

    pub file_ext: &'static str,

    pub validate: fn(&str) -> Result<(), String>,
}
fn validate_hir(source: &str) -> Result<(), String> {
    hir::parse_module_text(source).map(|_| ())
}

pub static REPRS: &[ReprSpec] = &[ReprSpec {
    name: hir::REPR_NAME,
    file_ext: hir::REPR_FILE_EXT,
    validate: validate_hir,
}];
