// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#![allow(dead_code, unused_variables)]
use super::*;
pub fn format_root_text(node: &Program) -> String {
    format_program(node)
}
pub fn format_program_text(node: &Program) -> String {
    format_root_text(node)
}

impl std::fmt::Display for Program {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&format_root_text(self))
    }
}
const INDENT_WIDTH: usize = 4;
struct Writer {

    out: String,

    indent: usize,

    at_line_start: bool,
}

impl Writer {
    fn new() -> Self {
        Self {
            out: String::new(),
            indent: 0,
            at_line_start: false,
        }
    }
    fn text(&mut self, text: &str) {
        for ch in text.chars() {
            if self.at_line_start && ch != '\n' {
                for _ in 0..self.indent {
                    self.out.push(' ');
                }
                self.at_line_start = false;
            }
            self.out.push(ch);
            if ch == '\n' {
                self.at_line_start = true;
            }
        }
    }
    fn with_indent(&mut self, f: impl FnOnce(&mut Self)) {
        self.indent += INDENT_WIDTH;
        f(self);
        self.indent -= INDENT_WIDTH;
    }
    fn finish(self) -> String {
        self.out
    }
}
pub fn format_block(node: &Block) -> String {
    let mut w = Writer::new();
    write_block(&mut w, node);
    w.finish()
}
fn write_block(w: &mut Writer, node: &Block) {
    w.text("block b");
    w.text(&node.id.0.to_string());
    w.text(" params=[");
    for (idx, value) in node.params.iter().enumerate() {
        if idx != 0 {
            w.text(", ");
        }
        w.text(&value.0.to_string());
    }
    w.text("] insts=[");
    for (idx, value) in node.insts.iter().enumerate() {
        if idx != 0 {
            w.text(", ");
        }
        w.text(&value.0.to_string());
    }
    w.text("] term=t");
    w.text(&node.term.0.to_string());
    w.text(" preds=[");
    for (idx, value) in node.preds.iter().enumerate() {
        if idx != 0 {
            w.text(", ");
        }
        w.text(&value.0.to_string());
    }
    w.text("] succs=[");
    for (idx, value) in node.succs.iter().enumerate() {
        if idx != 0 {
            w.text(", ");
        }
        w.text(&value.0.to_string());
    }
    w.text("]");
}
pub fn format_const_ref(node: &ConstRef) -> String {
    let mut w = Writer::new();
    write_const_ref(&mut w, node);
    w.finish()
}
fn write_const_ref(w: &mut Writer, node: &ConstRef) {
    match node {
        ConstRef::Named { name, .. } => {
            w.text("@");
            w.text(&name.text);
        }
        ConstRef::Value { value, .. } => {
            w.text(&value.value.to_string());
        }
    }
}
pub fn format_data_args_line(node: &DataArgsLine) -> String {
    let mut w = Writer::new();
    write_data_args_line(&mut w, node);
    w.finish()
}
fn write_data_args_line(w: &mut Writer, node: &DataArgsLine) {
    w.text("data_args: [");
    for (idx, value) in node.args.iter().enumerate() {
        if idx != 0 {
            w.text(", ");
        }
        w.text(&value.0.to_string());
    }
    w.text("]");
}
pub fn format_data_results_line(node: &DataResultsLine) -> String {
    let mut w = Writer::new();
    write_data_results_line(&mut w, node);
    w.finish()
}
fn write_data_results_line(w: &mut Writer, node: &DataResultsLine) {
    w.text("data_results: [");
    for (idx, value) in node.results.iter().enumerate() {
        if idx != 0 {
            w.text(", ");
        }
        w.text(&value.0.to_string());
    }
    w.text("]");
}
pub fn format_edge(node: &Edge) -> String {
    let mut w = Writer::new();
    write_edge(&mut w, node);
    w.finish()
}
fn write_edge(w: &mut Writer, node: &Edge) {
    w.text("edge e");
    w.text(&node.id.0.to_string());
    w.text(": b");
    w.text(&node.from.0.to_string());
    w.text(" -> b");
    w.text(&node.to.0.to_string());
    w.text(" [");
    for (idx, value) in node.args.iter().enumerate() {
        if idx != 0 {
            w.text(", ");
        }
        write_edge_arg(w, &value);
    }
    w.text("]");
}
pub fn format_edge_arg(node: &EdgeArg) -> String {
    let mut w = Writer::new();
    write_edge_arg(&mut w, node);
    w.finish()
}
fn write_edge_arg(w: &mut Writer, node: &EdgeArg) {
    match node {
        EdgeArg::Identity { vreg, .. } => {
            w.text(&vreg.0.to_string());
        }
        EdgeArg::Mapped { source, target, .. } => {
            w.text(&target.0.to_string());
            w.text("=>");
            w.text(&source.0.to_string());
        }
    }
}
pub fn format_fixed_reg(node: &FixedReg) -> String {
    let mut w = Writer::new();
    write_fixed_reg(&mut w, node);
    w.finish()
}
fn write_fixed_reg(w: &mut Writer, node: &FixedReg) {
    match node {
        FixedReg::AbiArg { index, .. } => {
            w.text("arg");
            w.text(&index.value.to_string());
        }
        FixedReg::AbiRet { index, .. } => {
            w.text("ret");
            w.text(&index.value.to_string());
        }
        FixedReg::HwReg { index, .. } => {
            w.text("hw");
            w.text(&index.value.to_string());
        }
    }
}
pub fn format_function(node: &Function) -> String {
    let mut w = Writer::new();
    write_function(&mut w, node);
    w.finish()
}
fn write_function(w: &mut Writer, node: &Function) {
    w.text("cfg_func @");
    w.text(&node.lambda_id.0.to_string());
    w.text(" f");
    w.text(&node.function_id.0.to_string());
    w.text(" entry=b");
    w.text(&node.entry.0.to_string());
    w.text(" ");
    w.text("{");
    w.text("\n");
    w.with_indent(|w| write_data_args_line(w, &node.data_args));
    w.text("\n");
    w.with_indent(|w| write_data_results_line(w, &node.data_results));
    w.text("\n");
    for (idx, value) in node.blocks.iter().enumerate() {
        if idx != 0 {
            w.text("\n");
        }
        w.with_indent(|w| {
            write_block(w, &value);
        });
    }
    w.text("\n");
    for (idx, value) in node.insts.iter().enumerate() {
        if idx != 0 {
            w.text("\n");
        }
        w.with_indent(|w| {
            write_inst(w, &value);
        });
    }
    w.text("\n");
    for (idx, value) in node.terms.iter().enumerate() {
        if idx != 0 {
            w.text("\n");
        }
        w.with_indent(|w| {
            write_terminator(w, &value);
        });
    }
    w.text("\n");
    for (idx, value) in node.edges.iter().enumerate() {
        if idx != 0 {
            w.text("\n");
        }
        w.with_indent(|w| {
            write_edge(w, &value);
        });
    }
    w.text("\n}");
}
pub fn format_inst(node: &Inst) -> String {
    let mut w = Writer::new();
    write_inst(&mut w, node);
    w.finish()
}
fn write_inst(w: &mut Writer, node: &Inst) {
    w.text("inst i");
    w.text(&node.id.0.to_string());
    w.text(":");
    if let Some(value) = node.defs.as_ref() {
        for (idx, value) in value.iter().enumerate() {
            if idx != 0 {
                w.text(", ");
            }
            write_operand(w, &value);
        }
        w.text(" =");
    }
    write_inst_op(w, &node.op);
    if let Some(value) = node.uses.as_ref() {
        for (idx, value) in value.iter().enumerate() {
            if idx != 0 {
                w.text(", ");
            }
            write_operand(w, &value);
        }
    }
    if let Some(value) = node.clobbers.as_ref() {
        w.text("!");
        write_clobber_kind(w, &value);
    }
}
pub fn format_inst_op(node: &InstOp) -> String {
    let mut w = Writer::new();
    write_inst_op(&mut w, node);
    w.finish()
}
fn write_inst_op(w: &mut Writer, node: &InstOp) {
    match node {
        InstOp::BinOp { op, .. } => {
            w.text(" ");
            write_bin_op_kind(w, &op);
        }
        InstOp::CallEffect { func, .. } => {
            w.text(" call_effect(");
            write_intrinsic_ref(w, &func);
            w.text(")");
        }
        InstOp::CallIntrinsic { func, .. } => {
            w.text(" call_intrinsic(");
            write_intrinsic_ref(w, &func);
            w.text(")");
        }
        InstOp::CallLambda { target, .. } => {
            w.text(" call_lambda(@");
            w.text(&target.0.to_string());
            w.text(")");
        }
        InstOp::CallPure { func, .. } => {
            w.text(" call_pure(");
            write_intrinsic_ref(w, &func);
            w.text(")");
        }
        InstOp::Const { value, .. } => {
            w.text(" const(");
            write_const_ref(w, &value);
            w.text(")");
        }
        InstOp::Copy(_value) => {
            w.text(" copy");
        }
        InstOp::DataAddr { blob_id, .. } => {
            w.text(" data_addr(");
            w.text(&blob_id.0.to_string());
            w.text(")");
        }
        InstOp::ExternAddr { symbol, .. } => {
            w.text(" extern_addr(");
            write_intrinsic_ref(w, &symbol);
            w.text(")");
        }
        InstOp::LoadFromAddr { width, .. } => {
            w.text(" load_addr([");
            write_width(w, &width);
            w.text("])");
        }
        InstOp::ReadFromSlot { slot, .. } => {
            w.text(" read_slot(");
            w.text(&slot.0.to_string());
            w.text(")");
        }
        InstOp::StackAlloc { id, .. } => {
            w.text(" stack_alloc(");
            w.text(&id.0.to_string());
            w.text(")");
        }
        InstOp::StoreToAddr { width, .. } => {
            w.text(" store_addr([");
            write_width(w, &width);
            w.text("])");
        }
        InstOp::UnaryOp { op, .. } => {
            w.text(" ");
            write_unary_op(w, &op);
        }
        InstOp::WriteToSlot { slot, .. } => {
            w.text(" write_slot(");
            w.text(&slot.0.to_string());
            w.text(")");
        }
    }
}
pub fn format_intrinsic_ref(node: &IntrinsicRef) -> String {
    let mut w = Writer::new();
    write_intrinsic_ref(&mut w, node);
    w.finish()
}
fn write_intrinsic_ref(w: &mut Writer, node: &IntrinsicRef) {
    match node {
        IntrinsicRef::Address { value, .. } => {
            w.text(&value.value.to_string());
        }
        IntrinsicRef::Named { name, .. } => {
            w.text("@");
            w.text(&name.text);
        }
    }
}
pub fn format_operand(node: &Operand) -> String {
    let mut w = Writer::new();
    write_operand(&mut w, node);
    w.finish()
}
fn write_operand(w: &mut Writer, node: &Operand) {
    w.text("v");
    w.text(&node.vreg.0.to_string());
    w.text(":");
    write_reg_class(w, &node.class);
    if let Some(value) = node.fixed.as_ref() {
        w.text("/");
        write_fixed_reg(w, &value);
    }
}
pub fn format_program(node: &Program) -> String {
    let mut w = Writer::new();
    write_program(&mut w, node);
    w.finish()
}
fn write_program(w: &mut Writer, node: &Program) {
    w.text("cfg_program vregs=");
    w.text(&node.vreg_count.value.to_string());
    w.text(" slots=");
    w.text(&node.slot_count.value.to_string());
    w.text(" ");
    w.text("{");
    w.text("\n");
    for (idx, value) in node.functions.iter().enumerate() {
        if idx != 0 {
            w.text("\n");
        }
        w.with_indent(|w| {
            write_function(w, &value);
        });
    }
    w.text("\n}");
}
pub fn format_terminator(node: &Terminator) -> String {
    let mut w = Writer::new();
    write_terminator(&mut w, node);
    w.finish()
}
fn write_terminator(w: &mut Writer, node: &Terminator) {
    match node {
        Terminator::Branch { edge, id, .. } => {
            w.text("term t");
            w.text(&id.0.to_string());
            w.text(": branch e");
            w.text(&edge.0.to_string());
        }
        Terminator::BranchIf { cond, fallthrough, id, taken, .. } => {
            w.text("term t");
            w.text(&id.0.to_string());
            w.text(": branch_if ");
            w.text(&cond.0.to_string());
            w.text(" -> e");
            w.text(&taken.0.to_string());
            w.text(", fallthrough e");
            w.text(&fallthrough.0.to_string());
        }
        Terminator::BranchIfZero { cond, fallthrough, id, taken, .. } => {
            w.text("term t");
            w.text(&id.0.to_string());
            w.text(": branch_if_zero ");
            w.text(&cond.0.to_string());
            w.text(" -> e");
            w.text(&taken.0.to_string());
            w.text(", fallthrough e");
            w.text(&fallthrough.0.to_string());
        }
        Terminator::JumpTable { default, id, predicate, targets, .. } => {
            w.text("term t");
            w.text(&id.0.to_string());
            w.text(": jump_table ");
            w.text(&predicate.0.to_string());
            w.text(" [");
            for (idx, value) in targets.iter().enumerate() {
                if idx != 0 {
                    w.text(", ");
                }
                w.text(&value.0.to_string());
            }
            w.text("], default e");
            w.text(&default.0.to_string());
        }
        Terminator::Return { id, .. } => {
            w.text("term t");
            w.text(&id.0.to_string());
            w.text(": return");
        }
    }
}
pub fn format_unary_op(node: &UnaryOp) -> String {
    let mut w = Writer::new();
    write_unary_op(&mut w, node);
    w.finish()
}
fn write_unary_op(w: &mut Writer, node: &UnaryOp) {
    match node {
        UnaryOp::SignExtend { from_width, .. } => {
            w.text("SignExtend ");
            write_width(w, &from_width);
        }
    }
}
pub fn format_bin_op_kind(node: &BinOpKind) -> String {
    let mut w = Writer::new();
    write_bin_op_kind(&mut w, node);
    w.finish()
}
fn write_bin_op_kind(w: &mut Writer, node: &BinOpKind) {
    match node {
        BinOpKind::Add => {
            w.text("Add");
        }
        BinOpKind::And => {
            w.text("And");
        }
        BinOpKind::CmpEq => {
            w.text("CmpEq");
        }
        BinOpKind::CmpGe => {
            w.text("CmpGe");
        }
        BinOpKind::CmpGt => {
            w.text("CmpGt");
        }
        BinOpKind::CmpLe => {
            w.text("CmpLe");
        }
        BinOpKind::CmpLt => {
            w.text("CmpLt");
        }
        BinOpKind::CmpNe => {
            w.text("CmpNe");
        }
        BinOpKind::Mul => {
            w.text("Mul");
        }
        BinOpKind::Or => {
            w.text("Or");
        }
        BinOpKind::Sar => {
            w.text("Sar");
        }
        BinOpKind::Shl => {
            w.text("Shl");
        }
        BinOpKind::Shr => {
            w.text("Shr");
        }
        BinOpKind::Sub => {
            w.text("Sub");
        }
        BinOpKind::Xor => {
            w.text("Xor");
        }
    }
}
pub fn format_clobber_kind(node: &ClobberKind) -> String {
    let mut w = Writer::new();
    write_clobber_kind(&mut w, node);
    w.finish()
}
fn write_clobber_kind(w: &mut Writer, node: &ClobberKind) {
    match node {
        ClobberKind::Both => {
            w.text("Both");
        }
        ClobberKind::Gpr => {
            w.text("Gpr");
        }
        ClobberKind::Simd => {
            w.text("Simd");
        }
    }
}
pub fn format_reg_class(node: &RegClass) -> String {
    let mut w = Writer::new();
    write_reg_class(&mut w, node);
    w.finish()
}
fn write_reg_class(w: &mut Writer, node: &RegClass) {
    match node {
        RegClass::Gpr => {
            w.text("Gpr");
        }
        RegClass::Simd => {
            w.text("Simd");
        }
    }
}
pub fn format_width(node: &Width) -> String {
    let mut w = Writer::new();
    write_width(&mut w, node);
    w.finish()
}
fn write_width(w: &mut Writer, node: &Width) {
    match node {
        Width::W1 => {
            w.text("W1");
        }
        Width::W2 => {
            w.text("W2");
        }
        Width::W4 => {
            w.text("W4");
        }
        Width::W8 => {
            w.text("W8");
        }
    }
}
