// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#![allow(dead_code, unused_variables)]
use super::provenance::HasProvenance;
use super::*;
use crate::HoverEntry;
use kajit_types::Prov;
pub fn hover_entries(source: &str) -> Vec<HoverEntry> {
    let mut graph = Graph::new();
    let Ok(handle) = parse_root_into_graph(&mut graph, source) else {
        return Vec::new();
    };
    hover_entries_in_graph(&graph, handle)
}
pub fn hover_entries_in_graph(graph: &Graph, handle: ProgramHandle) -> Vec<HoverEntry> {
    let Some(root) = graph.root(handle) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    collect_program(graph, root, &mut out);
    out.sort_by_key(|entry| (entry.start, entry.end, entry.priority));
    out.dedup_by(|a, b| a.start == b.start && a.end == b.end && a.markdown == b.markdown);
    out
}
fn emit_hover(prov: &Prov, markdown: &str, priority: u8, out: &mut Vec<HoverEntry>) {
    let Some(span) = prov.span.as_ref() else {
        return;
    };
    if span.end <= span.start {
        return;
    }
    out.push(HoverEntry {
        start: span.start,
        end: span.end,
        markdown: markdown.to_owned(),
        priority,
    });
}
fn collect_block(graph: &Graph, node: &Block, out: &mut Vec<HoverEntry>) {
    let _ = graph;
    if let Some(prov) = node.provenance() {
        emit_hover(
            prov,
            "A live basic block.\n\nTombstoned blocks are an internal rewrite detail and are not part\nof the canonical text form.",
            10,
            out,
        );
    }
}
fn collect_const_ref(graph: &Graph, node: &ConstRef, out: &mut Vec<HoverEntry>) {
    let _ = graph;
    match node {
        ConstRef::Named { name, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "A named constant.", 40, out);
            }
            emit_hover(&name.prov, "A named constant.", 30, out);
        }
        ConstRef::Value { prov, value } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "A raw integer constant.", 40, out);
            }
            emit_hover(&value.prov, "A raw integer constant.", 30, out);
        }
    }
}
fn collect_data_args_line(graph: &Graph, node: &DataArgsLine, out: &mut Vec<HoverEntry>) {
    let _ = graph;
    if let Some(prov) = node.provenance() {
        emit_hover(prov, "The `data_args` header line.", 10, out);
    }
}
fn collect_data_results_line(graph: &Graph, node: &DataResultsLine, out: &mut Vec<HoverEntry>) {
    let _ = graph;
    if let Some(prov) = node.provenance() {
        emit_hover(prov, "The `data_results` header line.", 10, out);
    }
}
fn collect_edge(graph: &Graph, node: &Edge, out: &mut Vec<HoverEntry>) {
    let _ = graph;
    if let Some(prov) = node.provenance() {
        emit_hover(prov, "A control-flow edge between two blocks.", 10, out);
    }
    for value in &node.args {
        collect_edge_arg(graph, value, out);
    }
}
fn collect_edge_arg(graph: &Graph, node: &EdgeArg, out: &mut Vec<HoverEntry>) {
    let _ = graph;
    match node {
        EdgeArg::Identity { prov, vreg } => {
            if let Some(prov) = node.provenance() {
                emit_hover(
                    prov,
                    "Identity mapping: the same vreg flows through unchanged.",
                    40,
                    out,
                );
            }
        }
        EdgeArg::Mapped {
            prov,
            source,
            target,
        } => {
            if let Some(prov) = node.provenance() {
                emit_hover(
                    prov,
                    "Explicit source-to-target mapping for a successor parameter.",
                    40,
                    out,
                );
            }
        }
    }
}
fn collect_fixed_reg(graph: &Graph, node: &FixedReg, out: &mut Vec<HoverEntry>) {
    let _ = graph;
    match node {
        FixedReg::AbiArg { index, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "An ABI argument register.", 40, out);
            }
            emit_hover(&index.prov, "An ABI argument register.", 30, out);
        }
        FixedReg::AbiRet { index, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "An ABI return register.", 40, out);
            }
            emit_hover(&index.prov, "An ABI return register.", 30, out);
        }
        FixedReg::HwReg { index, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "A hardware register encoding.", 40, out);
            }
            emit_hover(&index.prov, "A hardware register encoding.", 30, out);
        }
    }
}
fn collect_function(graph: &Graph, node: &Function, out: &mut Vec<HoverEntry>) {
    let _ = graph;
    if let Some(prov) = node.provenance() {
        emit_hover(
            prov,
            "A lowered lambda/function in canonical CFG-MIR form.",
            10,
            out,
        );
    }
    if let Some(prov) = node.data_args.provenance() {
        emit_hover(
            prov,
            "A lowered lambda/function in canonical CFG-MIR form.\n\nPrinted `data_args` header line for the function.",
            30,
            out,
        );
    }
    if let Some(prov) = node.data_results.provenance() {
        emit_hover(
            prov,
            "A lowered lambda/function in canonical CFG-MIR form.\n\nPrinted `data_results` header line for the function.",
            30,
            out,
        );
    }
    for value in &node.blocks {
        collect_block(graph, value, out);
    }
    collect_data_args_line(graph, &node.data_args, out);
    collect_data_results_line(graph, &node.data_results, out);
    for value in &node.edges {
        collect_edge(graph, value, out);
    }
    for id in &node.insts {
        if let Some(value) = graph.inst(*id) {
            collect_inst(graph, value, out);
        }
    }
    for value in &node.terms {
        collect_terminator(graph, value, out);
    }
}
fn collect_inst(graph: &Graph, node: &Inst, out: &mut Vec<HoverEntry>) {
    let _ = graph;
    if let Some(prov) = node.provenance() {
        emit_hover(
            prov,
            "A single non-terminator instruction in CFG-MIR.",
            10,
            out,
        );
    }
    if let Some(prov) = node.op.provenance() {
        emit_hover(
            prov,
            "A single non-terminator instruction in CFG-MIR.\n\nThe opcode and its payload.",
            30,
            out,
        );
    }
    if let Some(value) = node.defs.as_ref() {
        for value in value {
            collect_operand(graph, value, out);
        }
    }
    collect_inst_op(graph, &node.op, out);
    if let Some(value) = node.uses.as_ref() {
        for value in value {
            collect_operand(graph, value, out);
        }
    }
}
fn collect_inst_op(graph: &Graph, node: &InstOp, out: &mut Vec<HoverEntry>) {
    let _ = graph;
    match node {
        InstOp::BinOp { op, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(
                    prov,
                    "Execute a binary arithmetic or comparison op.",
                    40,
                    out,
                );
            }
        }
        InstOp::CallEffect { func, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Call an effectful intrinsic by reference.", 40, out);
            }
            if let Some(prov) = func.provenance() {
                emit_hover(prov, "Call an effectful intrinsic by reference.", 30, out);
            }
            collect_intrinsic_ref(graph, func, out);
        }
        InstOp::CallIntrinsic { func, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(
                    prov,
                    "Call an external/raw intrinsic by reference.",
                    40,
                    out,
                );
            }
            if let Some(prov) = func.provenance() {
                emit_hover(
                    prov,
                    "Call an external/raw intrinsic by reference.",
                    30,
                    out,
                );
            }
            collect_intrinsic_ref(graph, func, out);
        }
        InstOp::CallLambda { prov, target } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Call another lowered lambda by ID.", 40, out);
            }
        }
        InstOp::CallPure { func, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Call a pure intrinsic by reference.", 40, out);
            }
            if let Some(prov) = func.provenance() {
                emit_hover(prov, "Call a pure intrinsic by reference.", 30, out);
            }
            collect_intrinsic_ref(graph, func, out);
        }
        InstOp::Const { prov, value } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Materialize an immediate constant.", 40, out);
            }
            if let Some(prov) = value.provenance() {
                emit_hover(prov, "Materialize an immediate constant.", 30, out);
            }
            collect_const_ref(graph, value, out);
        }
        InstOp::Copy(value) => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Copy a value between virtual registers.", 40, out);
            }
        }
        InstOp::DataAddr { blob_id, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(
                    prov,
                    "Load the runtime address of an embedded data blob.",
                    40,
                    out,
                );
            }
        }
        InstOp::ExternAddr { prov, symbol } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Load the address of an external symbol.", 40, out);
            }
            if let Some(prov) = symbol.provenance() {
                emit_hover(prov, "Load the address of an external symbol.", 30, out);
            }
            collect_intrinsic_ref(graph, symbol, out);
        }
        InstOp::LoadFromAddr { prov, width } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Load a scalar value from memory.", 40, out);
            }
        }
        InstOp::ReadFromSlot { prov, slot } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Read a value from a stack slot.", 40, out);
            }
        }
        InstOp::StackAlloc { id, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(
                    prov,
                    "Produce the address of an abstract stack allocation.",
                    40,
                    out,
                );
            }
        }
        InstOp::StoreToAddr { prov, width } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Store a scalar value to memory.", 40, out);
            }
        }
        InstOp::UnaryOp { op, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Execute a unary op.", 40, out);
            }
            if let Some(prov) = op.provenance() {
                emit_hover(prov, "Execute a unary op.", 30, out);
            }
            collect_unary_op(graph, op, out);
        }
        InstOp::WriteToSlot { prov, slot } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Write a value to a stack slot.", 40, out);
            }
        }
    }
}
fn collect_intrinsic_ref(graph: &Graph, node: &IntrinsicRef, out: &mut Vec<HoverEntry>) {
    let _ = graph;
    match node {
        IntrinsicRef::Address { prov, value } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "A raw address reference.", 40, out);
            }
            emit_hover(&value.prov, "A raw address reference.", 30, out);
        }
        IntrinsicRef::Named { name, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "A named intrinsic reference.", 40, out);
            }
            emit_hover(&name.prov, "A named intrinsic reference.", 30, out);
        }
    }
}
fn collect_operand(graph: &Graph, node: &Operand, out: &mut Vec<HoverEntry>) {
    let _ = graph;
    if let Some(prov) = node.provenance() {
        emit_hover(prov, "A register operand used by an instruction.", 10, out);
    }
    if let Some(value) = node.fixed.as_ref() {
        collect_fixed_reg(graph, value, out);
    }
}
fn collect_program(graph: &Graph, node: &Program, out: &mut Vec<HoverEntry>) {
    let _ = graph;
    if let Some(prov) = node.provenance() {
        emit_hover(prov, "The root CFG-MIR program.", 10, out);
    }
    emit_hover(
        &node.slot_count.prov,
        "The root CFG-MIR program.\n\nTotal number of stack slots available in this program.",
        30,
        out,
    );
    emit_hover(
        &node.vreg_count.prov,
        "The root CFG-MIR program.\n\nTotal number of vregs available in this program.",
        30,
        out,
    );
    for value in &node.functions {
        collect_function(graph, value, out);
    }
}
fn collect_terminator(graph: &Graph, node: &Terminator, out: &mut Vec<HoverEntry>) {
    let _ = graph;
    match node {
        Terminator::Branch { edge, id, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Unconditional branch to a single edge.", 40, out);
            }
        }
        Terminator::BranchIf {
            cond,
            fallthrough,
            id,
            prov,
            taken,
        } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Branch if the condition is nonzero.", 40, out);
            }
        }
        Terminator::BranchIfZero {
            cond,
            fallthrough,
            id,
            prov,
            taken,
        } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Branch if the condition is zero.", 40, out);
            }
        }
        Terminator::JumpTable {
            default,
            id,
            predicate,
            prov,
            targets,
        } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Jump through a table of edge targets.", 40, out);
            }
        }
        Terminator::Return { id, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Return from the current function.", 40, out);
            }
        }
    }
}
fn collect_unary_op(graph: &Graph, node: &UnaryOp, out: &mut Vec<HoverEntry>) {
    let _ = graph;
    match node {
        UnaryOp::SignExtend { from_width, prov } => {
            if let Some(prov) = node.provenance() {
                emit_hover(prov, "Sign-extend from a source width to 64 bits.", 40, out);
            }
        }
    }
}
