// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#![allow(dead_code, unused_variables)]
use super::provenance::HasProvenance;
use super::*;
use crate::SemanticToken;
use kajit_types::Prov;
pub fn semantic_tokens(source: &str) -> Vec<SemanticToken> {
    let mut graph = Graph::new();
    let Ok(handle) = parse_root_into_graph(&mut graph, source) else {
        return Vec::new();
    };
    semantic_tokens_in_graph(source, &graph, handle)
}
pub fn semantic_tokens_in_graph(
    source: &str,

    graph: &Graph,

    handle: ProgramHandle,
) -> Vec<SemanticToken> {
    let Some(root) = graph.root(handle) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    collect_program(source, root, &mut out);
    out.sort_by_key(|token| (token.start, token.end, token.kind));
    out.dedup_by(|a, b| a.start == b.start && a.end == b.end && a.kind == b.kind);
    out
}
fn emit_prov_token(prov: &Prov, kind: &'static str, out: &mut Vec<SemanticToken>) {
    let Some(span) = prov.span.as_ref() else {
        return;
    };
    if span.end <= span.start {
        return;
    }
    out.push(SemanticToken {
        start: span.start,
        end: span.end,
        kind,
    });
}
fn emit_literal_token(
    source: &str,

    prov: Option<&Prov>,

    text: &str,

    kind: &'static str,

    out: &mut Vec<SemanticToken>,
) {
    let Some(prov) = prov else {
        return;
    };
    let Some(span) = prov.span.as_ref() else {
        return;
    };
    let start = span.start as usize;
    let end = span.end as usize;
    if start > end || end > source.len() {
        return;
    }
    let Some(offset) = source[start..end].find(text) else {
        return;
    };
    out.push(SemanticToken {
        start: (start + offset) as u32,
        end: (start + offset + text.len()) as u32,
        kind,
    });
}
fn collect_block(source: &str, node: &Block, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
    emit_literal_token(source, current_prov, "block", "keyword", out);
}
fn collect_const_ref(source: &str, node: &ConstRef, out: &mut Vec<SemanticToken>) {
    match node {
        ConstRef::Named { name, prov } => {
            let current_prov = node.provenance();
        }
        ConstRef::Value { prov, value } => {
            let current_prov = node.provenance();
            emit_prov_token(&value.prov, "number", out);
        }
    }
}
fn collect_data_args_line(source: &str, node: &DataArgsLine, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
}
fn collect_data_results_line(source: &str, node: &DataResultsLine, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
}
fn collect_edge(source: &str, node: &Edge, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
    emit_literal_token(source, current_prov, "edge", "keyword", out);
    for value in &node.args {
        collect_edge_arg(source, value, out);
    }
}
fn collect_edge_arg(source: &str, node: &EdgeArg, out: &mut Vec<SemanticToken>) {
    match node {
        EdgeArg::Identity { prov, vreg } => {
            let current_prov = node.provenance();
        }
        EdgeArg::Mapped {
            prov,
            source,
            target,
        } => {
            let current_prov = node.provenance();
        }
    }
}
fn collect_fixed_reg(source: &str, node: &FixedReg, out: &mut Vec<SemanticToken>) {
    match node {
        FixedReg::AbiArg { index, prov } => {
            let current_prov = node.provenance();
        }
        FixedReg::AbiRet { index, prov } => {
            let current_prov = node.provenance();
        }
        FixedReg::HwReg { index, prov } => {
            let current_prov = node.provenance();
        }
    }
}
fn collect_function(source: &str, node: &Function, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
    emit_literal_token(source, current_prov, "cfg_func", "keyword", out);
    for value in &node.blocks {
        collect_block(source, value, out);
    }
    collect_data_args_line(source, &node.data_args, out);
    collect_data_results_line(source, &node.data_results, out);
    for value in &node.edges {
        collect_edge(source, value, out);
    }
    for value in &node.terms {
        collect_terminator(source, value, out);
    }
}
fn collect_inst(source: &str, node: &Inst, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
    emit_literal_token(source, current_prov, "inst", "keyword", out);
    if let Some(value) = node.defs.as_ref() {
        for value in value {
            collect_operand(source, value, out);
        }
    }
    collect_inst_op(source, &node.op, out);
    if let Some(value) = node.uses.as_ref() {
        for value in value {
            collect_operand(source, value, out);
        }
    }
}
fn collect_inst_op(source: &str, node: &InstOp, out: &mut Vec<SemanticToken>) {
    match node {
        InstOp::BinOp { op, prov } => {
            let current_prov = node.provenance();
        }
        InstOp::CallEffect { func, prov } => {
            let current_prov = node.provenance();
            collect_intrinsic_ref(source, func, out);
        }
        InstOp::CallIntrinsic { func, prov } => {
            let current_prov = node.provenance();
            collect_intrinsic_ref(source, func, out);
        }
        InstOp::CallLambda { prov, target } => {
            let current_prov = node.provenance();
        }
        InstOp::CallPure { func, prov } => {
            let current_prov = node.provenance();
            collect_intrinsic_ref(source, func, out);
        }
        InstOp::Const { prov, value } => {
            let current_prov = node.provenance();
            if let Some(prov) = value.provenance() {
                emit_prov_token(prov, "number", out);
            }
            collect_const_ref(source, value, out);
        }
        InstOp::Copy(value) => {
            let current_prov = node.provenance();
            emit_literal_token(source, current_prov, "copy", "keyword", out);
        }
        InstOp::DataAddr { blob_id, prov } => {
            let current_prov = node.provenance();
        }
        InstOp::ExternAddr { prov, symbol } => {
            let current_prov = node.provenance();
            collect_intrinsic_ref(source, symbol, out);
        }
        InstOp::LoadFromAddr { prov, width } => {
            let current_prov = node.provenance();
        }
        InstOp::ReadFromSlot { prov, slot } => {
            let current_prov = node.provenance();
        }
        InstOp::StackAlloc { id, prov } => {
            let current_prov = node.provenance();
        }
        InstOp::StoreToAddr { prov, width } => {
            let current_prov = node.provenance();
        }
        InstOp::UnaryOp { op, prov } => {
            let current_prov = node.provenance();
            collect_unary_op(source, op, out);
        }
        InstOp::WriteToSlot { prov, slot } => {
            let current_prov = node.provenance();
        }
    }
}
fn collect_intrinsic_ref(source: &str, node: &IntrinsicRef, out: &mut Vec<SemanticToken>) {
    match node {
        IntrinsicRef::Address { prov, value } => {
            let current_prov = node.provenance();
            emit_prov_token(&value.prov, "number", out);
        }
        IntrinsicRef::Named { name, prov } => {
            let current_prov = node.provenance();
        }
    }
}
fn collect_operand(source: &str, node: &Operand, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
    if let Some(value) = node.fixed.as_ref() {
        collect_fixed_reg(source, value, out);
    }
}
fn collect_program(source: &str, node: &Program, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
    emit_literal_token(source, current_prov, "cfg_program", "keyword", out);
    emit_prov_token(&node.slot_count.prov, "number", out);
    emit_prov_token(&node.vreg_count.prov, "number", out);
    for value in &node.functions {
        collect_function(source, value, out);
    }
}
fn collect_terminator(source: &str, node: &Terminator, out: &mut Vec<SemanticToken>) {
    match node {
        Terminator::Branch { edge, id, prov } => {
            let current_prov = node.provenance();
            emit_literal_token(source, current_prov, "term", "keyword", out);
            emit_literal_token(source, current_prov, "branch", "keyword", out);
        }
        Terminator::BranchIf {
            cond,
            fallthrough,
            id,
            prov,
            taken,
        } => {
            let current_prov = node.provenance();
            emit_literal_token(source, current_prov, "term", "keyword", out);
            emit_literal_token(source, current_prov, "branch_if", "keyword", out);
        }
        Terminator::BranchIfZero {
            cond,
            fallthrough,
            id,
            prov,
            taken,
        } => {
            let current_prov = node.provenance();
            emit_literal_token(source, current_prov, "term", "keyword", out);
            emit_literal_token(source, current_prov, "branch_if_zero", "keyword", out);
        }
        Terminator::JumpTable {
            default,
            id,
            predicate,
            prov,
            targets,
        } => {
            let current_prov = node.provenance();
            emit_literal_token(source, current_prov, "term", "keyword", out);
            emit_literal_token(source, current_prov, "jump_table", "keyword", out);
        }
        Terminator::Return { id, prov } => {
            let current_prov = node.provenance();
            emit_literal_token(source, current_prov, "term", "keyword", out);
            emit_literal_token(source, current_prov, "return", "keyword", out);
        }
    }
}
fn collect_unary_op(source: &str, node: &UnaryOp, out: &mut Vec<SemanticToken>) {
    match node {
        UnaryOp::SignExtend { from_width, prov } => {
            let current_prov = node.provenance();
        }
    }
}
