[package]
name = "kajit-ir"
version = "0.1.0"
edition = "2024"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
kajit-reprs = { path = "../kajit-reprs" }
kajit-types = { path = "../kajit-types" }
thiserror = "2.0.18"

[dev-dependencies]
kajit-ir-text = { path = "../kajit-ir-text" }
