// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TokenSpec {
    pub name: &'static str,

    pub kind: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RuleSpec {
    pub name: &'static str,

    pub kind: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TypeUseSpec {
    pub name: &'static str,

    pub kind: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NodeSpec {
    pub name: &'static str,

    pub kind: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PrintSpec {
    pub name: &'static str,

    pub template: &'static str,
}

pub const REPR_NAME: &str = "MIR";

pub const REPR_FILE_EXT: &str = ".k-mir";

pub const REPR_ROOT: &str = "Program";

pub const REPR_PURPOSE: &str = "Canonical executable CFG IR";

pub const REPR_ROUND_TRIP: &str = "canonical-print";

pub const REPR_PROVENANCE: &str = "required";

pub static REPR_CANONICAL_IDENTITIES: &[&str] = &[
    "function-id",
    "block-id",
    "inst-id",
    "term-id",
    "edge-id",
    "vreg-id",
];

pub static TOKENS: &[TokenSpec] = &[
    TokenSpec {
        name: "ident",
        kind: "[A-Za-z_][A-Za-z0-9_]*",
    },
    TokenSpec {
        name: "int",
        kind: "[0-9]+",
    },
];

pub static RULES: &[RuleSpec] = &[
    RuleSpec {
        name: "BinOpKind",
        kind: "choice",
    },
    RuleSpec {
        name: "BlobId",
        kind: "token",
    },
    RuleSpec {
        name: "Block",
        kind: "seq",
    },
    RuleSpec {
        name: "BlockId",
        kind: "token",
    },
    RuleSpec {
        name: "ClobberKind",
        kind: "choice",
    },
    RuleSpec {
        name: "ConstRef",
        kind: "choice",
    },
    RuleSpec {
        name: "DataArgsLine",
        kind: "seq",
    },
    RuleSpec {
        name: "DataResultsLine",
        kind: "seq",
    },
    RuleSpec {
        name: "Edge",
        kind: "seq",
    },
    RuleSpec {
        name: "EdgeArg",
        kind: "choice",
    },
    RuleSpec {
        name: "EdgeId",
        kind: "token",
    },
    RuleSpec {
        name: "FixedReg",
        kind: "choice",
    },
    RuleSpec {
        name: "Function",
        kind: "seq",
    },
    RuleSpec {
        name: "FunctionId",
        kind: "token",
    },
    RuleSpec {
        name: "Inst",
        kind: "seq",
    },
    RuleSpec {
        name: "InstId",
        kind: "token",
    },
    RuleSpec {
        name: "InstOp",
        kind: "choice",
    },
    RuleSpec {
        name: "IntrinsicRef",
        kind: "choice",
    },
    RuleSpec {
        name: "LambdaId",
        kind: "token",
    },
    RuleSpec {
        name: "Nat",
        kind: "token",
    },
    RuleSpec {
        name: "Operand",
        kind: "seq",
    },
    RuleSpec {
        name: "Program",
        kind: "seq",
    },
    RuleSpec {
        name: "RegClass",
        kind: "choice",
    },
    RuleSpec {
        name: "SlotId",
        kind: "token",
    },
    RuleSpec {
        name: "StackAllocId",
        kind: "token",
    },
    RuleSpec {
        name: "Symbol",
        kind: "token",
    },
    RuleSpec {
        name: "TermId",
        kind: "token",
    },
    RuleSpec {
        name: "Terminator",
        kind: "choice",
    },
    RuleSpec {
        name: "UnaryOp",
        kind: "choice",
    },
    RuleSpec {
        name: "VReg",
        kind: "token",
    },
    RuleSpec {
        name: "Width",
        kind: "choice",
    },
];

pub static COMMON_TYPES: &[TypeUseSpec] = &[
    TypeUseSpec {
        name: "docs",
        kind: "DocBlock",
    },
    TypeUseSpec {
        name: "provenance",
        kind: "Prov",
    },
];

pub static NODES: &[NodeSpec] = &[
    NodeSpec {
        name: "Block",
        kind: "entity",
    },
    NodeSpec {
        name: "ConstRef",
        kind: "enum",
    },
    NodeSpec {
        name: "DataArgsLine",
        kind: "slot",
    },
    NodeSpec {
        name: "DataResultsLine",
        kind: "slot",
    },
    NodeSpec {
        name: "Edge",
        kind: "entity",
    },
    NodeSpec {
        name: "EdgeArg",
        kind: "enum",
    },
    NodeSpec {
        name: "FixedReg",
        kind: "enum",
    },
    NodeSpec {
        name: "Function",
        kind: "entity",
    },
    NodeSpec {
        name: "Inst",
        kind: "entity",
    },
    NodeSpec {
        name: "InstOp",
        kind: "enum",
    },
    NodeSpec {
        name: "IntrinsicRef",
        kind: "enum",
    },
    NodeSpec {
        name: "Operand",
        kind: "slot",
    },
    NodeSpec {
        name: "Program",
        kind: "node",
    },
    NodeSpec {
        name: "Terminator",
        kind: "enum",
    },
    NodeSpec {
        name: "UnaryOp",
        kind: "enum",
    },
];

pub static CANONICAL_PRINT: &[PrintSpec] = &[
    PrintSpec {
        name: "Block",
        template: "block b{id} params=[{params:, }] insts=[{insts:, }] term=t{term} preds=[{preds:, }] succs=[{succs:, }]",
    },
    PrintSpec {
        name: "ConstRef.Named",
        template: "@{name}",
    },
    PrintSpec {
        name: "ConstRef.Value",
        template: "{value}",
    },
    PrintSpec {
        name: "DataArgsLine",
        template: "data_args: [{args:, }]",
    },
    PrintSpec {
        name: "DataResultsLine",
        template: "data_results: [{results:, }]",
    },
    PrintSpec {
        name: "Edge",
        template: "edge e{id}: b{from} -> b{to} [{args:, }]",
    },
    PrintSpec {
        name: "EdgeArg.Identity",
        template: "{vreg}",
    },
    PrintSpec {
        name: "EdgeArg.Mapped",
        template: "{target}=>{source}",
    },
    PrintSpec {
        name: "FixedReg.AbiArg",
        template: "arg{index}",
    },
    PrintSpec {
        name: "FixedReg.AbiRet",
        template: "ret{index}",
    },
    PrintSpec {
        name: "FixedReg.HwReg",
        template: "hw{index}",
    },
    PrintSpec {
        name: "Function",
        template: "cfg_func @{lambda_id} f{function_id} entry=b{entry} {\n{data_args}\n{data_results}\n{blocks}\n{insts}\n{terms}\n{edges}\n}",
    },
    PrintSpec {
        name: "Inst",
        template: "inst i{id}:{defs? : {defs:, } =}{op}{uses? : {uses:, }}{clobbers? : !{clobbers}}",
    },
    PrintSpec {
        name: "InstOp.BinOp",
        template: " {op}",
    },
    PrintSpec {
        name: "InstOp.CallEffect",
        template: " call_effect({func})",
    },
    PrintSpec {
        name: "InstOp.CallIntrinsic",
        template: " call_intrinsic({func})",
    },
    PrintSpec {
        name: "InstOp.CallLambda",
        template: " call_lambda(@{target})",
    },
    PrintSpec {
        name: "InstOp.CallPure",
        template: " call_pure({func})",
    },
    PrintSpec {
        name: "InstOp.Const",
        template: " const({value})",
    },
    PrintSpec {
        name: "InstOp.Copy",
        template: " copy",
    },
    PrintSpec {
        name: "InstOp.DataAddr",
        template: " data_addr({blob_id})",
    },
    PrintSpec {
        name: "InstOp.ExternAddr",
        template: " extern_addr({symbol})",
    },
    PrintSpec {
        name: "InstOp.LoadFromAddr",
        template: " load_addr([{width}])",
    },
    PrintSpec {
        name: "InstOp.ReadFromSlot",
        template: " read_slot({slot})",
    },
    PrintSpec {
        name: "InstOp.StackAlloc",
        template: " stack_alloc({id})",
    },
    PrintSpec {
        name: "InstOp.StoreToAddr",
        template: " store_addr([{width}])",
    },
    PrintSpec {
        name: "InstOp.UnaryOp",
        template: " {op}",
    },
    PrintSpec {
        name: "InstOp.WriteToSlot",
        template: " write_slot({slot})",
    },
    PrintSpec {
        name: "IntrinsicRef.Address",
        template: "{value}",
    },
    PrintSpec {
        name: "IntrinsicRef.Named",
        template: "@{name}",
    },
    PrintSpec {
        name: "Operand",
        template: "v{vreg}:{class}{fixed? : /{fixed}}",
    },
    PrintSpec {
        name: "Program",
        template: "cfg_program vregs={vreg_count} slots={slot_count} {\n{functions}\n}",
    },
    PrintSpec {
        name: "Terminator.Branch",
        template: "branch e{edge}",
    },
    PrintSpec {
        name: "Terminator.BranchIf",
        template: "branch_if {cond} -> e{taken}, fallthrough e{fallthrough}",
    },
    PrintSpec {
        name: "Terminator.BranchIfZero",
        template: "branch_if_zero {cond} -> e{taken}, fallthrough e{fallthrough}",
    },
    PrintSpec {
        name: "Terminator.JumpTable",
        template: "jump_table {predicate} [{targets:, }], default e{default}",
    },
    PrintSpec {
        name: "Terminator.Return",
        template: "return",
    },
    PrintSpec {
        name: "UnaryOp.SignExtend",
        template: "SignExtend {from_width: {from_width}}",
    },
];
