// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

use super::*;
use chumsky::prelude::*;
type ParseExtra<'src> = extra::Err<Rich<'src, char>>;
fn ws<'src>() -> impl Parser<'src, &'src str, (), ParseExtra<'src>> + Clone {
    any()
        .filter(|c: &char| c.is_whitespace())
        .repeated()
        .ignored()
}
fn line_ws<'src>() -> impl Parser<'src, &'src str, (), ParseExtra<'src>> + Clone {
    one_of(" \t").repeated().ignored()
}
fn doc_comment_line<'src>() -> impl Parser<'src, &'src str, String, ParseExtra<'src>> + Clone {
    line_ws()
        .ignore_then(just("///"))
        .ignore_then(just(' ').or_not())
        .ignore_then(
            any()
                .filter(|c: &char| *c != '\n')
                .repeated()
                .collect::<String>(),
        )
        .then_ignore(just('\n').or_not())
}
fn doc_block<'src>() -> impl Parser<'src, &'src str, Option<DocBlock>, ParseExtra<'src>> + Clone {
    doc_comment_line()
        .repeated()
        .collect::<Vec<_>>()
        .map(|lines| {
            if lines.is_empty() {
                None
            } else {
                Some(DocBlock(lines))
            }
        })
}
fn token_ident<'src>() -> impl Parser<'src, &'src str, String, ParseExtra<'src>> + Clone {
    text::ident::<_, ParseExtra<'src>>().map(str::to_owned)
}
fn token_int<'src>() -> impl Parser<'src, &'src str, String, ParseExtra<'src>> + Clone {
    text::int::<_, ParseExtra<'src>>(10).map(str::to_owned)
}
fn prov_from_span(span: chumsky::span::SimpleSpan<usize>, file_id: Option<u32>) -> Prov {
    Prov {
        file_id,
        span: Some(Span {
            start: span.start as u32,
            end: span.end as u32,
        }),
    }
}
pub fn parse_root_text_rich(
    source: &str,

    file_id: Option<u32>,
) -> Result<Program, Vec<Rich<'_, char>>> {
    let bin_op_kind_parser = choice((
        just("add").to(BinOpKind::Add),
        just("sub").to(BinOpKind::Sub),
        just("mul").to(BinOpKind::Mul),
        just("and").to(BinOpKind::And),
        just("or").to(BinOpKind::Or),
        just("sar").to(BinOpKind::Sar),
        just("shr").to(BinOpKind::Shr),
        just("shl").to(BinOpKind::Shl),
        just("xor").to(BinOpKind::Xor),
        just("cmpeq").to(BinOpKind::CmpEq),
        just("cmpne").to(BinOpKind::CmpNe),
        just("cmplt").to(BinOpKind::CmpLt),
        just("cmple").to(BinOpKind::CmpLe),
        just("cmpgt").to(BinOpKind::CmpGt),
        just("cmpge").to(BinOpKind::CmpGe),
    ))
    .then_ignore(ws())
    .boxed();
    let blob_id_parser = token_int()
        .try_map(move |text, span| match text.parse::<u32>() {
            Ok(value) => Ok(BlobId(value)),
            Err(err) => Err(Rich::custom(
                span,
                format!("invalid id literal {text:?}: {err}"),
            )),
        })
        .then_ignore(ws());
    let block_id_parser = token_int()
        .try_map(move |text, span| match text.parse::<u32>() {
            Ok(value) => Ok(BlockId(value)),
            Err(err) => Err(Rich::custom(
                span,
                format!("invalid id literal {text:?}: {err}"),
            )),
        })
        .then_ignore(ws());
    let edge_id_parser = token_int()
        .try_map(move |text, span| match text.parse::<u32>() {
            Ok(value) => Ok(EdgeId(value)),
            Err(err) => Err(Rich::custom(
                span,
                format!("invalid id literal {text:?}: {err}"),
            )),
        })
        .then_ignore(ws());
    let inst_id_parser = token_int()
        .try_map(move |text, span| match text.parse::<u32>() {
            Ok(value) => Ok(InstId(value)),
            Err(err) => Err(Rich::custom(
                span,
                format!("invalid id literal {text:?}: {err}"),
            )),
        })
        .then_ignore(ws());
    let term_id_parser = token_int()
        .try_map(move |text, span| match text.parse::<u32>() {
            Ok(value) => Ok(TermId(value)),
            Err(err) => Err(Rich::custom(
                span,
                format!("invalid id literal {text:?}: {err}"),
            )),
        })
        .then_ignore(ws());
    let v_reg_parser = token_int()
        .try_map(move |text, span| match text.parse::<u32>() {
            Ok(value) => Ok(VReg(value)),
            Err(err) => Err(Rich::custom(
                span,
                format!("invalid id literal {text:?}: {err}"),
            )),
        })
        .then_ignore(ws());
    let block_parser = ((((((((((((((((((((((doc_block())
        .then_ignore(just("block").padded()))
    .then_ignore(just("b").padded()))
    .then(block_id_parser.clone()))
    .then_ignore(just("params=").padded()))
    .then_ignore(just("[").padded()))
    .then(
        (v_reg_parser.clone())
            .separated_by(just(",").padded())
            .allow_trailing()
            .collect::<Vec<_>>(),
    ))
    .then_ignore(just("]").padded()))
    .then_ignore(just("insts=").padded()))
    .then_ignore(just("[").padded()))
    .then(
        (inst_id_parser.clone())
            .separated_by(just(",").padded())
            .allow_trailing()
            .collect::<Vec<_>>(),
    ))
    .then_ignore(just("]").padded()))
    .then_ignore(just("term=t").padded()))
    .then(term_id_parser.clone()))
    .then_ignore(just("preds=").padded()))
    .then_ignore(just("[").padded()))
    .then(
        (edge_id_parser.clone())
            .separated_by(just(",").padded())
            .allow_trailing()
            .collect::<Vec<_>>(),
    ))
    .then_ignore(just("]").padded()))
    .then_ignore(just("succs=").padded()))
    .then_ignore(just("[").padded()))
    .then(
        (edge_id_parser.clone())
            .separated_by(just(",").padded())
            .allow_trailing()
            .collect::<Vec<_>>(),
    ))
    .then_ignore(just("]").padded()))
    .map_with(
        move |((((((docs, id), params), insts), term), preds), succs), e| Block {
            docs: docs,
            id: id,
            insts: insts,
            params: params,
            preds: preds,
            prov: prov_from_span(e.span(), file_id),
            succs: succs,
            term: term,
        },
    )
    .boxed();
    let clobber_kind_parser = choice((
        just("gpr").to(ClobberKind::Gpr),
        just("simd").to(ClobberKind::Simd),
        just("both").to(ClobberKind::Both),
    ))
    .then_ignore(ws())
    .boxed();
    let nat_parser = token_int()
        .try_map(move |text, span| match text.parse::<u64>() {
            Ok(value) => Ok(Nat {
                prov: prov_from_span(span, file_id),
                value,
            }),
            Err(err) => Err(Rich::custom(
                span,
                format!("invalid integer literal {text:?}: {err}"),
            )),
        })
        .then_ignore(ws());
    let symbol_parser = token_ident()
        .map_with(move |text, e| Symbol {
            prov: prov_from_span(e.span(), file_id),
            text,
        })
        .then_ignore(ws());
    let const_ref_parser = choice((
        ((just("@").padded()).ignore_then(symbol_parser.clone())).map_with(move |name, e| {
            ConstRef::Named {
                name: name,
                prov: prov_from_span(e.span(), file_id),
            }
        }),
        (nat_parser.clone()).map_with(move |value, e| ConstRef::Value {
            prov: prov_from_span(e.span(), file_id),
            value: value,
        }),
    ))
    .boxed();
    let data_args_line_parser = (((((doc_block()).then_ignore(just("data_args:").padded()))
        .then_ignore(just("[").padded()))
    .then(
        (v_reg_parser.clone())
            .separated_by(just(",").padded())
            .allow_trailing()
            .collect::<Vec<_>>(),
    ))
    .then_ignore(just("]").padded()))
    .map_with(move |(docs, args), e| DataArgsLine {
        args: args,
        docs: docs,
        prov: prov_from_span(e.span(), file_id),
    })
    .boxed();
    let data_results_line_parser = (((((doc_block())
        .then_ignore(just("data_results:").padded()))
    .then_ignore(just("[").padded()))
    .then(
        (v_reg_parser.clone())
            .separated_by(just(",").padded())
            .allow_trailing()
            .collect::<Vec<_>>(),
    ))
    .then_ignore(just("]").padded()))
    .map_with(move |(docs, results), e| DataResultsLine {
        docs: docs,
        prov: prov_from_span(e.span(), file_id),
        results: results,
    })
    .boxed();
    let edge_arg_parser = choice((
        (v_reg_parser.clone()).map_with(move |vreg, e| EdgeArg::Identity {
            prov: prov_from_span(e.span(), file_id),
            vreg: vreg,
        }),
        (((v_reg_parser.clone()).then_ignore(just("=>").padded())).then(v_reg_parser.clone()))
            .map_with(move |(target, source), e| EdgeArg::Mapped {
                prov: prov_from_span(e.span(), file_id),
                source: source,
                target: target,
            }),
    ))
    .boxed();
    let edge_parser = (((((((((((((doc_block()).then_ignore(just("edge").padded()))
        .then_ignore(just("e").padded()))
    .then(edge_id_parser.clone()))
    .then_ignore(just(":").padded()))
    .then_ignore(just("b").padded()))
    .then(block_id_parser.clone()))
    .then_ignore(just("->").padded()))
    .then_ignore(just("b").padded()))
    .then(block_id_parser.clone()))
    .then_ignore(just("[").padded()))
    .then(
        (edge_arg_parser.clone())
            .separated_by(just(",").padded())
            .allow_trailing()
            .collect::<Vec<_>>(),
    ))
    .then_ignore(just("]").padded()))
    .map_with(move |((((docs, id), from), to), args), e| Edge {
        args: args,
        docs: docs,
        from: from,
        id: id,
        prov: prov_from_span(e.span(), file_id),
        to: to,
    })
    .boxed();
    let fixed_reg_parser = choice((
        ((just("arg").padded()).ignore_then(nat_parser.clone())).map_with(move |index, e| {
            FixedReg::AbiArg {
                index: index,
                prov: prov_from_span(e.span(), file_id),
            }
        }),
        ((just("ret").padded()).ignore_then(nat_parser.clone())).map_with(move |index, e| {
            FixedReg::AbiRet {
                index: index,
                prov: prov_from_span(e.span(), file_id),
            }
        }),
        ((just("hw").padded()).ignore_then(nat_parser.clone())).map_with(move |index, e| {
            FixedReg::HwReg {
                index: index,
                prov: prov_from_span(e.span(), file_id),
            }
        }),
    ))
    .boxed();
    let intrinsic_ref_parser = choice((
        ((just("@").padded()).ignore_then(symbol_parser.clone())).map_with(move |name, e| {
            IntrinsicRef::Named {
                name: name,
                prov: prov_from_span(e.span(), file_id),
            }
        }),
        (nat_parser.clone()).map_with(move |value, e| IntrinsicRef::Address {
            prov: prov_from_span(e.span(), file_id),
            value: value,
        }),
    ))
    .boxed();
    let lambda_id_parser = token_int()
        .try_map(move |text, span| match text.parse::<u32>() {
            Ok(value) => Ok(LambdaId(value)),
            Err(err) => Err(Rich::custom(
                span,
                format!("invalid id literal {text:?}: {err}"),
            )),
        })
        .then_ignore(ws());
    let slot_id_parser = token_int()
        .try_map(move |text, span| match text.parse::<u32>() {
            Ok(value) => Ok(SlotId(value)),
            Err(err) => Err(Rich::custom(
                span,
                format!("invalid id literal {text:?}: {err}"),
            )),
        })
        .then_ignore(ws());
    let stack_alloc_id_parser = token_int()
        .try_map(move |text, span| match text.parse::<u32>() {
            Ok(value) => Ok(StackAllocId(value)),
            Err(err) => Err(Rich::custom(
                span,
                format!("invalid id literal {text:?}: {err}"),
            )),
        })
        .then_ignore(ws());
    let width_parser = choice((
        just("w1").to(Width::W1),
        just("w2").to(Width::W2),
        just("w4").to(Width::W4),
        just("w8").to(Width::W8),
    ))
    .then_ignore(ws())
    .boxed();
    let unary_op_parser = ((((just("SignExtend").padded()).ignore_then(
        (just("{").padded())
            .ignore_then((just("from_width:").padded()).ignore_then(width_parser.clone())),
    ))
    .then_ignore(just("}").padded()))
    .map_with(move |from_width, e| UnaryOp::SignExtend {
        from_width: from_width,
        prov: prov_from_span(e.span(), file_id),
    }))
    .boxed();
    let inst_op_parser = choice((
        (((just("const(").padded()).ignore_then((const_ref_parser.clone()).map(Box::new)))
            .then_ignore(just(")").padded()))
        .map_with(move |value, e| InstOp::Const {
            prov: prov_from_span(e.span(), file_id),
            value: value,
        }),
        (((just("data_addr(").padded()).ignore_then(blob_id_parser.clone()))
            .then_ignore(just(")").padded()))
        .map_with(move |blob_id, e| InstOp::DataAddr {
            blob_id: blob_id,
            prov: prov_from_span(e.span(), file_id),
        }),
        (((just("extern_addr(").padded())
            .ignore_then((intrinsic_ref_parser.clone()).map(Box::new)))
        .then_ignore(just(")").padded()))
        .map_with(move |symbol, e| InstOp::ExternAddr {
            prov: prov_from_span(e.span(), file_id),
            symbol: symbol,
        }),
        (bin_op_kind_parser.clone()).map_with(move |op, e| InstOp::BinOp {
            op: op,
            prov: prov_from_span(e.span(), file_id),
        }),
        ((unary_op_parser.clone()).map(Box::new)).map_with(move |op, e| InstOp::UnaryOp {
            op: op,
            prov: prov_from_span(e.span(), file_id),
        }),
        (just("copy").to(()))
            .map_with(move |(), e| {
                InstOp::Copy(Copy {
                    prov: prov_from_span(e.span(), file_id),
                })
            })
            .then_ignore(ws()),
        (((just("stack_alloc(").padded()).ignore_then(stack_alloc_id_parser.clone()))
            .then_ignore(just(")").padded()))
        .map_with(move |id, e| InstOp::StackAlloc {
            id: id,
            prov: prov_from_span(e.span(), file_id),
        }),
        (((just("store_addr([").padded()).ignore_then(width_parser.clone()))
            .then_ignore(just("])").padded()))
        .map_with(move |width, e| InstOp::StoreToAddr {
            prov: prov_from_span(e.span(), file_id),
            width: width,
        }),
        (((just("load_addr([").padded()).ignore_then(width_parser.clone()))
            .then_ignore(just("])").padded()))
        .map_with(move |width, e| InstOp::LoadFromAddr {
            prov: prov_from_span(e.span(), file_id),
            width: width,
        }),
        (((just("write_slot(").padded()).ignore_then(slot_id_parser.clone()))
            .then_ignore(just(")").padded()))
        .map_with(move |slot, e| InstOp::WriteToSlot {
            prov: prov_from_span(e.span(), file_id),
            slot: slot,
        }),
        (((just("read_slot(").padded()).ignore_then(slot_id_parser.clone()))
            .then_ignore(just(")").padded()))
        .map_with(move |slot, e| InstOp::ReadFromSlot {
            prov: prov_from_span(e.span(), file_id),
            slot: slot,
        }),
        (((just("call_intrinsic(").padded())
            .ignore_then((intrinsic_ref_parser.clone()).map(Box::new)))
        .then_ignore(just(")").padded()))
        .map_with(move |func, e| InstOp::CallIntrinsic {
            func: func,
            prov: prov_from_span(e.span(), file_id),
        }),
        (((just("call_pure(").padded()).ignore_then((intrinsic_ref_parser.clone()).map(Box::new)))
            .then_ignore(just(")").padded()))
        .map_with(move |func, e| InstOp::CallPure {
            func: func,
            prov: prov_from_span(e.span(), file_id),
        }),
        (((just("call_effect(").padded())
            .ignore_then((intrinsic_ref_parser.clone()).map(Box::new)))
        .then_ignore(just(")").padded()))
        .map_with(move |func, e| InstOp::CallEffect {
            func: func,
            prov: prov_from_span(e.span(), file_id),
        }),
        (((just("call_lambda(@").padded()).ignore_then(lambda_id_parser.clone()))
            .then_ignore(just(")").padded()))
        .map_with(move |target, e| InstOp::CallLambda {
            prov: prov_from_span(e.span(), file_id),
            target: target,
        }),
    ))
    .boxed();
    let reg_class_parser = choice((
        just("gpr").to(RegClass::Gpr),
        just("simd").to(RegClass::Simd),
    ))
    .then_ignore(ws())
    .boxed();
    let operand_parser = (((((just("v").padded()).ignore_then(v_reg_parser.clone()))
        .then_ignore(just(":").padded()))
    .then(reg_class_parser.clone()))
    .then(((just("/").padded()).ignore_then((fixed_reg_parser.clone()).map(Box::new))).or_not()))
    .map_with(move |((vreg, class), fixed), e| Operand {
        class: class,
        fixed: fixed,
        prov: prov_from_span(e.span(), file_id),
        vreg: vreg,
    })
    .boxed();
    let inst_parser = (((((((((doc_block()).then_ignore(just("inst").padded()))
        .then_ignore(just("i").padded()))
    .then(inst_id_parser.clone()))
    .then_ignore(just(":").padded()))
    .then(
        (((operand_parser.clone())
            .separated_by(just(",").padded())
            .allow_trailing()
            .collect::<Vec<_>>())
        .then_ignore(just("=").padded()))
        .or_not(),
    ))
    .then((inst_op_parser.clone()).map(Box::new)))
    .then(
        ((operand_parser.clone())
            .separated_by(just(",").padded())
            .allow_trailing()
            .collect::<Vec<_>>())
        .or_not(),
    ))
    .then(((just("!").padded()).ignore_then(clobber_kind_parser.clone())).or_not()))
    .map_with(
        move |(((((docs, id), defs), op), uses), clobbers), e| Inst {
            clobbers: clobbers,
            defs: defs,
            docs: docs,
            id: id,
            op: op,
            prov: prov_from_span(e.span(), file_id),
            uses: uses,
        },
    )
    .boxed();
    let terminator_parser = choice((
        (just("return").to(()))
            .map_with(move |(), e| {
                Terminator::Return(Return {
                    prov: prov_from_span(e.span(), file_id),
                })
            })
            .then_ignore(ws()),
        ((just("branch").padded())
            .ignore_then((just("e").padded()).ignore_then(edge_id_parser.clone())))
        .map_with(move |edge, e| Terminator::Branch {
            edge: edge,
            prov: prov_from_span(e.span(), file_id),
        }),
        (((((((((just("branch_if").padded()).ignore_then(v_reg_parser.clone()))
            .then_ignore(just("->").padded()))
        .then_ignore(just("e").padded()))
        .then(edge_id_parser.clone()))
        .then_ignore(just(",").padded()))
        .then_ignore(just("fallthrough").padded()))
        .then_ignore(just("e").padded()))
        .then(edge_id_parser.clone()))
        .map_with(
            move |((cond, taken), fallthrough), e| Terminator::BranchIf {
                cond: cond,
                fallthrough: fallthrough,
                prov: prov_from_span(e.span(), file_id),
                taken: taken,
            },
        ),
        (((((((((just("branch_if_zero").padded()).ignore_then(v_reg_parser.clone()))
            .then_ignore(just("->").padded()))
        .then_ignore(just("e").padded()))
        .then(edge_id_parser.clone()))
        .then_ignore(just(",").padded()))
        .then_ignore(just("fallthrough").padded()))
        .then_ignore(just("e").padded()))
        .then(edge_id_parser.clone()))
        .map_with(
            move |((cond, taken), fallthrough), e| Terminator::BranchIfZero {
                cond: cond,
                fallthrough: fallthrough,
                prov: prov_from_span(e.span(), file_id),
                taken: taken,
            },
        ),
        (((((((((just("jump_table").padded()).ignore_then(v_reg_parser.clone()))
            .then_ignore(just("[").padded()))
        .then(
            (edge_id_parser.clone())
                .separated_by(just(",").padded())
                .allow_trailing()
                .collect::<Vec<_>>(),
        ))
        .then_ignore(just("]").padded()))
        .then_ignore(just(",").padded()))
        .then_ignore(just("default").padded()))
        .then_ignore(just("e").padded()))
        .then(edge_id_parser.clone()))
        .map_with(
            move |((predicate, targets), default), e| Terminator::JumpTable {
                default: default,
                predicate: predicate,
                prov: prov_from_span(e.span(), file_id),
                targets: targets,
            },
        ),
    ))
    .boxed();
    let function_parser = (((((((((((((((((doc_block())
        .then_ignore(just("cfg_func").padded()))
    .then_ignore(just("@").padded()))
    .then(
        token_int()
            .try_map(move |text, span| match text.parse::<u32>() {
                Ok(value) => Ok(LambdaId(value)),
                Err(err) => Err(Rich::custom(
                    span,
                    format!("invalid id literal {text:?}: {err}"),
                )),
            })
            .then_ignore(ws()),
    ))
    .then_ignore(just("f").padded()))
    .then(
        token_int()
            .try_map(move |text, span| match text.parse::<u32>() {
                Ok(value) => Ok(FunctionId(value)),
                Err(err) => Err(Rich::custom(
                    span,
                    format!("invalid id literal {text:?}: {err}"),
                )),
            })
            .then_ignore(ws()),
    ))
    .then_ignore(just("entry=").padded()))
    .then_ignore(just("b").padded()))
    .then(
        token_int()
            .try_map(move |text, span| match text.parse::<u32>() {
                Ok(value) => Ok(BlockId(value)),
                Err(err) => Err(Rich::custom(
                    span,
                    format!("invalid id literal {text:?}: {err}"),
                )),
            })
            .then_ignore(ws()),
    ))
    .then_ignore(just("{").padded()))
    .then((data_args_line_parser.clone()).map(Box::new)))
    .then((data_results_line_parser.clone()).map(Box::new)))
    .then((block_parser.clone()).repeated().collect::<Vec<_>>()))
    .then((inst_parser.clone()).repeated().collect::<Vec<_>>()))
    .then((terminator_parser.clone()).repeated().collect::<Vec<_>>()))
    .then((edge_parser.clone()).repeated().collect::<Vec<_>>()))
    .then_ignore(just("}").padded()))
    .map_with(
        move |(
            (
                (
                    (
                        (((((docs, lambda_id), function_id), entry), data_args), data_results),
                        blocks,
                    ),
                    insts,
                ),
                terms,
            ),
            edges,
        ),
              e| Function {
            blocks: blocks,
            data_args: data_args,
            data_results: data_results,
            docs: docs,
            edges: edges,
            entry: entry,
            function_id: function_id,
            insts: insts,
            lambda_id: lambda_id,
            prov: prov_from_span(e.span(), file_id),
            terms: terms,
        },
    )
    .boxed();
    let function_id_parser = token_int()
        .try_map(move |text, span| match text.parse::<u32>() {
            Ok(value) => Ok(FunctionId(value)),
            Err(err) => Err(Rich::custom(
                span,
                format!("invalid id literal {text:?}: {err}"),
            )),
        })
        .then_ignore(ws());
    let program_parser = (((((((((doc_block()).then_ignore(just("cfg_program").padded()))
        .then_ignore(just("vregs=").padded()))
    .then(
        token_int()
            .try_map(move |text, span| match text.parse::<u64>() {
                Ok(value) => Ok(Nat {
                    prov: prov_from_span(span, file_id),
                    value,
                }),
                Err(err) => Err(Rich::custom(
                    span,
                    format!("invalid integer literal {text:?}: {err}"),
                )),
            })
            .then_ignore(ws()),
    ))
    .then_ignore(just("slots=").padded()))
    .then(
        token_int()
            .try_map(move |text, span| match text.parse::<u64>() {
                Ok(value) => Ok(Nat {
                    prov: prov_from_span(span, file_id),
                    value,
                }),
                Err(err) => Err(Rich::custom(
                    span,
                    format!("invalid integer literal {text:?}: {err}"),
                )),
            })
            .then_ignore(ws()),
    ))
    .then_ignore(just("{").padded()))
    .then((function_parser.clone()).repeated().collect::<Vec<_>>()))
    .then_ignore(just("}").padded()))
    .map_with(
        move |(((docs, vreg_count), slot_count), functions), e| Program {
            docs: docs,
            functions: functions,
            prov: prov_from_span(e.span(), file_id),
            slot_count: slot_count,
            vreg_count: vreg_count,
        },
    )
    .boxed();
    program_parser
        .then_ignore(end())
        .parse(source)
        .into_result()
}
pub fn parse_root_text_with_file_id(source: &str, file_id: Option<u32>) -> Result<Program, String> {
    parse_root_text_rich(source, file_id).map_err(|errs| crate::format_rich_errors(source, errs))
}
pub fn parse_root_text(source: &str) -> Result<Program, String> {
    parse_root_text_with_file_id(source, None)
}
pub fn parse_program_text_rich(
    source: &str,

    file_id: Option<u32>,
) -> Result<Program, Vec<Rich<'_, char>>> {
    parse_root_text_rich(source, file_id)
}
pub fn parse_program_text_with_file_id(
    source: &str,

    file_id: Option<u32>,
) -> Result<Program, String> {
    parse_root_text_with_file_id(source, file_id)
}
pub fn parse_program_text(source: &str) -> Result<Program, String> {
    parse_root_text(source)
}
