// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

use super::*;
use crate::schema_poc::ResolutionSet;
pub fn resolve(_source: &str) -> Result<ResolutionSet, String> {
    Ok(ResolutionSet::default())
}
