// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#![allow(unused_variables)]
use super::*;

pub trait Visit {
    fn visit_block(&mut self, node: &Block) {
        walk_block(self, node);
    }
    fn visit_const_ref(&mut self, node: &ConstRef) {
        walk_const_ref(self, node);
    }
    fn visit_data_args_line(&mut self, node: &DataArgsLine) {
        walk_data_args_line(self, node);
    }
    fn visit_data_results_line(&mut self, node: &DataResultsLine) {
        walk_data_results_line(self, node);
    }
    fn visit_edge(&mut self, node: &Edge) {
        walk_edge(self, node);
    }
    fn visit_edge_arg(&mut self, node: &EdgeArg) {
        walk_edge_arg(self, node);
    }
    fn visit_fixed_reg(&mut self, node: &FixedReg) {
        walk_fixed_reg(self, node);
    }
    fn visit_function(&mut self, node: &Function) {
        walk_function(self, node);
    }
    fn visit_inst(&mut self, node: &Inst) {
        walk_inst(self, node);
    }
    fn visit_inst_op(&mut self, node: &InstOp) {
        walk_inst_op(self, node);
    }
    fn visit_intrinsic_ref(&mut self, node: &IntrinsicRef) {
        walk_intrinsic_ref(self, node);
    }
    fn visit_operand(&mut self, node: &Operand) {
        walk_operand(self, node);
    }
    fn visit_program(&mut self, node: &Program) {
        walk_program(self, node);
    }
    fn visit_terminator(&mut self, node: &Terminator) {
        walk_terminator(self, node);
    }
    fn visit_unary_op(&mut self, node: &UnaryOp) {
        walk_unary_op(self, node);
    }
}

pub trait VisitMut {
    fn visit_block_mut(&mut self, node: &mut Block) {
        walk_block_mut(self, node);
    }
    fn visit_const_ref_mut(&mut self, node: &mut ConstRef) {
        walk_const_ref_mut(self, node);
    }
    fn visit_data_args_line_mut(&mut self, node: &mut DataArgsLine) {
        walk_data_args_line_mut(self, node);
    }
    fn visit_data_results_line_mut(&mut self, node: &mut DataResultsLine) {
        walk_data_results_line_mut(self, node);
    }
    fn visit_edge_mut(&mut self, node: &mut Edge) {
        walk_edge_mut(self, node);
    }
    fn visit_edge_arg_mut(&mut self, node: &mut EdgeArg) {
        walk_edge_arg_mut(self, node);
    }
    fn visit_fixed_reg_mut(&mut self, node: &mut FixedReg) {
        walk_fixed_reg_mut(self, node);
    }
    fn visit_function_mut(&mut self, node: &mut Function) {
        walk_function_mut(self, node);
    }
    fn visit_inst_mut(&mut self, node: &mut Inst) {
        walk_inst_mut(self, node);
    }
    fn visit_inst_op_mut(&mut self, node: &mut InstOp) {
        walk_inst_op_mut(self, node);
    }
    fn visit_intrinsic_ref_mut(&mut self, node: &mut IntrinsicRef) {
        walk_intrinsic_ref_mut(self, node);
    }
    fn visit_operand_mut(&mut self, node: &mut Operand) {
        walk_operand_mut(self, node);
    }
    fn visit_program_mut(&mut self, node: &mut Program) {
        walk_program_mut(self, node);
    }
    fn visit_terminator_mut(&mut self, node: &mut Terminator) {
        walk_terminator_mut(self, node);
    }
    fn visit_unary_op_mut(&mut self, node: &mut UnaryOp) {
        walk_unary_op_mut(self, node);
    }
}
pub fn walk_block<V: ?Sized + Visit>(_v: &mut V, _node: &Block) {}
pub fn walk_const_ref<V: ?Sized + Visit>(v: &mut V, node: &ConstRef) {
    match node {
        ConstRef::Named { .. } => {}
        ConstRef::Value { .. } => {}
    }
}
pub fn walk_data_args_line<V: ?Sized + Visit>(_v: &mut V, _node: &DataArgsLine) {}
pub fn walk_data_results_line<V: ?Sized + Visit>(_v: &mut V, _node: &DataResultsLine) {}
pub fn walk_edge<V: ?Sized + Visit>(v: &mut V, node: &Edge) {
    for value in node.args.iter() {
        v.visit_edge_arg(value);
    }
}
pub fn walk_edge_arg<V: ?Sized + Visit>(v: &mut V, node: &EdgeArg) {
    match node {
        EdgeArg::Identity { .. } => {}
        EdgeArg::Mapped { .. } => {}
    }
}
pub fn walk_fixed_reg<V: ?Sized + Visit>(v: &mut V, node: &FixedReg) {
    match node {
        FixedReg::AbiArg { .. } => {}
        FixedReg::AbiRet { .. } => {}
        FixedReg::HwReg { .. } => {}
    }
}
pub fn walk_function<V: ?Sized + Visit>(v: &mut V, node: &Function) {
    for value in node.blocks.iter() {
        v.visit_block(value);
    }
    v.visit_data_args_line(&node.data_args);
    v.visit_data_results_line(&node.data_results);
    for value in node.edges.iter() {
        v.visit_edge(value);
    }
    for value in node.insts.iter() {
        v.visit_inst(value);
    }
    for value in node.terms.iter() {
        v.visit_terminator(value);
    }
}
pub fn walk_inst<V: ?Sized + Visit>(v: &mut V, node: &Inst) {
    if let Some(value) = &node.defs {
        for value in value.iter() {
            v.visit_operand(value);
        }
    }
    v.visit_inst_op(&node.op);
    if let Some(value) = &node.uses {
        for value in value.iter() {
            v.visit_operand(value);
        }
    }
}
pub fn walk_inst_op<V: ?Sized + Visit>(v: &mut V, node: &InstOp) {
    match node {
        InstOp::BinOp { .. } => {}
        InstOp::CallEffect { func, .. } => {
            v.visit_intrinsic_ref(func);
        }
        InstOp::CallIntrinsic { func, .. } => {
            v.visit_intrinsic_ref(func);
        }
        InstOp::CallLambda { .. } => {}
        InstOp::CallPure { func, .. } => {
            v.visit_intrinsic_ref(func);
        }
        InstOp::Const { value, .. } => {
            v.visit_const_ref(value);
        }
        InstOp::Copy(..) => {}
        InstOp::DataAddr { .. } => {}
        InstOp::ExternAddr { symbol, .. } => {
            v.visit_intrinsic_ref(symbol);
        }
        InstOp::LoadFromAddr { .. } => {}
        InstOp::ReadFromSlot { .. } => {}
        InstOp::StackAlloc { .. } => {}
        InstOp::StoreToAddr { .. } => {}
        InstOp::UnaryOp { op, .. } => {
            v.visit_unary_op(op);
        }
        InstOp::WriteToSlot { .. } => {}
    }
}
pub fn walk_intrinsic_ref<V: ?Sized + Visit>(v: &mut V, node: &IntrinsicRef) {
    match node {
        IntrinsicRef::Address { .. } => {}
        IntrinsicRef::Named { .. } => {}
    }
}
pub fn walk_operand<V: ?Sized + Visit>(v: &mut V, node: &Operand) {
    if let Some(value) = &node.fixed {
        v.visit_fixed_reg(value);
    }
}
pub fn walk_program<V: ?Sized + Visit>(v: &mut V, node: &Program) {
    for value in node.functions.iter() {
        v.visit_function(value);
    }
}
pub fn walk_terminator<V: ?Sized + Visit>(v: &mut V, node: &Terminator) {
    match node {
        Terminator::Branch { .. } => {}
        Terminator::BranchIf { .. } => {}
        Terminator::BranchIfZero { .. } => {}
        Terminator::JumpTable { .. } => {}
        Terminator::Return { .. } => {}
    }
}
pub fn walk_unary_op<V: ?Sized + Visit>(v: &mut V, node: &UnaryOp) {
    match node {
        UnaryOp::SignExtend { .. } => {}
    }
}
pub fn walk_block_mut<V: ?Sized + VisitMut>(_v: &mut V, _node: &mut Block) {}
pub fn walk_const_ref_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut ConstRef) {
    match node {
        ConstRef::Named { .. } => {}
        ConstRef::Value { .. } => {}
    }
}
pub fn walk_data_args_line_mut<V: ?Sized + VisitMut>(_v: &mut V, _node: &mut DataArgsLine) {}
pub fn walk_data_results_line_mut<V: ?Sized + VisitMut>(_v: &mut V, _node: &mut DataResultsLine) {}
pub fn walk_edge_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut Edge) {
    for value in node.args.iter_mut() {
        v.visit_edge_arg_mut(value);
    }
}
pub fn walk_edge_arg_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut EdgeArg) {
    match node {
        EdgeArg::Identity { .. } => {}
        EdgeArg::Mapped { .. } => {}
    }
}
pub fn walk_fixed_reg_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut FixedReg) {
    match node {
        FixedReg::AbiArg { .. } => {}
        FixedReg::AbiRet { .. } => {}
        FixedReg::HwReg { .. } => {}
    }
}
pub fn walk_function_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut Function) {
    for value in node.blocks.iter_mut() {
        v.visit_block_mut(value);
    }
    v.visit_data_args_line_mut(&mut node.data_args);
    v.visit_data_results_line_mut(&mut node.data_results);
    for value in node.edges.iter_mut() {
        v.visit_edge_mut(value);
    }
    for value in node.insts.iter_mut() {
        v.visit_inst_mut(value);
    }
    for value in node.terms.iter_mut() {
        v.visit_terminator_mut(value);
    }
}
pub fn walk_inst_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut Inst) {
    if let Some(value) = &mut node.defs {
        for value in value.iter_mut() {
            v.visit_operand_mut(value);
        }
    }
    v.visit_inst_op_mut(&mut node.op);
    if let Some(value) = &mut node.uses {
        for value in value.iter_mut() {
            v.visit_operand_mut(value);
        }
    }
}
pub fn walk_inst_op_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut InstOp) {
    match node {
        InstOp::BinOp { .. } => {}
        InstOp::CallEffect { func, .. } => {
            v.visit_intrinsic_ref_mut(func);
        }
        InstOp::CallIntrinsic { func, .. } => {
            v.visit_intrinsic_ref_mut(func);
        }
        InstOp::CallLambda { .. } => {}
        InstOp::CallPure { func, .. } => {
            v.visit_intrinsic_ref_mut(func);
        }
        InstOp::Const { value, .. } => {
            v.visit_const_ref_mut(value);
        }
        InstOp::Copy(..) => {}
        InstOp::DataAddr { .. } => {}
        InstOp::ExternAddr { symbol, .. } => {
            v.visit_intrinsic_ref_mut(symbol);
        }
        InstOp::LoadFromAddr { .. } => {}
        InstOp::ReadFromSlot { .. } => {}
        InstOp::StackAlloc { .. } => {}
        InstOp::StoreToAddr { .. } => {}
        InstOp::UnaryOp { op, .. } => {
            v.visit_unary_op_mut(op);
        }
        InstOp::WriteToSlot { .. } => {}
    }
}
pub fn walk_intrinsic_ref_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut IntrinsicRef) {
    match node {
        IntrinsicRef::Address { .. } => {}
        IntrinsicRef::Named { .. } => {}
    }
}
pub fn walk_operand_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut Operand) {
    if let Some(value) = &mut node.fixed {
        v.visit_fixed_reg_mut(value);
    }
}
pub fn walk_program_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut Program) {
    for value in node.functions.iter_mut() {
        v.visit_function_mut(value);
    }
}
pub fn walk_terminator_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut Terminator) {
    match node {
        Terminator::Branch { .. } => {}
        Terminator::BranchIf { .. } => {}
        Terminator::BranchIfZero { .. } => {}
        Terminator::JumpTable { .. } => {}
        Terminator::Return { .. } => {}
    }
}
pub fn walk_unary_op_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut UnaryOp) {
    match node {
        UnaryOp::SignExtend { .. } => {}
    }
}
