// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

pub trait HasProvenance {
    fn provenance(&self) -> Option<&Prov>;
}
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct BinaryOp;
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct DocBlock(pub Vec<String>);
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct GenericParam;
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Literal(pub String);
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct LocalKind;
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Span {
    pub start: u32,
    pub end: u32,
}
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Prov {
    pub file_id: Option<u32>,
    pub span: Option<Span>,
}
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Symbol(pub String);
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Type(pub String);
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct TypeDefKind;
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Block {
    pub prov: Prov,
    pub statements: Vec<Stmt>,
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Expr {
    Binary {
        lhs: Box<Expr>,
        op: BinaryOp,
        prov: Prov,
        rhs: Box<Expr>,
    },
    Call {
        args: Vec<Expr>,
        callee: Symbol,
        prov: Prov,
    },
    Field {
        base: Box<Expr>,
        field: Symbol,
        prov: Prov,
    },
    Literal {
        prov: Prov,
        value: Literal,
    },
    Local {
        name: Symbol,
        prov: Prov,
    },
}
impl HasProvenance for Expr {
    fn provenance(&self) -> Option<&Prov> {
        match self {
            Self::Binary { prov, .. } => Some(prov),
            Self::Call { prov, .. } => Some(prov),
            Self::Field { prov, .. } => Some(prov),
            Self::Literal { prov, .. } => Some(prov),
            Self::Local { prov, .. } => Some(prov),
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Function {
    pub body: Box<Block>,
    pub docs: Option<DocBlock>,
    pub locals: Vec<Local>,
    pub name: Symbol,
    pub params: Vec<Param>,
    pub prov: Prov,
    pub return_type: Type,
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Local {
    pub kind: LocalKind,
    pub name: Symbol,
    pub prov: Prov,
    pub ty: Type,
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Module {
    pub docs: Option<DocBlock>,
    pub functions: Vec<Function>,
    pub type_defs: Vec<TypeDef>,
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Param {
    pub name: Symbol,
    pub prov: Prov,
    pub ty: Type,
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Place {
    Field {
        base: Box<Place>,
        field: Symbol,
        prov: Prov,
    },
    Local {
        name: Symbol,
        prov: Prov,
    },
}
impl HasProvenance for Place {
    fn provenance(&self) -> Option<&Prov> {
        match self {
            Self::Field { prov, .. } => Some(prov),
            Self::Local { prov, .. } => Some(prov),
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Stmt {
    Assign {
        place: Box<Place>,
        prov: Prov,
        value: Box<Expr>,
    },
    Expr {
        prov: Prov,
        value: Box<Expr>,
    },
    If {
        condition: Box<Expr>,
        r#else: Option<Box<Block>>,
        prov: Prov,
        then: Box<Block>,
    },
    Init {
        place: Box<Place>,
        prov: Prov,
        value: Box<Expr>,
    },
    Return {
        prov: Prov,
        value: Option<Box<Expr>>,
    },
}
impl HasProvenance for Stmt {
    fn provenance(&self) -> Option<&Prov> {
        match self {
            Self::Assign { prov, .. } => Some(prov),
            Self::Expr { prov, .. } => Some(prov),
            Self::If { prov, .. } => Some(prov),
            Self::Init { prov, .. } => Some(prov),
            Self::Return { prov, .. } => Some(prov),
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TypeDef {
    pub docs: Option<DocBlock>,
    pub kind: TypeDefKind,
    pub name: Symbol,
    pub params: Vec<GenericParam>,
    pub prov: Prov,
}
impl HasProvenance for Block {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}
impl HasProvenance for Function {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}
impl HasProvenance for Local {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}
impl HasProvenance for Param {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}
impl HasProvenance for TypeDef {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}
