// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

use super::*;
pub fn format_module_text(node: &Module) -> String {
    format_module(node)
}

impl std::fmt::Display for Module {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&format_module(self))
    }
}
pub fn format_block(node: &Block) -> String {
    let mut out = String::new();
    out.push_str("{");
    out.push_str("\n");
    out.push_str(
        &(node
            .statements
            .iter()
            .map(|value| format_stmt(&value))
            .collect::<Vec<_>>()
            .join("\n")),
    );
    out.push_str("\n}");
    out
}
pub fn format_expr(node: &Expr) -> String {
    match node {
        other @ Expr::Binary { .. } => format!("{:?}", other),
        Expr::Call { args, callee, .. } => {
            let mut out = String::new();
            out.push_str("call ");
            out.push_str(&(callee.0.clone()));
            out.push_str("(");
            out.push_str(
                &(args
                    .iter()
                    .map(|value| format_expr(&value))
                    .collect::<Vec<_>>()
                    .join(", ")),
            );
            out.push_str(")");
            out
        }
        other @ Expr::Field { .. } => format!("{:?}", other),
        Expr::Literal { value, .. } => {
            let mut out = String::new();
            out.push_str(&(value.0.clone()));
            out
        }
        Expr::Local { name, .. } => {
            let mut out = String::new();
            out.push_str(&(name.0.clone()));
            out
        }
    }
}
pub fn format_function(node: &Function) -> String {
    let mut out = String::new();
    out.push_str("fn ");
    out.push_str(&(node.name.0.clone()));
    out.push_str("(");
    out.push_str(
        &(node
            .params
            .iter()
            .map(|value| format_param(&value))
            .collect::<Vec<_>>()
            .join(", ")),
    );
    out.push_str(") -> ");
    out.push_str(&(node.return_type.0.clone()));
    out.push_str(" ");
    out.push_str(&(format_block(&node.body)));
    out
}
pub fn format_local(node: &Local) -> String {
    format!("{:?}", node)
}
pub fn format_module(node: &Module) -> String {
    let mut out = String::new();
    out.push_str("module ");
    out.push_str("{");
    out.push_str("\n");
    out.push_str(
        &(node
            .functions
            .iter()
            .map(|value| format_function(&value))
            .collect::<Vec<_>>()
            .join("\n")),
    );
    out.push_str("\n}");
    out
}
pub fn format_param(node: &Param) -> String {
    let mut out = String::new();
    out.push_str(&(node.name.0.clone()));
    out.push_str(": ");
    out.push_str(&(node.ty.0.clone()));
    out
}
pub fn format_place(node: &Place) -> String {
    match node {
        other @ Place::Field { .. } => format!("{:?}", other),
        other @ Place::Local { .. } => format!("{:?}", other),
    }
}
pub fn format_stmt(node: &Stmt) -> String {
    match node {
        other @ Stmt::Assign { .. } => format!("{:?}", other),
        Stmt::Expr { value, .. } => {
            let mut out = String::new();
            out.push_str(&(format_expr(&value)));
            out
        }
        other @ Stmt::If { .. } => format!("{:?}", other),
        other @ Stmt::Init { .. } => format!("{:?}", other),
        Stmt::Return { value, .. } => {
            let mut out = String::new();
            out.push_str("return");
            if let Some(value) = value.as_ref() {
                out.push_str(&(format_expr(&value)));
            }
            out
        }
    }
}
pub fn format_type_def(node: &TypeDef) -> String {
    format!("{:?}", node)
}
