// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TokenSpec {
    pub name: &'static str,

    pub kind: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RuleSpec {
    pub name: &'static str,

    pub kind: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TypeUseSpec {
    pub name: &'static str,

    pub kind: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FieldSpec {
    pub owner: &'static str,

    pub field: &'static str,

    pub kind: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NodeSpec {
    pub name: &'static str,

    pub kind: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PrintSpec {
    pub name: &'static str,

    pub template: &'static str,
}

pub const REPR_NAME: &str = "HIR";

pub const REPR_FILE_EXT: &str = ".k-hir";

pub const REPR_ROOT: &str = "Module";

pub const REPR_PURPOSE: &str = "Human-semantic structured IR";

pub const REPR_ROUND_TRIP: &str = "canonical-print";

pub const REPR_PROVENANCE: &str = "required";

pub static REPR_CANONICAL_IDENTITIES: &[&str] =
    &["symbol", "local-name", "type-name", "function-name"];

pub static TOKENS: &[TokenSpec] = &[
    TokenSpec {
        name: "ident",
        kind: "[A-Za-z_][A-Za-z0-9_]*",
    },
    TokenSpec {
        name: "int",
        kind: "[0-9]+",
    },
    TokenSpec {
        name: "symbol",
        kind: "@[A-Za-z_][A-Za-z0-9_.]*",
    },
];

pub static RULES: &[RuleSpec] = &[
    RuleSpec {
        name: "Block",
        kind: "seq",
    },
    RuleSpec {
        name: "Expr",
        kind: "choice",
    },
    RuleSpec {
        name: "Function",
        kind: "seq",
    },
    RuleSpec {
        name: "Module",
        kind: "seq",
    },
    RuleSpec {
        name: "Param",
        kind: "seq",
    },
    RuleSpec {
        name: "Stmt",
        kind: "choice",
    },
];

pub static COMMON_TYPES: &[TypeUseSpec] = &[
    TypeUseSpec {
        name: "docs",
        kind: "DocBlock",
    },
    TypeUseSpec {
        name: "provenance",
        kind: "Prov",
    },
    TypeUseSpec {
        name: "symbol",
        kind: "Symbol",
    },
];

pub static SUPPORT_FIELDS: &[FieldSpec] = &[];

pub static NODES: &[NodeSpec] = &[
    NodeSpec {
        name: "Block",
        kind: "node",
    },
    NodeSpec {
        name: "Expr",
        kind: "enum",
    },
    NodeSpec {
        name: "Function",
        kind: "node",
    },
    NodeSpec {
        name: "Local",
        kind: "node",
    },
    NodeSpec {
        name: "Module",
        kind: "node",
    },
    NodeSpec {
        name: "Param",
        kind: "node",
    },
    NodeSpec {
        name: "Place",
        kind: "enum",
    },
    NodeSpec {
        name: "Stmt",
        kind: "enum",
    },
    NodeSpec {
        name: "TypeDef",
        kind: "node",
    },
];

pub static NODE_FIELDS: &[FieldSpec] = &[
    FieldSpec {
        owner: "Block",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Block",
        field: "statements",
        kind: "seq<Stmt>",
    },
    FieldSpec {
        owner: "Expr.Binary",
        field: "lhs",
        kind: "Expr",
    },
    FieldSpec {
        owner: "Expr.Binary",
        field: "op",
        kind: "BinaryOp",
    },
    FieldSpec {
        owner: "Expr.Binary",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Expr.Binary",
        field: "rhs",
        kind: "Expr",
    },
    FieldSpec {
        owner: "Expr.Call",
        field: "args",
        kind: "seq<Expr>",
    },
    FieldSpec {
        owner: "Expr.Call",
        field: "callee",
        kind: "Symbol",
    },
    FieldSpec {
        owner: "Expr.Call",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Expr.Field",
        field: "base",
        kind: "Expr",
    },
    FieldSpec {
        owner: "Expr.Field",
        field: "field",
        kind: "Symbol",
    },
    FieldSpec {
        owner: "Expr.Field",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Expr.Literal",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Expr.Literal",
        field: "value",
        kind: "Literal",
    },
    FieldSpec {
        owner: "Expr.Local",
        field: "name",
        kind: "Symbol",
    },
    FieldSpec {
        owner: "Expr.Local",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Function",
        field: "body",
        kind: "Block",
    },
    FieldSpec {
        owner: "Function",
        field: "docs",
        kind: "optional<DocBlock>",
    },
    FieldSpec {
        owner: "Function",
        field: "locals",
        kind: "seq<Local>",
    },
    FieldSpec {
        owner: "Function",
        field: "name",
        kind: "Symbol",
    },
    FieldSpec {
        owner: "Function",
        field: "params",
        kind: "seq<Param>",
    },
    FieldSpec {
        owner: "Function",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Function",
        field: "return_type",
        kind: "Type",
    },
    FieldSpec {
        owner: "Local",
        field: "kind",
        kind: "LocalKind",
    },
    FieldSpec {
        owner: "Local",
        field: "name",
        kind: "Symbol",
    },
    FieldSpec {
        owner: "Local",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Local",
        field: "ty",
        kind: "Type",
    },
    FieldSpec {
        owner: "Module",
        field: "docs",
        kind: "optional<DocBlock>",
    },
    FieldSpec {
        owner: "Module",
        field: "functions",
        kind: "seq<Function>",
    },
    FieldSpec {
        owner: "Module",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Module",
        field: "type_defs",
        kind: "seq<TypeDef>",
    },
    FieldSpec {
        owner: "Param",
        field: "name",
        kind: "Symbol",
    },
    FieldSpec {
        owner: "Param",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Param",
        field: "ty",
        kind: "Type",
    },
    FieldSpec {
        owner: "Place.Field",
        field: "base",
        kind: "Place",
    },
    FieldSpec {
        owner: "Place.Field",
        field: "field",
        kind: "Symbol",
    },
    FieldSpec {
        owner: "Place.Field",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Place.Local",
        field: "name",
        kind: "Symbol",
    },
    FieldSpec {
        owner: "Place.Local",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Stmt.Assign",
        field: "place",
        kind: "Place",
    },
    FieldSpec {
        owner: "Stmt.Assign",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Stmt.Assign",
        field: "value",
        kind: "Expr",
    },
    FieldSpec {
        owner: "Stmt.Expr",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Stmt.Expr",
        field: "value",
        kind: "Expr",
    },
    FieldSpec {
        owner: "Stmt.If",
        field: "condition",
        kind: "Expr",
    },
    FieldSpec {
        owner: "Stmt.If",
        field: "else",
        kind: "optional<Block>",
    },
    FieldSpec {
        owner: "Stmt.If",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Stmt.If",
        field: "then",
        kind: "Block",
    },
    FieldSpec {
        owner: "Stmt.Init",
        field: "place",
        kind: "Place",
    },
    FieldSpec {
        owner: "Stmt.Init",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Stmt.Init",
        field: "value",
        kind: "Expr",
    },
    FieldSpec {
        owner: "Stmt.Return",
        field: "prov",
        kind: "Prov",
    },
    FieldSpec {
        owner: "Stmt.Return",
        field: "value",
        kind: "optional<Expr>",
    },
    FieldSpec {
        owner: "TypeDef",
        field: "docs",
        kind: "optional<DocBlock>",
    },
    FieldSpec {
        owner: "TypeDef",
        field: "kind",
        kind: "TypeDefKind",
    },
    FieldSpec {
        owner: "TypeDef",
        field: "name",
        kind: "Symbol",
    },
    FieldSpec {
        owner: "TypeDef",
        field: "params",
        kind: "seq<GenericParam>",
    },
    FieldSpec {
        owner: "TypeDef",
        field: "prov",
        kind: "Prov",
    },
];

pub static CANONICAL_PRINT: &[PrintSpec] = &[
    PrintSpec {
        name: "Block",
        template: "{\n{statements}\n}",
    },
    PrintSpec {
        name: "Expr.Call",
        template: "call {callee}({args:, })",
    },
    PrintSpec {
        name: "Expr.Literal",
        template: "{value}",
    },
    PrintSpec {
        name: "Expr.Local",
        template: "{name}",
    },
    PrintSpec {
        name: "Function",
        template: "fn {name}({params:, }) -> {return_type} {body}",
    },
    PrintSpec {
        name: "Module",
        template: "module {\n{functions}\n}",
    },
    PrintSpec {
        name: "Param",
        template: "{name}: {ty}",
    },
    PrintSpec {
        name: "Stmt.Expr",
        template: "{value}",
    },
    PrintSpec {
        name: "Stmt.Return",
        template: "return{value? :  {value}}",
    },
];
