// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

use super::*;
use chumsky::prelude::*;
type ParseExtra<'src> = extra::Err<Rich<'src, char>>;
fn ws<'src>() -> impl Parser<'src, &'src str, (), ParseExtra<'src>> + Clone {
    any()
        .filter(|c: &char| c.is_whitespace())
        .repeated()
        .ignored()
}
fn ident_token<'src>() -> impl Parser<'src, &'src str, String, ParseExtra<'src>> + Clone {
    text::ident::<_, ParseExtra<'src>>()
        .map(str::to_owned)
        .padded_by(ws())
}
fn symbol_token<'src>() -> impl Parser<'src, &'src str, String, ParseExtra<'src>> + Clone {
    just('@')
        .then(text::ident::<_, ParseExtra<'src>>().map(str::to_owned))
        .then(
            just('.')
                .ignore_then(text::ident::<_, ParseExtra<'src>>().map(str::to_owned))
                .repeated()
                .collect::<Vec<_>>(),
        )
        .map(|((_, head), tail)| {
            let mut out = format!("@{head}");
            for part in tail {
                out.push('.');
                out.push_str(&part);
            }
            out
        })
        .padded_by(ws())
}
fn int_token<'src>() -> impl Parser<'src, &'src str, String, ParseExtra<'src>> + Clone {
    text::int::<_, ParseExtra<'src>>(10)
        .map(str::to_owned)
        .padded_by(ws())
}
fn prov_from_span(span: chumsky::span::SimpleSpan<usize>, file_id: Option<u32>) -> Prov {
    Prov {
        file_id,
        span: Some(Span {
            start: span.start as u32,
            end: span.end as u32,
        }),
    }
}
pub fn parse_module_text_rich(
    source: &str,

    file_id: Option<u32>,
) -> Result<Module, Vec<Rich<'_, char>>> {
    let param_parser = (((ident_token().map(Symbol)).then_ignore(just(":").padded()))
        .then(ident_token().map(Type)))
    .map_with(move |(name, ty), e| Param {
        name: name,
        prov: prov_from_span(e.span(), file_id),
        ty: ty,
    })
    .boxed();
    let expr_parser = recursive(move |expr_parser| {
        choice((
            (((((just("call").padded()).ignore_then(symbol_token().map(Symbol)))
                .then_ignore(just("(").padded()))
            .then(
                (expr_parser.clone())
                    .separated_by(just(",").padded())
                    .allow_trailing()
                    .collect::<Vec<_>>(),
            ))
            .then_ignore(just(")").padded()))
            .map_with(move |(callee, args), e| Expr::Call {
                args: args,
                callee: callee,
                prov: prov_from_span(e.span(), file_id),
            }),
            (ident_token().map(Symbol)).map_with(move |name, e| Expr::Local {
                name: name,
                prov: prov_from_span(e.span(), file_id),
            }),
            (int_token().map(Literal)).map_with(move |value, e| Expr::Literal {
                prov: prov_from_span(e.span(), file_id),
                value: value,
            }),
        ))
        .boxed()
    });
    let stmt_parser = choice((
        ((just("return").padded()).ignore_then(((expr_parser.clone()).map(Box::new)).or_not()))
            .map_with(move |value, e| Stmt::Return {
                prov: prov_from_span(e.span(), file_id),
                value: value,
            }),
        ((expr_parser.clone()).map(Box::new)).map_with(move |value, e| Stmt::Expr {
            prov: prov_from_span(e.span(), file_id),
            value: value,
        }),
    ))
    .boxed();
    let block_parser = (((just("{").padded())
        .ignore_then((stmt_parser.clone()).repeated().collect::<Vec<_>>()))
    .then_ignore(just("}").padded()))
    .map_with(move |statements, e| Block {
        prov: prov_from_span(e.span(), file_id),
        statements: statements,
    })
    .boxed();
    let function_parser = ((((((((just("fn").padded())
        .ignore_then(ident_token().map(Symbol)))
    .then_ignore(just("(").padded()))
    .then(
        (param_parser.clone())
            .separated_by(just(",").padded())
            .allow_trailing()
            .collect::<Vec<_>>(),
    ))
    .then_ignore(just(")").padded()))
    .then_ignore(just("->").padded()))
    .then(ident_token().map(Type)))
    .then((block_parser.clone()).map(Box::new)))
    .map_with(move |(((name, params), return_type), body), e| Function {
        body: body,
        docs: None,
        locals: Vec::new(),
        name: name,
        params: params,
        prov: prov_from_span(e.span(), file_id),
        return_type: return_type,
    })
    .boxed();
    let module_parser = (((just("module").padded()).ignore_then(
        (just("{").padded()).ignore_then((function_parser.clone()).repeated().collect::<Vec<_>>()),
    ))
    .then_ignore(just("}").padded()))
    .map_with(move |functions, _e| Module {
        docs: None,
        functions: functions,
        type_defs: Vec::new(),
    })
    .boxed();
    module_parser.then_ignore(end()).parse(source).into_result()
}
pub fn parse_module_text_with_file_id(
    source: &str,

    file_id: Option<u32>,
) -> Result<Module, String> {
    parse_module_text_rich(source, file_id).map_err(|errs| crate::format_rich_errors(source, errs))
}
pub fn parse_module_text(source: &str) -> Result<Module, String> {
    parse_module_text_with_file_id(source, None)
}
