// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

use super::ast::*;

pub trait HasProvenance {
    fn provenance(&self) -> Option<&Prov>;
}

impl HasProvenance for Block {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}

impl HasProvenance for Expr {
    fn provenance(&self) -> Option<&Prov> {
        match self {
            Self::Binary { prov, .. } => Some(prov),
            Self::Call { prov, .. } => Some(prov),
            Self::Field { prov, .. } => Some(prov),
            Self::Literal { prov, .. } => Some(prov),
            Self::Local { prov, .. } => Some(prov),
        }
    }
}

impl HasProvenance for Function {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}

impl HasProvenance for Local {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}

impl HasProvenance for Param {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}

impl HasProvenance for Place {
    fn provenance(&self) -> Option<&Prov> {
        match self {
            Self::Field { prov, .. } => Some(prov),
            Self::Local { prov, .. } => Some(prov),
        }
    }
}

impl HasProvenance for Stmt {
    fn provenance(&self) -> Option<&Prov> {
        match self {
            Self::Assign { prov, .. } => Some(prov),
            Self::Expr { prov, .. } => Some(prov),
            Self::If { prov, .. } => Some(prov),
            Self::Init { prov, .. } => Some(prov),
            Self::Return { prov, .. } => Some(prov),
        }
    }
}

impl HasProvenance for TypeDef {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}
