// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#![allow(dead_code, unused_variables)]
use super::provenance::HasProvenance;
use super::*;
use crate::schema_poc::SemanticToken;
use kajit_types::Prov;
pub fn semantic_tokens(source: &str) -> Vec<SemanticToken> {
    let Ok(root) = parse_root_text_rich(source, None) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    collect_module(source, &root, &mut out);
    out.sort_by_key(|token| (token.start, token.end, token.kind));
    out.dedup_by(|a, b| a.start == b.start && a.end == b.end && a.kind == b.kind);
    out
}
fn emit_prov_token(prov: &Prov, kind: &'static str, out: &mut Vec<SemanticToken>) {
    let Some(span) = prov.span.as_ref() else {
        return;
    };
    if span.end <= span.start {
        return;
    }
    out.push(SemanticToken {
        start: span.start,
        end: span.end,
        kind,
    });
}
fn emit_literal_token(
    source: &str,

    prov: Option<&Prov>,

    text: &str,

    kind: &'static str,

    out: &mut Vec<SemanticToken>,
) {
    let Some(prov) = prov else {
        return;
    };
    let Some(span) = prov.span.as_ref() else {
        return;
    };
    let start = span.start as usize;
    let end = span.end as usize;
    if start > end || end > source.len() {
        return;
    }
    let Some(offset) = source[start..end].find(text) else {
        return;
    };
    out.push(SemanticToken {
        start: (start + offset) as u32,
        end: (start + offset + text.len()) as u32,
        kind,
    });
}
fn collect_block(source: &str, node: &Block, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
    for value in &node.statements {
        collect_stmt(source, value, out);
    }
}
fn collect_expr(source: &str, node: &Expr, out: &mut Vec<SemanticToken>) {
    match node {
        Expr::Binary { lhs, op, prov, rhs } => {
            let current_prov = node.provenance();
            collect_expr(source, lhs, out);
            collect_expr(source, rhs, out);
        }
        Expr::Call { args, callee, prov } => {
            let current_prov = node.provenance();
            emit_literal_token(source, current_prov, "call", "keyword", out);
            emit_prov_token(&callee.prov, "function", out);
            for value in args {
                collect_expr(source, value, out);
            }
        }
        Expr::Field { base, field, prov } => {
            let current_prov = node.provenance();
            collect_expr(source, base, out);
        }
        Expr::Literal { prov, value } => {
            let current_prov = node.provenance();
            emit_prov_token(&value.prov, "number", out);
        }
        Expr::Local { name, prov } => {
            let current_prov = node.provenance();
            emit_prov_token(&name.prov, "variable", out);
        }
    }
}
fn collect_function(source: &str, node: &Function, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
    emit_literal_token(source, current_prov, "fn", "keyword", out);
    emit_prov_token(&node.name.prov, "function", out);
    emit_prov_token(&node.return_type.prov, "type", out);
    collect_block(source, &node.body, out);
    for value in &node.locals {
        collect_local(source, value, out);
    }
    for value in &node.params {
        collect_param(source, value, out);
    }
}
fn collect_local(source: &str, node: &Local, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
    emit_prov_token(&node.name.prov, "variable", out);
    emit_prov_token(&node.ty.prov, "type", out);
}
fn collect_module(source: &str, node: &Module, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
    emit_literal_token(source, current_prov, "module", "keyword", out);
    for value in &node.functions {
        collect_function(source, value, out);
    }
    for value in &node.type_defs {
        collect_type_def(source, value, out);
    }
}
fn collect_param(source: &str, node: &Param, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
    emit_prov_token(&node.name.prov, "parameter", out);
    emit_prov_token(&node.ty.prov, "type", out);
}
fn collect_place(source: &str, node: &Place, out: &mut Vec<SemanticToken>) {
    match node {
        Place::Field { base, field, prov } => {
            let current_prov = node.provenance();
            collect_place(source, base, out);
        }
        Place::Local { name, prov } => {
            let current_prov = node.provenance();
        }
    }
}
fn collect_stmt(source: &str, node: &Stmt, out: &mut Vec<SemanticToken>) {
    match node {
        Stmt::Assign { place, prov, value } => {
            let current_prov = node.provenance();
            collect_place(source, place, out);
            collect_expr(source, value, out);
        }
        Stmt::Expr { prov, value } => {
            let current_prov = node.provenance();
            collect_expr(source, value, out);
        }
        Stmt::If {
            condition,
            r#else,
            prov,
            then,
        } => {
            let current_prov = node.provenance();
            collect_expr(source, condition, out);
            if let Some(value) = r#else.as_ref() {
                collect_block(source, value, out);
            }
            collect_block(source, then, out);
        }
        Stmt::Init { place, prov, value } => {
            let current_prov = node.provenance();
            collect_place(source, place, out);
            collect_expr(source, value, out);
        }
        Stmt::Return { prov, value } => {
            let current_prov = node.provenance();
            emit_literal_token(source, current_prov, "return", "keyword", out);
            if let Some(value) = value.as_ref() {
                collect_expr(source, value, out);
            }
        }
    }
}
fn collect_type_def(source: &str, node: &TypeDef, out: &mut Vec<SemanticToken>) {
    let current_prov = node.provenance();
    emit_prov_token(&node.name.prov, "type", out);
}
