// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#![allow(unused_variables)]
use super::*;

pub trait Visit {
    fn visit_block(&mut self, node: &Block) {
        walk_block(self, node);
    }
    fn visit_expr(&mut self, node: &Expr) {
        walk_expr(self, node);
    }
    fn visit_function(&mut self, node: &Function) {
        walk_function(self, node);
    }
    fn visit_local(&mut self, node: &Local) {
        walk_local(self, node);
    }
    fn visit_module(&mut self, node: &Module) {
        walk_module(self, node);
    }
    fn visit_param(&mut self, node: &Param) {
        walk_param(self, node);
    }
    fn visit_place(&mut self, node: &Place) {
        walk_place(self, node);
    }
    fn visit_stmt(&mut self, node: &Stmt) {
        walk_stmt(self, node);
    }
    fn visit_type_def(&mut self, node: &TypeDef) {
        walk_type_def(self, node);
    }
}

pub trait VisitMut {
    fn visit_block_mut(&mut self, node: &mut Block) {
        walk_block_mut(self, node);
    }
    fn visit_expr_mut(&mut self, node: &mut Expr) {
        walk_expr_mut(self, node);
    }
    fn visit_function_mut(&mut self, node: &mut Function) {
        walk_function_mut(self, node);
    }
    fn visit_local_mut(&mut self, node: &mut Local) {
        walk_local_mut(self, node);
    }
    fn visit_module_mut(&mut self, node: &mut Module) {
        walk_module_mut(self, node);
    }
    fn visit_param_mut(&mut self, node: &mut Param) {
        walk_param_mut(self, node);
    }
    fn visit_place_mut(&mut self, node: &mut Place) {
        walk_place_mut(self, node);
    }
    fn visit_stmt_mut(&mut self, node: &mut Stmt) {
        walk_stmt_mut(self, node);
    }
    fn visit_type_def_mut(&mut self, node: &mut TypeDef) {
        walk_type_def_mut(self, node);
    }
}
pub fn walk_block<V: ?Sized + Visit>(v: &mut V, node: &Block) {
    for value in node.statements.iter() {
        v.visit_stmt(value);
    }
}
pub fn walk_expr<V: ?Sized + Visit>(v: &mut V, node: &Expr) {
    match node {
        Expr::Binary { lhs, rhs, .. } => {
            v.visit_expr(lhs);
            v.visit_expr(rhs);
        }
        Expr::Call { args, .. } => {
            for value in args.iter() {
                v.visit_expr(value);
            }
        }
        Expr::Field { base, .. } => {
            v.visit_expr(base);
        }
        Expr::Literal { .. } => {}
        Expr::Local { .. } => {}
    }
}
pub fn walk_function<V: ?Sized + Visit>(v: &mut V, node: &Function) {
    v.visit_block(&node.body);
    for value in node.locals.iter() {
        v.visit_local(value);
    }
    for value in node.params.iter() {
        v.visit_param(value);
    }
}
pub fn walk_local<V: ?Sized + Visit>(_v: &mut V, _node: &Local) {}
pub fn walk_module<V: ?Sized + Visit>(v: &mut V, node: &Module) {
    for value in node.functions.iter() {
        v.visit_function(value);
    }
    for value in node.type_defs.iter() {
        v.visit_type_def(value);
    }
}
pub fn walk_param<V: ?Sized + Visit>(_v: &mut V, _node: &Param) {}
pub fn walk_place<V: ?Sized + Visit>(v: &mut V, node: &Place) {
    match node {
        Place::Field { base, .. } => {
            v.visit_place(base);
        }
        Place::Local { .. } => {}
    }
}
pub fn walk_stmt<V: ?Sized + Visit>(v: &mut V, node: &Stmt) {
    match node {
        Stmt::Assign { place, value, .. } => {
            v.visit_place(place);
            v.visit_expr(value);
        }
        Stmt::Expr { value, .. } => {
            v.visit_expr(value);
        }
        Stmt::If {
            condition,
            r#else,
            then,
            ..
        } => {
            v.visit_expr(condition);
            if let Some(value) = r#else {
                v.visit_block(value);
            }
            v.visit_block(then);
        }
        Stmt::Init { place, value, .. } => {
            v.visit_place(place);
            v.visit_expr(value);
        }
        Stmt::Return { value, .. } => {
            if let Some(value) = value {
                v.visit_expr(value);
            }
        }
    }
}
pub fn walk_type_def<V: ?Sized + Visit>(_v: &mut V, _node: &TypeDef) {}
pub fn walk_block_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut Block) {
    for value in node.statements.iter_mut() {
        v.visit_stmt_mut(value);
    }
}
pub fn walk_expr_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut Expr) {
    match node {
        Expr::Binary { lhs, rhs, .. } => {
            v.visit_expr_mut(lhs);
            v.visit_expr_mut(rhs);
        }
        Expr::Call { args, .. } => {
            for value in args.iter_mut() {
                v.visit_expr_mut(value);
            }
        }
        Expr::Field { base, .. } => {
            v.visit_expr_mut(base);
        }
        Expr::Literal { .. } => {}
        Expr::Local { .. } => {}
    }
}
pub fn walk_function_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut Function) {
    v.visit_block_mut(&mut node.body);
    for value in node.locals.iter_mut() {
        v.visit_local_mut(value);
    }
    for value in node.params.iter_mut() {
        v.visit_param_mut(value);
    }
}
pub fn walk_local_mut<V: ?Sized + VisitMut>(_v: &mut V, _node: &mut Local) {}
pub fn walk_module_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut Module) {
    for value in node.functions.iter_mut() {
        v.visit_function_mut(value);
    }
    for value in node.type_defs.iter_mut() {
        v.visit_type_def_mut(value);
    }
}
pub fn walk_param_mut<V: ?Sized + VisitMut>(_v: &mut V, _node: &mut Param) {}
pub fn walk_place_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut Place) {
    match node {
        Place::Field { base, .. } => {
            v.visit_place_mut(base);
        }
        Place::Local { .. } => {}
    }
}
pub fn walk_stmt_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut Stmt) {
    match node {
        Stmt::Assign { place, value, .. } => {
            v.visit_place_mut(place);
            v.visit_expr_mut(value);
        }
        Stmt::Expr { value, .. } => {
            v.visit_expr_mut(value);
        }
        Stmt::If {
            condition,
            r#else,
            then,
            ..
        } => {
            v.visit_expr_mut(condition);
            if let Some(value) = r#else {
                v.visit_block_mut(value);
            }
            v.visit_block_mut(then);
        }
        Stmt::Init { place, value, .. } => {
            v.visit_place_mut(place);
            v.visit_expr_mut(value);
        }
        Stmt::Return { value, .. } => {
            if let Some(value) = value {
                v.visit_expr_mut(value);
            }
        }
    }
}
pub fn walk_type_def_mut<V: ?Sized + VisitMut>(_v: &mut V, _node: &mut TypeDef) {}
