// @generated by xtask generate-synthetic. Do not edit manually.
use facet::Facet;
use proptest::arbitrary::Arbitrary;
use std::fmt::Write;
#[cfg(target_arch = "x86_64")]
use yaxpeax_arch::LengthedInstruction;
use yaxpeax_arch::{Decoder, U8Reader};
use serde::{Serialize, Deserialize};
use std::collections::{BTreeMap, HashMap};
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct Friend {
    age: u32,
    #[proptest(strategy = "proptest::string::string_regex(\"(?s).{0,64}\").unwrap()")]
    name: String,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct Address {
    #[proptest(strategy = "proptest::string::string_regex(\"(?s).{0,64}\").unwrap()")]
    city: String,
    zip: u32,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct Person {
    #[proptest(strategy = "proptest::string::string_regex(\"(?s).{0,64}\").unwrap()")]
    name: String,
    age: u32,
    address: Address,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct Metadata {
    version: u32,
    #[proptest(strategy = "proptest::string::string_regex(\"(?s).{0,64}\").unwrap()")]
    author: String,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct Document {
    #[proptest(strategy = "proptest::string::string_regex(\"(?s).{0,64}\").unwrap()")]
    title: String,
    #[facet(flatten)]
    meta: Metadata,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
#[repr(u8)]
enum Animal {
    Cat,
    Dog { name: String, good_boy: bool },
    Parrot(String),
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct Zoo {
    #[proptest(strategy = "proptest::string::string_regex(\"(?s).{0,64}\").unwrap()")]
    name: String,
    star: Animal,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
#[facet(tag = "type", content = "data")]
#[repr(u8)]
enum AdjAnimal {
    Cat,
    Dog { name: String, good_boy: bool },
    Parrot(String),
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
#[facet(tag = "type")]
#[repr(u8)]
enum IntAnimal {
    Cat,
    Dog { name: String, good_boy: bool },
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
#[facet(untagged)]
#[repr(u8)]
enum UntaggedAnimal {
    Cat,
    Dog { name: String, good_boy: bool },
    Parrot(String),
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
#[facet(untagged)]
#[repr(u8)]
enum UntaggedConfig {
    Database { host: String, port: u32 },
    Redis { host: String, db: u32 },
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
struct SuccessPayload {
    items: u32,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
struct ErrorPayload {
    message: String,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
#[facet(untagged)]
#[repr(u8)]
enum ApiResponse {
    Success { status: u32, data: SuccessPayload },
    Error { status: u32, data: ErrorPayload },
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct Inner {
    x: u32,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct Middle {
    inner: Inner,
    y: u32,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct Outer {
    middle: Middle,
    z: u32,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct AllIntegers {
    a_u8: u8,
    a_u16: u16,
    a_u32: u32,
    a_u64: u64,
    a_u128: u128,
    a_usize: usize,
    a_i8: i8,
    a_i16: i16,
    a_i32: i32,
    a_i64: i64,
    a_i128: i128,
    a_isize: isize,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct BoolField {
    value: bool,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct WithOptU32 {
    value: Option<u32>,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct WithOptStr {
    #[proptest(
        strategy = "proptest::option::of(proptest::string::string_regex(\"(?s).{0,64}\").unwrap())"
    )]
    name: Option<String>,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct WithOptAddr {
    addr: Option<Address>,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct MultiOpt {
    a: Option<u32>,
    #[proptest(strategy = "proptest::string::string_regex(\"(?s).{0,64}\").unwrap()")]
    b: String,
    #[proptest(
        strategy = "proptest::option::of(proptest::string::string_regex(\"(?s).{0,64}\").unwrap())"
    )]
    c: Option<String>,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct RenameField {
    #[facet(rename = "user_name")]
    name: String,
    age: u32,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
#[facet(rename_all = "camelCase")]
struct CamelCaseStruct {
    user_name: String,
    birth_year: u32,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
#[facet(deny_unknown_fields)]
struct Strict {
    x: u32,
    y: u32,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
struct WithDefault {
    name: String,
    #[facet(default)]
    score: u32,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
struct WithDefaultString {
    #[facet(default)]
    label: String,
    value: u32,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
#[facet(default)]
struct AllDefault {
    x: u32,
    y: u32,
}
impl Default for AllDefault {
    fn default() -> Self {
        AllDefault { x: 10, y: 20 }
    }
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
struct WithSkip {
    name: String,
    #[facet(skip, default)]
    cached: u32,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
struct WithSkipDeser {
    name: String,
    #[facet(skip_deserializing, default)]
    internal: u32,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
struct SkipWithCustomDefault {
    value: u32,
    #[facet(skip, default = 42)]
    magic: u32,
}
#[derive(Debug, PartialEq, Facet)]
struct RcScalar {
    value: std::rc::Rc<u32>,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct ScalarVec {
    #[proptest(
        strategy = "proptest::collection::vec(proptest::arbitrary::any::<u32>(), 0..256)"
    )]
    values: Vec<u32>,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct Nums {
    #[proptest(
        strategy = "proptest::collection::vec(proptest::arbitrary::any::<u32>(), 0..256)"
    )]
    vals: Vec<u32>,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct Names {
    #[proptest(
        strategy = "proptest::collection::vec(proptest::string::string_regex(\"(?s).{0,32}\").unwrap(), 0..128)"
    )]
    items: Vec<String>,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct AddressList {
    #[proptest(
        strategy = "proptest::collection::vec(proptest::arbitrary::any::<Address>(), 0..128)"
    )]
    addrs: Vec<Address>,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct TwoAddresses {
    home: Address,
    work: Address,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct ConfigMap {
    #[proptest(
        strategy = "proptest::collection::hash_map(proptest::string::string_regex(\"[a-z]{1,8}\").unwrap(), proptest::arbitrary::any::<u32>(), 0..32)"
    )]
    scores: HashMap<String, u32>,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct EnvMap {
    #[proptest(
        strategy = "proptest::collection::hash_map(proptest::string::string_regex(\"[A-Z_]{1,8}\").unwrap(), proptest::string::string_regex(\"(?s).{0,16}\").unwrap(), 0..32)"
    )]
    vars: HashMap<String, String>,
}
#[derive(Debug, PartialEq, Serialize, Deserialize, Facet, proptest_derive::Arbitrary)]
struct BTreeConfigMap {
    #[proptest(
        strategy = "proptest::collection::btree_map(proptest::string::string_regex(\"[a-z]{1,8}\").unwrap(), proptest::arbitrary::any::<u32>(), 0..32)"
    )]
    scores: BTreeMap<String, u32>,
}
#[allow(dead_code)]
type Pair = (u32, String);
fn assert_json_case<T>(value: T)
where
    for<'input> T: Facet<'input> + serde::Serialize + serde::de::DeserializeOwned
        + PartialEq + std::fmt::Debug,
{
    let encoded = serde_json::to_string(&value).unwrap();
    let expected: T = serde_json::from_str(&encoded).unwrap();
    let decoder = kajit::compile_decoder_legacy(T::SHAPE, &kajit::json::KajitJson);
    let got: T = kajit::from_str(&decoder, &encoded).unwrap();
    assert_eq!(got, expected);
}
fn assert_postcard_case<T>(value: T)
where
    for<'input> T: Facet<'input> + serde::Serialize + serde::de::DeserializeOwned
        + PartialEq + std::fmt::Debug,
{
    let encoded = ::postcard::to_allocvec(&value).unwrap();
    let expected: T = ::postcard::from_bytes(&encoded).unwrap();
    let legacy = kajit::compile_decoder_legacy(
        T::SHAPE,
        &kajit::postcard::KajitPostcard,
    );
    let legacy_out: T = kajit::deserialize(&legacy, &encoded).unwrap();
    assert_eq!(legacy_out, expected);
    let ir = kajit::compile_decoder_via_ir(T::SHAPE, &kajit::postcard::KajitPostcard);
    let ir_out: T = kajit::deserialize(&ir, &encoded).unwrap();
    assert_eq!(ir_out, expected);
}
fn assert_json_input_case<T>(input: &[u8], expected: T)
where
    for<'input> T: Facet<'input> + PartialEq + std::fmt::Debug,
{
    let decoder = kajit::compile_decoder_legacy(T::SHAPE, &kajit::json::KajitJson);
    let got: T = kajit::deserialize(&decoder, input).unwrap();
    assert_eq!(got, expected);
}
fn assert_json_input_err<T>(input: &[u8])
where
    for<'input> T: Facet<'input>,
{
    let decoder = kajit::compile_decoder_legacy(T::SHAPE, &kajit::json::KajitJson);
    let out = kajit::deserialize::<T>(&decoder, input);
    assert!(out.is_err(), "expected json decode failure");
}
fn assert_json_input_err_code<T>(input: &[u8], expected_code: kajit::context::ErrorCode)
where
    for<'input> T: Facet<'input>,
{
    let decoder = kajit::compile_decoder_legacy(T::SHAPE, &kajit::json::KajitJson);
    let out = kajit::deserialize::<T>(&decoder, input);
    let err = match out {
        Ok(_) => panic!("expected json decode failure"),
        Err(err) => err,
    };
    assert_eq!(err.code, expected_code);
}
fn assert_prop_case<T>(_marker: &T)
where
    for<'input> T: Facet<'input> + serde::Serialize + serde::de::DeserializeOwned
        + PartialEq + std::fmt::Debug + Arbitrary + 'static,
{
    let json_decoder = kajit::compile_decoder_legacy(T::SHAPE, &kajit::json::KajitJson);
    let postcard_legacy = kajit::compile_decoder_legacy(
        T::SHAPE,
        &kajit::postcard::KajitPostcard,
    );
    let postcard_ir = kajit::compile_decoder_via_ir(
        T::SHAPE,
        &kajit::postcard::KajitPostcard,
    );
    let mut runner = proptest::test_runner::TestRunner::new(proptest::test_runner::Config {
        cases: 64,
        ..proptest::test_runner::Config::default()
    });
    let strategy = proptest::arbitrary::any::<T>();
    runner
        .run(
            &strategy,
            |value| {
                let json_encoded = serde_json::to_string(&value).unwrap();
                let json_expected: T = serde_json::from_str(&json_encoded).unwrap();
                let json_got: T = kajit::from_str(&json_decoder, &json_encoded).unwrap();
                assert_eq!(json_got, json_expected);
                let postcard_encoded = ::postcard::to_allocvec(&value).unwrap();
                let postcard_expected: T = ::postcard::from_bytes(&postcard_encoded)
                    .unwrap();
                let postcard_legacy_out: T = kajit::deserialize(
                        &postcard_legacy,
                        &postcard_encoded,
                    )
                    .unwrap();
                assert_eq!(postcard_legacy_out, postcard_expected);
                let postcard_ir_out: T = kajit::deserialize(
                        &postcard_ir,
                        &postcard_encoded,
                    )
                    .unwrap();
                assert_eq!(postcard_ir_out, postcard_expected);
                Ok(())
            },
        )
        .unwrap();
}
fn disasm_bytes(code: &[u8], marker_offset: Option<usize>) -> String {
    let mut out = String::new();
    #[cfg(target_arch = "aarch64")]
    {
        use yaxpeax_arm::armv8::a64::InstDecoder;
        let decoder = InstDecoder::default();
        let mut reader = U8Reader::new(code);
        let mut offset = 0usize;
        let mut ret_count = 0u32;
        while offset + 4 <= code.len() {
            let prefix = if marker_offset == Some(offset) { "> " } else { "  " };
            match decoder.decode(&mut reader) {
                Ok(inst) => {
                    let text = kajit::disasm_normalize::normalize_inst(
                        &format!("{inst}"),
                    );
                    writeln!(& mut out, "{prefix}{text}").unwrap();
                    if text.trim() == "ret" {
                        ret_count += 1;
                        if ret_count >= 2 {
                            break;
                        }
                    }
                }
                Err(e) => {
                    let word = u32::from_le_bytes(
                        code[offset..offset + 4].try_into().unwrap(),
                    );
                    writeln!(& mut out, "{prefix}<{e}> (0x{word:08x})").unwrap();
                }
            }
            offset += 4;
        }
    }
    #[cfg(target_arch = "x86_64")]
    {
        use yaxpeax_x86::amd64::InstDecoder;
        let decoder = InstDecoder::default();
        let mut reader = U8Reader::new(code);
        let mut offset = 0usize;
        let mut ret_count = 0u32;
        while offset < code.len() {
            let prefix = if marker_offset == Some(offset) { "> " } else { "  " };
            match decoder.decode(&mut reader) {
                Ok(inst) => {
                    let len = inst.len().to_const() as usize;
                    let text = kajit::disasm_normalize::normalize_inst(
                        &format!("{inst}"),
                    );
                    writeln!(& mut out, "{prefix}{text}").unwrap();
                    if text.trim() == "ret" {
                        ret_count += 1;
                        if ret_count >= 2 {
                            break;
                        }
                    }
                    offset += len;
                }
                Err(_) => {
                    writeln!(
                        & mut out, "{prefix}<decode error> (0x{:02x})", code[offset]
                    )
                        .unwrap();
                    offset += 1;
                }
            }
        }
    }
    out
}
fn codegen_artifacts<T, F>(decoder: &F) -> (String, String, usize, String)
where
    for<'input> T: Facet<'input>,
    F: kajit::format::Decoder + kajit::format::IrDecoder,
{
    let shape = T::SHAPE;
    let (ir_text, ra_text) = kajit::debug_ir_and_ra_mir_text(shape, decoder);
    let edits = kajit::regalloc_edit_count_via_ir(shape, decoder);
    let compiled = kajit::compile_decoder_with_backend(
        shape,
        decoder,
        kajit::DecoderBackend::Ir,
    );
    let disasm = disasm_bytes(compiled.code(), Some(compiled.entry_offset()));
    (ir_text, ra_text, edits, disasm)
}
fn assert_codegen_snapshots<T, F>(
    format_label: &str,
    case: &str,
    decoder: &F,
    _marker: &T,
)
where
    for<'input> T: Facet<'input>,
    F: kajit::format::Decoder + kajit::format::IrDecoder,
{
    let (ir_text, ra_text, edits, disasm) = codegen_artifacts::<T, F>(decoder);
    insta::assert_snapshot!(
        format!("generated_rvsdg_{}_{}_{}", format_label, case, std::env::consts::ARCH),
        ir_text
    );
    insta::assert_snapshot!(
        format!("generated_ra_mir_{}_{}_{}", format_label, case, std::env::consts::ARCH),
        ra_text
    );
    insta::assert_snapshot!(
        format!("generated_postreg_disasm_{}_{}_{}", format_label, case,
        std::env::consts::ARCH), disasm
    );
    insta::assert_snapshot!(
        format!("generated_postreg_edits_{}_{}_{}", format_label, case,
        std::env::consts::ARCH), format!("{edits}")
    );
}
mod json {
    use super::*;
    #[test]
    fn flat_struct() {
        let value = Friend {
            age: 42,
            name: "Alice".into(),
        };
        assert_codegen_snapshots("json", "flat_struct", &kajit::json::KajitJson, &value);
        assert_json_case(value);
    }
    #[test]
    fn nested_struct() {
        let value = Person {
            name: "Alice".into(),
            age: 30,
            address: Address {
                city: "Portland".into(),
                zip: 97201,
            },
        };
        assert_codegen_snapshots(
            "json",
            "nested_struct",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn deep_struct() {
        let value = Outer {
            middle: Middle {
                inner: Inner { x: 1 },
                y: 2,
            },
            z: 3,
        };
        assert_codegen_snapshots("json", "deep_struct", &kajit::json::KajitJson, &value);
        assert_json_case(value);
    }
    #[test]
    fn all_integers() {
        let value = AllIntegers {
            a_u8: 255,
            a_u16: 65535,
            a_u32: 1_000_000,
            a_u64: 1_000_000_000_000,
            a_u128: 340282366920938463463374607431768211455u128,
            a_usize: 123_456usize,
            a_i8: -128,
            a_i16: -32768,
            a_i32: -1_000_000,
            a_i64: -1_000_000_000_000,
            a_i128: -170141183460469231731687303715884105728i128,
            a_isize: -123_456isize,
        };
        assert_codegen_snapshots(
            "json",
            "all_integers",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn bool_field() {
        let value = BoolField { value: true };
        assert_codegen_snapshots("json", "bool_field", &kajit::json::KajitJson, &value);
        assert_json_case(value);
    }
    #[test]
    fn enum_external_v0() {
        let value = Animal::Cat;
        assert_codegen_snapshots(
            "json",
            "enum_external__v0",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn enum_external_v1() {
        let value = Animal::Dog {
            name: "Rex".into(),
            good_boy: true,
        };
        assert_codegen_snapshots(
            "json",
            "enum_external__v1",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn enum_external_v2() {
        let value = Animal::Parrot("Polly".into());
        assert_codegen_snapshots(
            "json",
            "enum_external__v2",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn enum_as_struct_field() {
        let value = Zoo {
            name: "City Zoo".into(),
            star: Animal::Dog {
                name: "Rex".into(),
                good_boy: true,
            },
        };
        assert_codegen_snapshots(
            "json",
            "enum_as_struct_field",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn tuple_pair() {
        let value = (42u32, "Alice".to_string());
        assert_codegen_snapshots("json", "tuple_pair", &kajit::json::KajitJson, &value);
        assert_json_case(value);
    }
    #[test]
    fn vec_scalar_small() {
        let value = ScalarVec {
            values: (0..16).map(|i| i as u32).collect(),
        };
        assert_codegen_snapshots(
            "json",
            "vec_scalar_small",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn vec_scalar_large() {
        let value = ScalarVec {
            values: (0..2048).map(|i| i as u32).collect(),
        };
        assert_codegen_snapshots(
            "json",
            "vec_scalar_large",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn flatten() {
        let value = Document {
            title: "Hello".into(),
            meta: Metadata {
                version: 1,
                author: "Amos".into(),
            },
        };
        assert_codegen_snapshots("json", "flatten", &kajit::json::KajitJson, &value);
        assert_json_case(value);
    }
    #[test]
    fn option_u32_v0() {
        let value = WithOptU32 { value: Some(42) };
        assert_codegen_snapshots(
            "json",
            "option_u32__v0",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn option_u32_v1() {
        let value = WithOptU32 { value: None };
        assert_codegen_snapshots(
            "json",
            "option_u32__v1",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn option_string_v0() {
        let value = WithOptStr {
            name: Some("Alice".into()),
        };
        assert_codegen_snapshots(
            "json",
            "option_string__v0",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn option_string_v1() {
        let value = WithOptStr { name: None };
        assert_codegen_snapshots(
            "json",
            "option_string__v1",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn option_struct_v0() {
        let value = WithOptAddr {
            addr: Some(Address {
                city: "Portland".into(),
                zip: 97201,
            }),
        };
        assert_codegen_snapshots(
            "json",
            "option_struct__v0",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn option_struct_v1() {
        let value = WithOptAddr { addr: None };
        assert_codegen_snapshots(
            "json",
            "option_struct__v1",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn multi_options() {
        let value = MultiOpt {
            a: Some(7),
            b: "hello".into(),
            c: None,
        };
        assert_codegen_snapshots(
            "json",
            "multi_options",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn vec_u32_v0() {
        let value = Nums { vals: vec![1, 2, 3] };
        assert_codegen_snapshots("json", "vec_u32__v0", &kajit::json::KajitJson, &value);
        assert_json_case(value);
    }
    #[test]
    fn vec_u32_v1() {
        let value = Nums { vals: vec![] };
        assert_codegen_snapshots("json", "vec_u32__v1", &kajit::json::KajitJson, &value);
        assert_json_case(value);
    }
    #[test]
    fn vec_string_v0() {
        let value = Names {
            items: vec!["hello".into(), "world".into()],
        };
        assert_codegen_snapshots(
            "json",
            "vec_string__v0",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn vec_string_v1() {
        let value = Names { items: vec![] };
        assert_codegen_snapshots(
            "json",
            "vec_string__v1",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn vec_nested_struct() {
        let value = AddressList {
            addrs: vec![
                Address { city : "Portland".into(), zip : 97201 }, Address { city :
                "Seattle".into(), zip : 98101 },
            ],
        };
        assert_codegen_snapshots(
            "json",
            "vec_nested_struct",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
    #[test]
    fn shared_inner_type() {
        let value = TwoAddresses {
            home: Address {
                city: "Portland".into(),
                zip: 97201,
            },
            work: Address {
                city: "Seattle".into(),
                zip: 98101,
            },
        };
        assert_codegen_snapshots(
            "json",
            "shared_inner_type",
            &kajit::json::KajitJson,
            &value,
        );
        assert_json_case(value);
    }
}
mod postcard {
    use super::*;
    #[test]
    fn flat_struct() {
        let value = Friend {
            age: 42,
            name: "Alice".into(),
        };
        assert_codegen_snapshots(
            "postcard",
            "flat_struct",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn nested_struct() {
        let value = Person {
            name: "Alice".into(),
            age: 30,
            address: Address {
                city: "Portland".into(),
                zip: 97201,
            },
        };
        assert_codegen_snapshots(
            "postcard",
            "nested_struct",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn deep_struct() {
        let value = Outer {
            middle: Middle {
                inner: Inner { x: 1 },
                y: 2,
            },
            z: 3,
        };
        assert_codegen_snapshots(
            "postcard",
            "deep_struct",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn all_integers() {
        let value = AllIntegers {
            a_u8: 255,
            a_u16: 65535,
            a_u32: 1_000_000,
            a_u64: 1_000_000_000_000,
            a_u128: 340282366920938463463374607431768211455u128,
            a_usize: 123_456usize,
            a_i8: -128,
            a_i16: -32768,
            a_i32: -1_000_000,
            a_i64: -1_000_000_000_000,
            a_i128: -170141183460469231731687303715884105728i128,
            a_isize: -123_456isize,
        };
        assert_codegen_snapshots(
            "postcard",
            "all_integers",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn bool_field() {
        let value = BoolField { value: true };
        assert_codegen_snapshots(
            "postcard",
            "bool_field",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn enum_external_v0() {
        let value = Animal::Cat;
        assert_codegen_snapshots(
            "postcard",
            "enum_external__v0",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn enum_external_v1() {
        let value = Animal::Dog {
            name: "Rex".into(),
            good_boy: true,
        };
        assert_codegen_snapshots(
            "postcard",
            "enum_external__v1",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn enum_external_v2() {
        let value = Animal::Parrot("Polly".into());
        assert_codegen_snapshots(
            "postcard",
            "enum_external__v2",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn enum_as_struct_field() {
        let value = Zoo {
            name: "City Zoo".into(),
            star: Animal::Dog {
                name: "Rex".into(),
                good_boy: true,
            },
        };
        assert_codegen_snapshots(
            "postcard",
            "enum_as_struct_field",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn tuple_pair() {
        let value = (42u32, "Alice".to_string());
        assert_codegen_snapshots(
            "postcard",
            "tuple_pair",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn vec_scalar_small() {
        let value = ScalarVec {
            values: (0..16).map(|i| i as u32).collect(),
        };
        assert_codegen_snapshots(
            "postcard",
            "vec_scalar_small",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn vec_scalar_large() {
        let value = ScalarVec {
            values: (0..2048).map(|i| i as u32).collect(),
        };
        assert_codegen_snapshots(
            "postcard",
            "vec_scalar_large",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn flatten() {
        let value = Document {
            title: "Hello".into(),
            meta: Metadata {
                version: 1,
                author: "Amos".into(),
            },
        };
        assert_codegen_snapshots(
            "postcard",
            "flatten",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn option_u32_v0() {
        let value = WithOptU32 { value: Some(42) };
        assert_codegen_snapshots(
            "postcard",
            "option_u32__v0",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn option_u32_v1() {
        let value = WithOptU32 { value: None };
        assert_codegen_snapshots(
            "postcard",
            "option_u32__v1",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn option_string_v0() {
        let value = WithOptStr {
            name: Some("Alice".into()),
        };
        assert_codegen_snapshots(
            "postcard",
            "option_string__v0",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn option_string_v1() {
        let value = WithOptStr { name: None };
        assert_codegen_snapshots(
            "postcard",
            "option_string__v1",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn option_struct_v0() {
        let value = WithOptAddr {
            addr: Some(Address {
                city: "Portland".into(),
                zip: 97201,
            }),
        };
        assert_codegen_snapshots(
            "postcard",
            "option_struct__v0",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn option_struct_v1() {
        let value = WithOptAddr { addr: None };
        assert_codegen_snapshots(
            "postcard",
            "option_struct__v1",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn multi_options() {
        let value = MultiOpt {
            a: Some(7),
            b: "hello".into(),
            c: None,
        };
        assert_codegen_snapshots(
            "postcard",
            "multi_options",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn vec_u32_v0() {
        let value = Nums { vals: vec![1, 2, 3] };
        assert_codegen_snapshots(
            "postcard",
            "vec_u32__v0",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn vec_u32_v1() {
        let value = Nums { vals: vec![] };
        assert_codegen_snapshots(
            "postcard",
            "vec_u32__v1",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn vec_string_v0() {
        let value = Names {
            items: vec!["hello".into(), "world".into()],
        };
        assert_codegen_snapshots(
            "postcard",
            "vec_string__v0",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn vec_string_v1() {
        let value = Names { items: vec![] };
        assert_codegen_snapshots(
            "postcard",
            "vec_string__v1",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn vec_nested_struct() {
        let value = AddressList {
            addrs: vec![
                Address { city : "Portland".into(), zip : 97201 }, Address { city :
                "Seattle".into(), zip : 98101 },
            ],
        };
        assert_codegen_snapshots(
            "postcard",
            "vec_nested_struct",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
    #[test]
    fn shared_inner_type() {
        let value = TwoAddresses {
            home: Address {
                city: "Portland".into(),
                zip: 97201,
            },
            work: Address {
                city: "Seattle".into(),
                zip: 98101,
            },
        };
        assert_codegen_snapshots(
            "postcard",
            "shared_inner_type",
            &kajit::postcard::KajitPostcard,
            &value,
        );
        assert_postcard_case(value);
    }
}
mod prop {
    use super::*;
    #[test]
    fn flat_struct() {
        let marker = Friend {
            age: 42,
            name: "Alice".into(),
        };
        assert_prop_case(&marker);
    }
    #[test]
    fn nested_struct() {
        let marker = Person {
            name: "Alice".into(),
            age: 30,
            address: Address {
                city: "Portland".into(),
                zip: 97201,
            },
        };
        assert_prop_case(&marker);
    }
    #[test]
    fn deep_struct() {
        let marker = Outer {
            middle: Middle {
                inner: Inner { x: 1 },
                y: 2,
            },
            z: 3,
        };
        assert_prop_case(&marker);
    }
    #[test]
    fn all_integers() {
        let marker = AllIntegers {
            a_u8: 255,
            a_u16: 65535,
            a_u32: 1_000_000,
            a_u64: 1_000_000_000_000,
            a_u128: 340282366920938463463374607431768211455u128,
            a_usize: 123_456usize,
            a_i8: -128,
            a_i16: -32768,
            a_i32: -1_000_000,
            a_i64: -1_000_000_000_000,
            a_i128: -170141183460469231731687303715884105728i128,
            a_isize: -123_456isize,
        };
        assert_prop_case(&marker);
    }
    #[test]
    fn bool_field() {
        let marker = BoolField { value: true };
        assert_prop_case(&marker);
    }
    #[test]
    fn enum_external() {
        let marker = Animal::Cat;
        assert_prop_case(&marker);
    }
    #[test]
    fn enum_as_struct_field() {
        let marker = Zoo {
            name: "City Zoo".into(),
            star: Animal::Dog {
                name: "Rex".into(),
                good_boy: true,
            },
        };
        assert_prop_case(&marker);
    }
    #[test]
    fn tuple_pair() {
        let marker = (42u32, "Alice".to_string());
        assert_prop_case(&marker);
    }
    #[test]
    fn vec_scalar_small() {
        let marker = ScalarVec {
            values: (0..16).map(|i| i as u32).collect(),
        };
        assert_prop_case(&marker);
    }
    #[test]
    fn vec_scalar_large() {
        let marker = ScalarVec {
            values: (0..2048).map(|i| i as u32).collect(),
        };
        assert_prop_case(&marker);
    }
    #[test]
    fn flatten() {
        let marker = Document {
            title: "Hello".into(),
            meta: Metadata {
                version: 1,
                author: "Amos".into(),
            },
        };
        assert_prop_case(&marker);
    }
    #[test]
    fn option_u32() {
        let marker = WithOptU32 { value: Some(42) };
        assert_prop_case(&marker);
    }
    #[test]
    fn option_string() {
        let marker = WithOptStr {
            name: Some("Alice".into()),
        };
        assert_prop_case(&marker);
    }
    #[test]
    fn option_struct() {
        let marker = WithOptAddr {
            addr: Some(Address {
                city: "Portland".into(),
                zip: 97201,
            }),
        };
        assert_prop_case(&marker);
    }
    #[test]
    fn multi_options() {
        let marker = MultiOpt {
            a: Some(7),
            b: "hello".into(),
            c: None,
        };
        assert_prop_case(&marker);
    }
    #[test]
    fn vec_u32() {
        let marker = Nums { vals: vec![1, 2, 3] };
        assert_prop_case(&marker);
    }
    #[test]
    fn vec_string() {
        let marker = Names {
            items: vec!["hello".into(), "world".into()],
        };
        assert_prop_case(&marker);
    }
    #[test]
    fn vec_nested_struct() {
        let marker = AddressList {
            addrs: vec![
                Address { city : "Portland".into(), zip : 97201 }, Address { city :
                "Seattle".into(), zip : 98101 },
            ],
        };
        assert_prop_case(&marker);
    }
    #[test]
    fn shared_inner_type() {
        let marker = TwoAddresses {
            home: Address {
                city: "Portland".into(),
                zip: 97201,
            },
            work: Address {
                city: "Seattle".into(),
                zip: 98101,
            },
        };
        assert_prop_case(&marker);
    }
}
mod json_input {
    use super::*;
    #[test]
    fn reversed_key_order() {
        assert_json_input_case::<
            Friend,
        >(
            b"{\"name\": \"Alice\", \"age\": 42}",
            Friend {
                age: 42,
                name: "Alice".into(),
            },
        );
    }
    #[test]
    fn unknown_keys_skipped() {
        assert_json_input_case::<
            Friend,
        >(
            b"{\"age\": 42, \"extra\": true, \"name\": \"Alice\"}",
            Friend {
                age: 42,
                name: "Alice".into(),
            },
        );
    }
    #[test]
    fn empty_object_missing_fields() {
        assert_json_input_err_code::<
            Friend,
        >(b"{}", kajit::context::ErrorCode::MissingRequiredField);
    }
    #[test]
    fn nested_struct_reversed_keys() {
        assert_json_input_case::<
            Person,
        >(
            b"{\"address\": {\"zip\": 97201, \"city\": \"Portland\"}, \"age\": 30, \"name\": \"Alice\"}",
            Person {
                name: "Alice".into(),
                age: 30,
                address: Address {
                    city: "Portland".into(),
                    zip: 97201,
                },
            },
        );
    }
    #[test]
    fn flatten_reversed_keys() {
        assert_json_input_case::<
            Document,
        >(
            b"{\"author\": \"Amos\", \"version\": 1, \"title\": \"Hello\"}",
            Document {
                title: "Hello".into(),
                meta: Metadata {
                    version: 1,
                    author: "Amos".into(),
                },
            },
        );
    }
    #[test]
    fn enum_struct_variant_reversed_keys() {
        assert_json_input_case::<
            Animal,
        >(
            b"{\"Dog\": {\"good_boy\": true, \"name\": \"Rex\"}}",
            Animal::Dog {
                name: "Rex".into(),
                good_boy: true,
            },
        );
    }
    #[test]
    fn enum_unit_as_string() {
        assert_json_input_case::<Animal>(b"\"Cat\"", Animal::Cat);
    }
    #[test]
    fn enum_struct_variant() {
        assert_json_input_case::<
            Animal,
        >(
            b"{\"Dog\": {\"name\": \"Rex\", \"good_boy\": true}}",
            Animal::Dog {
                name: "Rex".into(),
                good_boy: true,
            },
        );
    }
    #[test]
    fn enum_tuple_variant() {
        assert_json_input_case::<
            Animal,
        >(b"{\"Parrot\": \"Polly\"}", Animal::Parrot("Polly".into()));
    }
    #[test]
    fn enum_unit_in_object() {
        assert_json_input_case::<Animal>(b"{\"Cat\": null}", Animal::Cat);
    }
    #[test]
    fn enum_unknown_variant() {
        assert_json_input_err_code::<
            Animal,
        >(b"\"Snake\"", kajit::context::ErrorCode::UnknownVariant);
    }
    #[test]
    fn adjacent_unit_no_content() {
        assert_json_input_case::<AdjAnimal>(b"{\"type\": \"Cat\"}", AdjAnimal::Cat);
    }
    #[test]
    fn adjacent_unit_with_null_content() {
        assert_json_input_case::<
            AdjAnimal,
        >(b"{\"type\": \"Cat\", \"data\": null}", AdjAnimal::Cat);
    }
    #[test]
    fn adjacent_struct_variant() {
        assert_json_input_case::<
            AdjAnimal,
        >(
            b"{\"type\": \"Dog\", \"data\": {\"name\": \"Rex\", \"good_boy\": true}}",
            AdjAnimal::Dog {
                name: "Rex".into(),
                good_boy: true,
            },
        );
    }
    #[test]
    fn adjacent_struct_variant_reversed_fields() {
        assert_json_input_case::<
            AdjAnimal,
        >(
            b"{\"type\": \"Dog\", \"data\": {\"good_boy\": true, \"name\": \"Rex\"}}",
            AdjAnimal::Dog {
                name: "Rex".into(),
                good_boy: true,
            },
        );
    }
    #[test]
    fn adjacent_tuple_variant() {
        assert_json_input_case::<
            AdjAnimal,
        >(
            b"{\"type\": \"Parrot\", \"data\": \"Polly\"}",
            AdjAnimal::Parrot("Polly".into()),
        );
    }
    #[test]
    fn adjacent_unknown_variant() {
        assert_json_input_err_code::<
            AdjAnimal,
        >(
            b"{\"type\": \"Snake\", \"data\": null}",
            kajit::context::ErrorCode::UnknownVariant,
        );
    }
    #[test]
    fn adjacent_wrong_first_key() {
        assert_json_input_err_code::<
            AdjAnimal,
        >(
            b"{\"data\": null, \"type\": \"Cat\"}",
            kajit::context::ErrorCode::ExpectedTagKey,
        );
    }
    #[test]
    fn internal_struct_variant_reversed_fields() {
        assert_json_input_case::<
            IntAnimal,
        >(
            b"{\"type\": \"Dog\", \"good_boy\": true, \"name\": \"Rex\"}",
            IntAnimal::Dog {
                name: "Rex".into(),
                good_boy: true,
            },
        );
    }
    #[test]
    fn internal_unit_variant() {
        assert_json_input_case::<IntAnimal>(b"{\"type\": \"Cat\"}", IntAnimal::Cat);
    }
    #[test]
    fn internal_struct_variant() {
        assert_json_input_case::<
            IntAnimal,
        >(
            b"{\"type\": \"Dog\", \"name\": \"Rex\", \"good_boy\": true}",
            IntAnimal::Dog {
                name: "Rex".into(),
                good_boy: true,
            },
        );
    }
    #[test]
    fn internal_unknown_variant() {
        assert_json_input_err_code::<
            IntAnimal,
        >(b"{\"type\": \"Snake\"}", kajit::context::ErrorCode::UnknownVariant);
    }
    #[test]
    fn internal_wrong_first_key() {
        assert_json_input_err_code::<
            IntAnimal,
        >(
            b"{\"name\": \"Rex\", \"type\": \"Dog\", \"good_boy\": true}",
            kajit::context::ErrorCode::ExpectedTagKey,
        );
    }
    #[test]
    fn untagged_struct_reversed_keys() {
        assert_json_input_case::<
            UntaggedAnimal,
        >(
            b"{\"good_boy\": false, \"name\": \"Rex\"}",
            UntaggedAnimal::Dog {
                name: "Rex".into(),
                good_boy: false,
            },
        );
    }
    #[test]
    fn untagged_solver_key_order_independent() {
        assert_json_input_case::<
            UntaggedConfig,
        >(
            b"{\"db\": 0, \"host\": \"localhost\"}",
            UntaggedConfig::Redis {
                host: "localhost".into(),
                db: 0,
            },
        );
    }
    #[test]
    fn untagged_nested_key_order_independent() {
        assert_json_input_case::<
            ApiResponse,
        >(
            b"{\"data\": {\"items\": 5}, \"status\": 200}",
            ApiResponse::Success {
                status: 200,
                data: SuccessPayload { items: 5 },
            },
        );
    }
    #[test]
    fn option_some_scalar() {
        assert_json_input_case::<
            WithOptU32,
        >(b"{\"value\": 42}", WithOptU32 { value: Some(42) });
    }
    #[test]
    fn option_some_string() {
        assert_json_input_case::<
            WithOptStr,
        >(
            b"{\"name\": \"Alice\"}",
            WithOptStr {
                name: Some("Alice".into()),
            },
        );
    }
    #[test]
    fn option_some_struct() {
        assert_json_input_case::<
            WithOptAddr,
        >(
            b"{\"addr\": {\"city\": \"Portland\", \"zip\": 97201}}",
            WithOptAddr {
                addr: Some(Address {
                    city: "Portland".into(),
                    zip: 97201,
                }),
            },
        );
    }
    #[test]
    fn option_none_struct() {
        assert_json_input_case::<
            WithOptAddr,
        >(b"{\"addr\": null}", WithOptAddr { addr: None });
    }
    #[test]
    fn option_none_scalar() {
        assert_json_input_case::<
            WithOptU32,
        >(b"{\"value\": null}", WithOptU32 { value: None });
    }
    #[test]
    fn option_none_string() {
        assert_json_input_case::<
            WithOptStr,
        >(b"{\"name\": null}", WithOptStr { name: None });
    }
    #[test]
    fn option_reversed_keys() {
        assert_json_input_case::<
            MultiOpt,
        >(
            b"{\"c\": \"world\", \"b\": \"hello\", \"a\": null}",
            MultiOpt {
                a: None,
                b: "hello".into(),
                c: Some("world".into()),
            },
        );
    }
    #[test]
    fn rc_scalar() {
        assert_json_input_case::<
            RcScalar,
        >(
            b"{\"value\": 77}",
            RcScalar {
                value: std::rc::Rc::new(77),
            },
        );
    }
    #[test]
    fn rename_field() {
        assert_json_input_case::<
            RenameField,
        >(
            b"{\"user_name\": \"Alice\", \"age\": 30}",
            RenameField {
                name: "Alice".into(),
                age: 30,
            },
        );
    }
    #[test]
    fn rename_field_original_name_rejected() {
        assert_json_input_err::<RenameField>(b"{\"name\": \"Alice\", \"age\": 30}");
    }
    #[test]
    fn rename_all_camel_case() {
        assert_json_input_case::<
            CamelCaseStruct,
        >(
            b"{\"userName\": \"Bob\", \"birthYear\": 1990}",
            CamelCaseStruct {
                user_name: "Bob".into(),
                birth_year: 1990,
            },
        );
    }
    #[test]
    fn deny_unknown_fields_rejects() {
        assert_json_input_err_code::<
            Strict,
        >(b"{\"x\": 1, \"y\": 2, \"z\": 3}", kajit::context::ErrorCode::UnknownField);
    }
    #[test]
    fn deny_unknown_fields_allows_known() {
        assert_json_input_case::<Strict>(b"{\"x\": 1, \"y\": 2}", Strict { x: 1, y: 2 });
    }
    #[test]
    fn default_field_missing() {
        assert_json_input_case::<
            WithDefault,
        >(
            b"{\"name\": \"Alice\"}",
            WithDefault {
                name: "Alice".into(),
                score: 0,
            },
        );
    }
    #[test]
    fn default_field_present() {
        assert_json_input_case::<
            WithDefault,
        >(
            b"{\"name\": \"Alice\", \"score\": 99}",
            WithDefault {
                name: "Alice".into(),
                score: 99,
            },
        );
    }
    #[test]
    fn default_field_required_still_errors() {
        assert_json_input_err_code::<
            WithDefault,
        >(b"{\"score\": 50}", kajit::context::ErrorCode::MissingRequiredField);
    }
    #[test]
    fn default_string_field() {
        assert_json_input_case::<
            WithDefaultString,
        >(
            b"{\"value\": 42}",
            WithDefaultString {
                label: String::new(),
                value: 42,
            },
        );
    }
    #[test]
    fn container_default_empty_object() {
        assert_json_input_case::<AllDefault>(b"{}", AllDefault { x: 0, y: 0 });
    }
    #[test]
    fn container_default_partial() {
        assert_json_input_case::<AllDefault>(b"{\"x\": 5}", AllDefault { x: 5, y: 0 });
    }
    #[test]
    fn skip_field() {
        assert_json_input_case::<
            WithSkip,
        >(
            b"{\"name\": \"Alice\"}",
            WithSkip {
                name: "Alice".into(),
                cached: 0,
            },
        );
    }
    #[test]
    fn skip_field_in_input_treated_as_unknown() {
        assert_json_input_case::<
            WithSkip,
        >(
            b"{\"name\": \"Alice\", \"cached\": 99}",
            WithSkip {
                name: "Alice".into(),
                cached: 0,
            },
        );
    }
    #[test]
    fn skip_deserializing_field() {
        assert_json_input_case::<
            WithSkipDeser,
        >(
            b"{\"name\": \"Bob\"}",
            WithSkipDeser {
                name: "Bob".into(),
                internal: 0,
            },
        );
    }
    #[test]
    fn skip_with_custom_default() {
        assert_json_input_case::<
            SkipWithCustomDefault,
        >(
            b"{\"value\": 10}",
            SkipWithCustomDefault {
                value: 10,
                magic: 42,
            },
        );
    }
    #[test]
    fn string_escape_newline() {
        assert_json_input_case::<
            Friend,
        >(
            b"{\"age\": 1, \"name\": \"hello\\nworld\"}",
            Friend {
                age: 1,
                name: "hello\nworld".into(),
            },
        );
    }
    #[test]
    fn string_escape_tab() {
        assert_json_input_case::<
            Friend,
        >(
            b"{\"age\": 1, \"name\": \"hello\\tworld\"}",
            Friend {
                age: 1,
                name: "hello\tworld".into(),
            },
        );
    }
    #[test]
    fn string_escape_backslash() {
        assert_json_input_case::<
            Friend,
        >(
            b"{\"age\": 1, \"name\": \"hello\\\\world\"}",
            Friend {
                age: 1,
                name: "hello\\world".into(),
            },
        );
    }
    #[test]
    fn string_escape_quote() {
        assert_json_input_case::<
            Friend,
        >(
            b"{\"age\": 1, \"name\": \"hello\\\"world\"}",
            Friend {
                age: 1,
                name: "hello\"world".into(),
            },
        );
    }
    #[test]
    fn string_escape_all_simple() {
        assert_json_input_case::<
            Friend,
        >(
            b"{\"age\": 1, \"name\": \"a\\\"b\\\\c\\/d\\be\\ff\\ng\\rh\\ti\"}",
            Friend {
                age: 1,
                name: "a\"b\\c/d\x08e\x0Cf\ng\rh\ti".into(),
            },
        );
    }
    #[test]
    fn string_unicode_escape_bmp() {
        assert_json_input_case::<
            Friend,
        >(
            b"{\"age\": 1, \"name\": \"\\u0041lice\"}",
            Friend {
                age: 1,
                name: "Alice".into(),
            },
        );
    }
    #[test]
    fn string_unicode_escape_non_ascii() {
        assert_json_input_case::<
            Friend,
        >(
            b"{\"age\": 1, \"name\": \"caf\\u00E9\"}",
            Friend {
                age: 1,
                name: "caf\u{00E9}".into(),
            },
        );
    }
    #[test]
    fn string_unicode_surrogate_pair() {
        assert_json_input_case::<
            Friend,
        >(
            b"{\"age\": 1, \"name\": \"\\uD83D\\uDE00\"}",
            Friend {
                age: 1,
                name: "\u{1F600}".into(),
            },
        );
    }
    #[test]
    fn key_with_unicode_escape() {
        assert_json_input_case::<
            Friend,
        >(
            b"{\"age\": 42, \"na\\u006De\": \"Alice\"}",
            Friend {
                age: 42,
                name: "Alice".into(),
            },
        );
    }
    #[test]
    fn string_invalid_escape() {
        assert_json_input_err_code::<
            Friend,
        >(
            b"{\"age\": 1, \"name\": \"hello\\xworld\"}",
            kajit::context::ErrorCode::InvalidEscapeSequence,
        );
    }
    #[test]
    fn string_lone_high_surrogate() {
        assert_json_input_err_code::<
            Friend,
        >(
            b"{\"age\": 1, \"name\": \"\\uD800\"}",
            kajit::context::ErrorCode::InvalidEscapeSequence,
        );
    }
    #[test]
    fn string_truncated_unicode() {
        assert_json_input_err::<Friend>(b"{\"age\": 1, \"name\": \"\\u00\"}");
    }
    #[test]
    fn skip_value_with_unicode_escape() {
        assert_json_input_case::<
            Friend,
        >(
            b"{\"age\": 42, \"extra\": \"test\\uD83D\\uDE00end\", \"name\": \"Alice\"}",
            Friend {
                age: 42,
                name: "Alice".into(),
            },
        );
    }
    #[test]
    fn skip_value_with_backslash_escape() {
        assert_json_input_case::<
            Friend,
        >(
            b"{\"age\": 42, \"extra\": \"test\\n\\t\\\\end\", \"name\": \"Alice\"}",
            Friend {
                age: 42,
                name: "Alice".into(),
            },
        );
    }
    #[test]
    fn map_string_to_u32() {
        assert_json_input_case::<
            ConfigMap,
        >(
            b"{\"scores\": {\"alice\": 42, \"bob\": 7}}",
            ConfigMap {
                scores: std::collections::HashMap::from([
                    ("alice".to_string(), 42u32),
                    ("bob".to_string(), 7u32),
                ]),
            },
        );
    }
    #[test]
    fn map_empty() {
        assert_json_input_case::<
            ConfigMap,
        >(
            b"{\"scores\": {}}",
            ConfigMap {
                scores: std::collections::HashMap::new(),
            },
        );
    }
    #[test]
    fn map_string_to_string() {
        assert_json_input_case::<
            EnvMap,
        >(
            b"{\"vars\": {\"HOME\": \"/root\", \"PATH\": \"/usr/bin\"}}",
            EnvMap {
                vars: std::collections::HashMap::from([
                    ("HOME".to_string(), "/root".to_string()),
                    ("PATH".to_string(), "/usr/bin".to_string()),
                ]),
            },
        );
    }
    #[test]
    fn map_growth() {
        assert_json_input_case::<
            ConfigMap,
        >(
            b"{\"scores\": {\"a\": 1, \"b\": 2, \"c\": 3, \"d\": 4, \"e\": 5, \"f\": 6}}",
            ConfigMap {
                scores: std::collections::HashMap::from([
                    ("a".to_string(), 1u32),
                    ("b".to_string(), 2u32),
                    ("c".to_string(), 3u32),
                    ("d".to_string(), 4u32),
                    ("e".to_string(), 5u32),
                    ("f".to_string(), 6u32),
                ]),
            },
        );
    }
}
mod postreg {
    use super::*;
    #[test]
    fn vec_scalar_large_hotpath_asserts() {
        let (ir_text, ra_text, edits, disasm) = codegen_artifacts::<
            ScalarVec,
            _,
        >(&kajit::postcard::KajitPostcard);
        assert!(
            ir_text.contains("theta") || ir_text.contains("apply @"),
            "expected loop form (`theta`) or outlined loop body (`apply`) in IR"
        );
        assert!(ra_text.contains("branch_if"), "expected loop backedge in RA-MIR");
        assert!(
            ra_text.contains("call_intrinsic"),
            "expected intrinsic-heavy vec decode path in RA-MIR"
        );
        assert!(edits <= 128, "expected edit budget <= 128, got {edits}");
        assert!(! disasm.is_empty(), "expected non-empty disassembly artifact");
    }
}
