// @generated by xtask generate-ir-behavior-corpus. Do not edit manually.
use facet::Facet;
fn parse_case(ir: &str) -> kajit::ir::IrFunc {
    let registry = kajit::ir::IntrinsicRegistry::empty();
    kajit::ir_parse::parse_ir(ir, <u8 as Facet>::SHAPE, &registry).expect("text IR should parse")
}
fn run_exec(ir: &str, input: &[u8], with_passes: bool) -> u8 {
    let mut func = parse_case(ir);
    if with_passes {
        kajit::ir_passes::run_default_passes(&mut func);
    }
    let linear = kajit::linearize::linearize(&mut func);
    let dec = kajit::compile_decoder_linear_ir(&linear, false);
    kajit::deserialize::<u8>(&dec, input).expect("decoder should execute")
}
#[test]
fn ir_behavior_enum_like_gamma_tag_branch() {
    let ir = "\nlambda @0 (shape: \"u8\") {\n  region {\n    args: [%cs, %os]\n    n0 = BoundsCheck(1) [%cs:arg] -> [%cs]\n    n1 = ReadBytes(1) [%cs:n0] -> [v0, %cs]\n    n2 = Const(0x0) [] -> [v1]\n    n3 = CmpNe [v0, v1] -> [v2]\n    n4 = gamma [\n      pred: v2\n      in0: %cs:n1\n      in1: %os:arg\n    ] {\n      branch 0:\n        region {\n          args: [%cs, %os]\n          n5 = Const(0x2a) [] -> [v3]\n          results: [v3, %cs:arg, %os:arg]\n        }\n      branch 1:\n        region {\n          args: [%cs, %os]\n          n6 = Const(0x63) [] -> [v4]\n          results: [v4, %cs:arg, %os:arg]\n        }\n    } -> [v5, %cs, %os]\n    n7 = WriteToField(offset=0, W1) [v5, %os:n4] -> [%os]\n    results: [%cs:n4, %os:n7]\n  }\n}\n";
    {
        let input: &[u8] = &[0u8];
        let expected: u8 = 42u8;
        let baseline = run_exec(ir, input, false);
        let optimized = run_exec(ir, input, true);
        assert_eq!(baseline, expected, "baseline output mismatch");
        assert_eq!(optimized, expected, "optimized output mismatch");
        assert_eq!(
            optimized, baseline,
            "optimized and baseline outputs diverged"
        );
    }
    {
        let input: &[u8] = &[1u8];
        let expected: u8 = 99u8;
        let baseline = run_exec(ir, input, false);
        let optimized = run_exec(ir, input, true);
        assert_eq!(baseline, expected, "baseline output mismatch");
        assert_eq!(optimized, expected, "optimized output mismatch");
        assert_eq!(
            optimized, baseline,
            "optimized and baseline outputs diverged"
        );
    }
    {
        let input: &[u8] = &[255u8];
        let expected: u8 = 99u8;
        let baseline = run_exec(ir, input, false);
        let optimized = run_exec(ir, input, true);
        assert_eq!(baseline, expected, "baseline output mismatch");
        assert_eq!(optimized, expected, "optimized output mismatch");
        assert_eq!(
            optimized, baseline,
            "optimized and baseline outputs diverged"
        );
    }
}
#[test]
fn ir_behavior_theta_countdown_accumulate() {
    let ir = "\nlambda @0 (shape: \"u8\") {\n  region {\n    args: [%cs, %os]\n    n0 = BoundsCheck(1) [%cs:arg] -> [%cs]\n    n1 = ReadBytes(1) [%cs:n0] -> [v0, %cs]\n    n2 = Const(0x0) [] -> [v1]\n    n3 = Const(0x1) [] -> [v2]\n    n4 = theta [v0, v1, v2, %cs:n1, %os:arg] {\n      region {\n        args: [arg0, arg1, arg2, %cs, %os]\n        n5 = Add [arg1, arg2] -> [v3]\n        n6 = Sub [arg0, arg2] -> [v4]\n        results: [v4, v4, v3, arg2, %cs:arg, %os:arg]\n      }\n    } -> [v5, v6, v7, %cs, %os]\n    n8 = WriteToField(offset=0, W1) [v6, %os:n4] -> [%os]\n    results: [%cs:n4, %os:n8]\n  }\n}\n";
    {
        let input: &[u8] = &[1u8];
        let expected: u8 = 1u8;
        let baseline = run_exec(ir, input, false);
        let optimized = run_exec(ir, input, true);
        assert_eq!(baseline, expected, "baseline output mismatch");
        assert_eq!(optimized, expected, "optimized output mismatch");
        assert_eq!(
            optimized, baseline,
            "optimized and baseline outputs diverged"
        );
    }
    {
        let input: &[u8] = &[3u8];
        let expected: u8 = 3u8;
        let baseline = run_exec(ir, input, false);
        let optimized = run_exec(ir, input, true);
        assert_eq!(baseline, expected, "baseline output mismatch");
        assert_eq!(optimized, expected, "optimized output mismatch");
        assert_eq!(
            optimized, baseline,
            "optimized and baseline outputs diverged"
        );
    }
    {
        let input: &[u8] = &[7u8];
        let expected: u8 = 7u8;
        let baseline = run_exec(ir, input, false);
        let optimized = run_exec(ir, input, true);
        assert_eq!(baseline, expected, "baseline output mismatch");
        assert_eq!(optimized, expected, "optimized output mismatch");
        assert_eq!(
            optimized, baseline,
            "optimized and baseline outputs diverged"
        );
    }
}
#[test]
fn ir_behavior_and_cmpne_branch_surface() {
    let ir = "\nlambda @0 (shape: \"u8\") {\n  region {\n    args: [%cs, %os]\n    n0 = BoundsCheck(2) [%cs:arg] -> [%cs]\n    n1 = ReadBytes(1) [%cs:n0] -> [v0, %cs]\n    n2 = ReadBytes(1) [%cs:n1] -> [v1, %cs]\n    n3 = Const(0x0) [] -> [v2]\n    n4 = CmpNe [v0, v2] -> [v3]\n    n5 = CmpNe [v1, v2] -> [v4]\n    n6 = And [v3, v4] -> [v5]\n    n7 = gamma [\n      pred: v5\n      in0: %cs:n2\n      in1: %os:arg\n    ] {\n      branch 0:\n        region {\n          args: [%cs, %os]\n          n8 = Const(0x4) [] -> [v6]\n          results: [v6, %cs:arg, %os:arg]\n        }\n      branch 1:\n        region {\n          args: [%cs, %os]\n          n9 = Const(0x9) [] -> [v7]\n          results: [v7, %cs:arg, %os:arg]\n        }\n    } -> [v8, %cs, %os]\n    n10 = WriteToField(offset=0, W1) [v8, %os:n7] -> [%os]\n    results: [%cs:n7, %os:n10]\n  }\n}\n";
    {
        let input: &[u8] = &[1u8, 1u8];
        let expected: u8 = 9u8;
        let baseline = run_exec(ir, input, false);
        let optimized = run_exec(ir, input, true);
        assert_eq!(baseline, expected, "baseline output mismatch");
        assert_eq!(optimized, expected, "optimized output mismatch");
        assert_eq!(
            optimized, baseline,
            "optimized and baseline outputs diverged"
        );
    }
    {
        let input: &[u8] = &[1u8, 0u8];
        let expected: u8 = 4u8;
        let baseline = run_exec(ir, input, false);
        let optimized = run_exec(ir, input, true);
        assert_eq!(baseline, expected, "baseline output mismatch");
        assert_eq!(optimized, expected, "optimized output mismatch");
        assert_eq!(
            optimized, baseline,
            "optimized and baseline outputs diverged"
        );
    }
    {
        let input: &[u8] = &[0u8, 1u8];
        let expected: u8 = 4u8;
        let baseline = run_exec(ir, input, false);
        let optimized = run_exec(ir, input, true);
        assert_eq!(baseline, expected, "baseline output mismatch");
        assert_eq!(optimized, expected, "optimized output mismatch");
        assert_eq!(
            optimized, baseline,
            "optimized and baseline outputs diverged"
        );
    }
    {
        let input: &[u8] = &[0u8, 0u8];
        let expected: u8 = 4u8;
        let baseline = run_exec(ir, input, false);
        let optimized = run_exec(ir, input, true);
        assert_eq!(baseline, expected, "baseline output mismatch");
        assert_eq!(optimized, expected, "optimized output mismatch");
        assert_eq!(
            optimized, baseline,
            "optimized and baseline outputs diverged"
        );
    }
}
#[test]
fn ir_behavior_boundscheck_peek_read_chain() {
    let ir = "\nlambda @0 (shape: \"u8\") {\n  region {\n    args: [%cs, %os]\n    n0 = BoundsCheck(1) [%cs:arg] -> [%cs]\n    n1 = PeekByte [%cs:n0] -> [v0, %cs]\n    n2 = BoundsCheck(1) [%cs:n1] -> [%cs]\n    n3 = ReadBytes(1) [%cs:n2] -> [v1, %cs]\n    n4 = WriteToField(offset=0, W1) [v1, %os:arg] -> [%os]\n    results: [%cs:n3, %os:n4]\n  }\n}\n";
    {
        let input: &[u8] = &[7u8];
        let expected: u8 = 7u8;
        let baseline = run_exec(ir, input, false);
        let optimized = run_exec(ir, input, true);
        assert_eq!(baseline, expected, "baseline output mismatch");
        assert_eq!(optimized, expected, "optimized output mismatch");
        assert_eq!(
            optimized, baseline,
            "optimized and baseline outputs diverged"
        );
    }
    {
        let input: &[u8] = &[200u8];
        let expected: u8 = 200u8;
        let baseline = run_exec(ir, input, false);
        let optimized = run_exec(ir, input, true);
        assert_eq!(baseline, expected, "baseline output mismatch");
        assert_eq!(optimized, expected, "optimized output mismatch");
        assert_eq!(
            optimized, baseline,
            "optimized and baseline outputs diverged"
        );
    }
}
