// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#![allow(dead_code, unused_variables)]
use super::*;

#[derive(Default)]
struct ErrorSink(Vec<String>);

impl ErrorSink {
    fn push(&mut self, error: String) {
        self.0.push(error);
    }
    fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
    fn into_vec(self) -> Vec<String> {
        self.0
    }
}

#[derive(Default)]
struct ValidationContext {}
fn validate_block(value: &Block, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    for value in value.statements.iter() {
        validate_stmt(value, ctx, errors);
    }
}
fn validate_expr(value: &Expr, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    match value {
        Expr::Binary {
            lhs, op, prov, rhs, ..
        } => {
            validate_expr(lhs, ctx, errors);
            validate_expr(rhs, ctx, errors);
        }
        Expr::Call {
            args, callee, prov, ..
        } => {
            for value in args.iter() {
                validate_expr(value, ctx, errors);
            }
        }
        Expr::Field {
            base, field, prov, ..
        } => {
            validate_expr(base, ctx, errors);
        }
        Expr::Literal { prov, value, .. } => {
            let _ = (ctx, errors);
        }
        Expr::Local { name, prov, .. } => {
            let _ = (ctx, errors);
        }
    }
}
fn validate_function(value: &Function, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    validate_block(&value.body, ctx, errors);
    if let Some(value) = value.docs.as_ref() {}
    for value in value.locals.iter() {
        validate_local(value, ctx, errors);
    }
    for value in value.params.iter() {
        validate_param(value, ctx, errors);
    }
}
fn validate_local(value: &Local, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    let _ = (value, ctx, errors);
}
fn validate_module(value: &Module, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    if let Some(value) = value.docs.as_ref() {}
    for value in value.functions.iter() {
        validate_function(value, ctx, errors);
    }
    for value in value.type_defs.iter() {
        validate_type_def(value, ctx, errors);
    }
}
fn validate_param(value: &Param, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    let _ = (value, ctx, errors);
}
fn validate_place(value: &Place, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    match value {
        Place::Field {
            base, field, prov, ..
        } => {
            validate_place(base, ctx, errors);
        }
        Place::Local { name, prov, .. } => {
            let _ = (ctx, errors);
        }
    }
}
fn validate_stmt(value: &Stmt, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    match value {
        Stmt::Assign {
            place, prov, value, ..
        } => {
            validate_place(place, ctx, errors);
            validate_expr(value, ctx, errors);
        }
        Stmt::Expr { prov, value, .. } => {
            validate_expr(value, ctx, errors);
        }
        Stmt::If {
            condition,
            r#else,
            prov,
            then,
            ..
        } => {
            validate_expr(condition, ctx, errors);
            if let Some(value) = r#else.as_ref() {
                validate_block(value, ctx, errors);
            }
            validate_block(then, ctx, errors);
        }
        Stmt::Init {
            place, prov, value, ..
        } => {
            validate_place(place, ctx, errors);
            validate_expr(value, ctx, errors);
        }
        Stmt::Return { prov, value, .. } => {
            if let Some(value) = value.as_ref() {
                validate_expr(value, ctx, errors);
            }
        }
    }
}
fn validate_type_def(value: &TypeDef, ctx: &mut ValidationContext, errors: &mut ErrorSink) {
    if let Some(value) = value.docs.as_ref() {}
    for value in value.params.iter() {}
}
pub fn validate_root(root: &Module) -> Result<(), String> {
    let mut ctx = ValidationContext::default();
    let mut errors = ErrorSink::default();
    validate_module(root, &mut ctx, &mut errors);
    let errors = errors.into_vec();
    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors.join("\n"))
    }
}
pub fn validate_root_text(source: &str) -> Result<(), String> {
    let root = parse_root_text(source)?;
    validate_root(&root)
}
