[package]
name = "kajit-foundation"
version = "0.1.0"
edition = "2024"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
facet = "0.44"
facet-styx = "3.0.0"
prettyplease = "0.2"
styx-tree = { version = "3.0.0", features = ["facet"] }
syn = { version = "2", features = ["full"] }

[dev-dependencies]
tempfile = "3"
