[package]
name = "kajit-foundation"
version = "0.1.0"
edition = "2024"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
facet = { workspace = true, features = ["indexmap"] }
facet-styx = { workspace = true }
indexmap = { workspace = true }
prettyplease = { workspace = true }
styx-tree = { workspace = true }
syn = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
