experimental = ["wrapper-scripts"]

[profile.default]
slow-timeout = { period = "5s", terminate-after = 2 }

[scripts.wrapper.valgrind]
command = ['valgrind', '-q', '--error-exitcode=1']

[[profile.valgrind.scripts]]
platform = 'cfg(target_os = "linux")'
run-wrapper = 'valgrind'
