//! Deser/ser cases

use std::fmt::Write as _;

use crate::Case;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

pub(crate) fn types_rs() -> TokenStream {
    quote! {
        use serde::{Serialize, Deserialize};

        #[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
        struct Friend {
            age: u32,
            name: String,
        }

        #[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
        struct Address {
            city: String,
            zip: u32,
        }

        #[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
        struct Person {
            name: String,
            age: u32,
            address: Address,
        }

        #[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
        struct Inner {
            x: u32,
        }

        #[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
        struct Middle {
            inner: Inner,
            y: u32,
        }

        #[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
        struct Outer {
            middle: Middle,
            z: u32,
        }

        #[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
        struct AllIntegers {
            a_u8: u8,
            a_u16: u16,
            a_u32: u32,
            a_u64: u64,
            a_i8: i8,
            a_i16: i16,
            a_i32: i32,
            a_i64: i64,
        }

        #[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
        struct BoolField {
            value: bool,
        }

        #[derive(Debug, PartialEq, Serialize, Deserialize, Facet)]
        struct ScalarVec {
            values: Vec<u32>,
        }

        type Pair = (u32, String);
    }
}

pub(crate) fn cases() -> Vec<Case> {
    vec![
        Case {
            name: "flat_struct",
            value: quote!(Friend {
                age: 42,
                name: "Alice".into()
            }),
        },
        Case {
            name: "nested_struct",
            value: quote!(Person {
                name: "Alice".into(),
                age: 30,
                address: Address {
                    city: "Portland".into(),
                    zip: 97201
                }
            }),
        },
        Case {
            name: "deep_struct",
            value: quote!(Outer {
                middle: Middle {
                    inner: Inner { x: 1 },
                    y: 2
                },
                z: 3
            }),
        },
        Case {
            name: "all_integers",
            value: quote!(AllIntegers {
                a_u8: 255,
                a_u16: 65535,
                a_u32: 1_000_000,
                a_u64: 1_000_000_000_000,
                a_i8: -128,
                a_i16: -32768,
                a_i32: -1_000_000,
                a_i64: -1_000_000_000_000
            }),
        },
        Case {
            name: "bool_field",
            value: quote!(BoolField { value: true }),
        },
        Case {
            name: "tuple_pair",
            value: quote!((42u32, "Alice".to_string())),
        },
        Case {
            name: "vec_scalar_small",
            value: quote!(ScalarVec {
                values: (0..16).map(|i| i as u32).collect()
            }),
        },
        Case {
            name: "vec_scalar_large",
            value: quote!(ScalarVec {
                values: (0..2048).map(|i| i as u32).collect()
            }),
        },
    ]
}

fn types_rs_pretty() -> String {
    let file: syn::File =
        syn::parse2(types_rs()).expect("types_rs quote output should parse as a Rust file");
    prettyplease::unparse(&file)
}

pub(crate) fn render_bench_file() -> String {
    let cases = cases();
    let mut out = String::new();
    out.push_str("// @generated by xtask generate-synthetic. Do not edit manually.\n");
    out.push_str("#[path = \"harness.rs\"]\nmod harness;\n\n");
    out.push_str("#[macro_use]\n#[path = \"common/bench_macros.rs\"]\nmod bench_macros;\n\n");
    out.push_str("use facet::Facet;\n\n");
    out.push_str(types_rs_pretty().trim());
    out.push_str("\n\nfn main() {\n");
    out.push_str("    let mut v: Vec<harness::Bench> = Vec::new();\n\n");
    for case in &cases {
        writeln!(
            out,
            "    bench!(v, {}, {}, +ser, +ir);",
            case.name, case.value
        )
        .unwrap();
    }
    out.push_str("\n    harness::run_benchmarks(v);\n}\n");
    out
}

pub(crate) fn render_test_file() -> String {
    let cases = cases();
    let types = types_rs();
    let json_tests: Vec<TokenStream> = cases
        .iter()
        .map(|case| {
            let test_name = format_ident!("generated_json_{}", case.name);
            let value = case.value.clone();
            quote! {
                #[test]
                fn #test_name() {
                    let value = #value;
                    assert_json_case(value);
                }
            }
        })
        .collect();
    let postcard_tests: Vec<TokenStream> = cases
        .iter()
        .map(|case| {
            let test_name = format_ident!("generated_postcard_{}", case.name);
            let value = case.value.clone();
            let case_name = case.name;
            quote! {
                #[test]
                fn #test_name() {
                    let value = #value;
                    assert_ir_ra_snapshots("postcard", #case_name, &kajit::postcard::KajitPostcard, &value);
                    assert_postcard_case(value, true);
                }
            }
        })
        .collect();
    let file_tokens = quote! {
        use facet::Facet;

        #types

        fn assert_json_case<T>(value: T)
        where
            for<'input> T: Facet<'input> + serde::Serialize + serde::de::DeserializeOwned + PartialEq + std::fmt::Debug,
        {
            let encoded = serde_json::to_string(&value).unwrap();
            let expected: T = serde_json::from_str(&encoded).unwrap();
            let decoder = kajit::compile_decoder_legacy(T::SHAPE, &kajit::json::KajitJson);
            let got: T = kajit::from_str(&decoder, &encoded).unwrap();
            assert_eq!(got, expected);
        }

        fn assert_postcard_case<T>(value: T, with_ir: bool)
        where
            for<'input> T: Facet<'input> + serde::Serialize + serde::de::DeserializeOwned + PartialEq + std::fmt::Debug,
        {
            let encoded = postcard::to_allocvec(&value).unwrap();
            let expected: T = postcard::from_bytes(&encoded).unwrap();
            let legacy = kajit::compile_decoder_legacy(T::SHAPE, &kajit::postcard::KajitPostcard);
            let legacy_out: T = kajit::deserialize(&legacy, &encoded).unwrap();
            assert_eq!(legacy_out, expected);
            if with_ir {
                let ir = kajit::compile_decoder_via_ir(T::SHAPE, &kajit::postcard::KajitPostcard);
                let ir_out: T = kajit::deserialize(&ir, &encoded).unwrap();
                assert_eq!(ir_out, expected);
            }
        }

        fn assert_ir_ra_snapshots<T>(
            format_label: &str,
            case: &str,
            decoder: &dyn kajit::format::IrDecoder,
            _marker: &T,
        )
        where
            for<'input> T: Facet<'input>,
        {
            let shape = T::SHAPE;
            let (ir_text, ra_text) = kajit::debug_ir_and_ra_mir_text(shape, decoder);
            insta::assert_snapshot!(
                format!(
                    "generated_rvsdg_{}_{}_{}",
                    format_label,
                    case,
                    std::env::consts::ARCH
                ),
                ir_text
            );
            insta::assert_snapshot!(
                format!(
                    "generated_ra_mir_{}_{}_{}",
                    format_label,
                    case,
                    std::env::consts::ARCH
                ),
                ra_text
            );
        }

        #(#json_tests)*
        #(#postcard_tests)*
    };
    let file: syn::File =
        syn::parse2(file_tokens).expect("generated synthetic test file should parse");
    let mut out =
        String::from("// @generated by xtask generate-synthetic. Do not edit manually.\n");
    out.push_str(&prettyplease::unparse(&file));
    out
}
