//! IR optimization test cases.

use std::fmt::Write as _;

use crate::IrOptCase;

pub(crate) const IR_OPT_CASES: &[IrOptCase] = &[
    IrOptCase {
        name: "theta_invariant_tree_hoist",
        ir: r#"
lambda @0 (shape: "u8") {
  region {
    args: [%cs, %os]
    n0 = Const(0x4) [] -> [v0]
    n1 = Const(0x1) [] -> [v1]
    n2 = theta [v0, v1, %cs:arg, %os:arg] {
      region {
        args: [arg0, arg1, %cs, %os]
        n3 = Const(0x7) [] -> [v2]
        n4 = Const(0x3) [] -> [v3]
        n5 = Add [v2, v3] -> [v4]
        n6 = Xor [v4, v3] -> [v5]
        n7 = Sub [arg0, arg1] -> [v6]
        n8 = Add [v5, v6] -> [v7]
        results: [v6, v6, arg1, %cs:arg, %os:arg]
      }
    } -> [v8, v9, %cs, %os]
    n9 = WriteToField(offset=0, W1) [v8, %os:n2] -> [%os]
    results: [%cs:n2, %os:n9]
  }
}
"#,
        must_not_contain_after: &[
            "n3 = Const(0x7) [] -> [v2]",
            "n4 = Const(0x3) [] -> [v3]",
            "n5 = Add [v2, v3] -> [v4]",
            "n6 = Xor [v4, v3] -> [v5]",
        ],
        must_contain_after: &[],
        input: &[],
    },
    IrOptCase {
        name: "theta_loop_variant_not_hoisted",
        ir: r#"
lambda @0 (shape: "u8") {
  region {
    args: [%cs, %os]
    n0 = Const(0x4) [] -> [v0]
    n1 = Const(0x1) [] -> [v1]
    n2 = theta [v0, v1, %cs:arg, %os:arg] {
      region {
        args: [arg0, arg1, %cs, %os]
        n3 = Add [arg0, arg1] -> [v2]
        n4 = Sub [arg0, arg1] -> [v3]
        results: [v3, v3, arg1, %cs:arg, %os:arg]
      }
    } -> [v4, v5, %cs, %os]
    n5 = WriteToField(offset=0, W1) [v4, %os:n2] -> [%os]
    results: [%cs:n2, %os:n5]
  }
}
"#,
        must_not_contain_after: &[],
        must_contain_after: &["n3 = Add [arg0, arg1] -> [v2]"],
        input: &[],
    },
    IrOptCase {
        name: "bounds_check_chain_coalesce",
        ir: r#"
lambda @0 (shape: "u8") {
  region {
    args: [%cs, %os]
    n0 = BoundsCheck(1) [%cs:arg] -> [%cs]
    n1 = PeekByte [%cs:n0] -> [v0, %cs]
    n2 = BoundsCheck(1) [%cs:n1] -> [%cs]
    n3 = ReadBytes(1) [%cs:n2] -> [v1, %cs]
    n4 = WriteToField(offset=0, W1) [v1, %os:arg] -> [%os]
    results: [%cs:n3, %os:n4]
  }
}
"#,
        must_not_contain_after: &["n2 = BoundsCheck(1) [%cs:n1] -> [%cs]"],
        must_contain_after: &["BoundsCheck(1) [%cs:arg] -> [%cs]"],
        input: &[7],
    },
];

pub(crate) fn render_ir_opt_test_file() -> String {
    let mut out = String::new();
    out.push_str("// @generated by xtask generate-ir-opt-corpus. Do not edit manually.\n");
    out.push_str("use facet::Facet;\n\n");
    out.push_str("fn parse_case(ir: &str) -> kajit::ir::IrFunc {\n");
    out.push_str("    let registry = kajit::ir::IntrinsicRegistry::empty();\n");
    out.push_str("    kajit::ir_parse::parse_ir(ir, <u8 as Facet>::SHAPE, &registry)\n");
    out.push_str("        .expect(\"text IR should parse\")\n");
    out.push_str("}\n\n");
    out.push_str("fn run_pass(ir: &str) -> (String, String) {\n");
    out.push_str("    let mut func = parse_case(ir);\n");
    out.push_str("    let before = format!(\"{func}\");\n");
    out.push_str("    kajit::ir_passes::run_default_passes(&mut func);\n");
    out.push_str("    let after = format!(\"{func}\");\n");
    out.push_str("    (before, after)\n");
    out.push_str("}\n\n");
    out.push_str("fn run_exec(ir: &str, input: &[u8]) -> u8 {\n");
    out.push_str("    let mut func = parse_case(ir);\n");
    out.push_str("    let linear = kajit::linearize::linearize(&mut func);\n");
    out.push_str("    let dec = kajit::compile_decoder_linear_ir(&linear, false);\n");
    out.push_str("    kajit::deserialize::<u8>(&dec, input).expect(\"decoder should execute\")\n");
    out.push_str("}\n\n");

    for case in IR_OPT_CASES {
        let test_name_snapshot = format!("ir_opt_snapshot_{}", case.name);
        let test_name_asserts = format!("ir_opt_asserts_{}", case.name);
        let test_name_exec = format!("ir_opt_exec_{}", case.name);

        write!(
            out,
            "#[test]\nfn {test_name_snapshot}() {{\n    let (before, after) = run_pass(r#\"{ir}\"#);\n    insta::assert_snapshot!(\"generated_ir_opt_before_{name}\", before);\n    insta::assert_snapshot!(\"generated_ir_opt_after_{name}\", after);\n}}\n\n",
            test_name_snapshot = test_name_snapshot,
            ir = case.ir,
            name = case.name
        )
        .unwrap();

        write!(
            out,
            "#[test]\nfn {test_name_asserts}() {{\n    let (_before, after) = run_pass(r#\"{ir}\"#);\n",
            test_name_asserts = test_name_asserts,
            ir = case.ir
        )
        .unwrap();
        for needle in case.must_not_contain_after {
            writeln!(
                out,
                "    assert!(!after.contains(r#\"{needle}\"#), \"expected to hoist/remove: {{}}\", r#\"{needle}\"#);",
                needle = needle
            )
            .unwrap();
        }
        for needle in case.must_contain_after {
            writeln!(
                out,
                "    assert!(after.contains(r#\"{needle}\"#), \"expected to keep/preserve: {{}}\", r#\"{needle}\"#);",
                needle = needle
            )
            .unwrap();
        }
        out.push_str("}\n\n");

        out.push_str(&format!(
            "#[test]\nfn {test_name_exec}() {{\n",
            test_name_exec = test_name_exec
        ));
        out.push_str("    let before_out = run_exec(r#\"");
        out.push_str(case.ir);
        out.push_str("\"#, &[");
        for (idx, b) in case.input.iter().enumerate() {
            if idx > 0 {
                out.push_str(", ");
            }
            out.push_str(&b.to_string());
        }
        out.push_str("]);\n");
        out.push_str("    let mut optimized = parse_case(r#\"");
        out.push_str(case.ir);
        out.push_str("\"#);\n");
        out.push_str("    kajit::ir_passes::run_default_passes(&mut optimized);\n");
        out.push_str("    let linear = kajit::linearize::linearize(&mut optimized);\n");
        out.push_str("    let dec = kajit::compile_decoder_linear_ir(&linear, false);\n");
        out.push_str("    let after_out = kajit::deserialize::<u8>(&dec, &[");
        for (idx, b) in case.input.iter().enumerate() {
            if idx > 0 {
                out.push_str(", ");
            }
            out.push_str(&b.to_string());
        }
        out.push_str("]).expect(\"optimized decoder should execute\");\n");
        out.push_str("    assert_eq!(after_out, before_out);\n");
        out.push_str("}\n\n");
    }

    out
}
