// IR post-register allocation cases

use std::fmt::Write as _;

use crate::IrPostRegCase;

pub(crate) const IR_POSTREG_CASES: &[IrPostRegCase] = &[
    IrPostRegCase {
        name: "cmpne_gamma_branch",
        ir: r#"
lambda @0 (shape: "u8") {
  region {
    args: [%cs, %os]
    n0 = BoundsCheck(1) [%cs:arg] -> [%cs]
    n1 = ReadBytes(1) [%cs:n0] -> [v0, %cs]
    n2 = Const(0x0) [] -> [v1]
    n3 = CmpNe [v0, v1] -> [v2]
    n4 = gamma [
      pred: v2
      in0: %cs:n1
      in1: %os:arg
    ] {
      branch 0:
        region {
          args: [%cs, %os]
          n5 = Const(0x3) [] -> [v3]
          results: [v3, %cs:arg, %os:arg]
        }
      branch 1:
        region {
          args: [%cs, %os]
          n6 = Const(0x7) [] -> [v4]
          results: [v4, %cs:arg, %os:arg]
        }
    } -> [v5, %cs, %os]
    n7 = WriteToField(offset=0, W1) [v5, %os:n4] -> [%os]
    results: [%cs:n4, %os:n7]
  }
}
"#,
        must_contain_linear: &["CmpNe", "br_zero"],
        max_total_edits: 64,
        input: &[1],
        expected: 7,
    },
    IrPostRegCase {
        name: "and_cmpne_gamma_branch",
        ir: r#"
lambda @0 (shape: "u8") {
  region {
    args: [%cs, %os]
    n0 = BoundsCheck(2) [%cs:arg] -> [%cs]
    n1 = ReadBytes(1) [%cs:n0] -> [v0, %cs]
    n2 = ReadBytes(1) [%cs:n1] -> [v1, %cs]
    n3 = Const(0x0) [] -> [v2]
    n4 = CmpNe [v0, v2] -> [v3]
    n5 = CmpNe [v1, v2] -> [v4]
    n6 = And [v3, v4] -> [v5]
    n7 = gamma [
      pred: v5
      in0: %cs:n2
      in1: %os:arg
    ] {
      branch 0:
        region {
          args: [%cs, %os]
          n8 = Const(0x4) [] -> [v6]
          results: [v6, %cs:arg, %os:arg]
        }
      branch 1:
        region {
          args: [%cs, %os]
          n9 = Const(0x9) [] -> [v7]
          results: [v7, %cs:arg, %os:arg]
        }
    } -> [v8, %cs, %os]
    n10 = WriteToField(offset=0, W1) [v8, %os:n7] -> [%os]
    results: [%cs:n7, %os:n10]
  }
}
"#,
        must_contain_linear: &["And", "CmpNe", "br_zero"],
        max_total_edits: 96,
        input: &[1, 1],
        expected: 9,
    },
    IrPostRegCase {
        name: "theta_then_gamma_edit_budget",
        ir: r#"
lambda @0 (shape: "u8") {
  region {
    args: [%cs, %os]
    n0 = Const(0x3) [] -> [v0]
    n1 = Const(0x1) [] -> [v1]
    n2 = theta [v0, v1, %cs:arg, %os:arg] {
      region {
        args: [arg0, arg1, %cs, %os]
        n3 = Sub [arg0, arg1] -> [v2]
        results: [v2, v2, arg1, %cs:arg, %os:arg]
      }
    } -> [v3, v4, %cs, %os]
    n4 = gamma [
      pred: v3
      in0: %cs:n2
      in1: %os:n2
    ] {
      branch 0:
        region {
          args: [%cs, %os]
          n5 = Const(0xb) [] -> [v5]
          results: [v5, %cs:arg, %os:arg]
        }
      branch 1:
        region {
          args: [%cs, %os]
          n6 = Const(0x16) [] -> [v6]
          results: [v6, %cs:arg, %os:arg]
        }
    } -> [v7, %cs, %os]
    n8 = WriteToField(offset=0, W1) [v7, %os:n4] -> [%os]
    results: [%cs:n4, %os:n8]
  }
}
"#,
        must_contain_linear: &["br_if", "br_zero"],
        max_total_edits: 128,
        input: &[],
        expected: 11,
    },
];

pub(crate) fn render_ir_postreg_test_file() -> String {
    let mut out = String::new();
    out.push_str("// @generated by xtask generate-ir-postreg-corpus. Do not edit manually.\n");
    out.push_str("use facet::Facet;\n\n");
    out.push_str("fn parse_case(ir: &str) -> kajit::ir::IrFunc {\n");
    out.push_str("    let registry = kajit::ir::IntrinsicRegistry::empty();\n");
    out.push_str("    kajit::ir_parse::parse_ir(ir, <u8 as Facet>::SHAPE, &registry)\n");
    out.push_str("        .expect(\"text IR should parse\")\n");
    out.push_str("}\n\n");
    out.push_str("fn run_exec(ir: &str, input: &[u8], with_passes: bool) -> u8 {\n");
    out.push_str("    let mut func = parse_case(ir);\n");
    out.push_str("    if with_passes {\n");
    out.push_str("        kajit::ir_passes::run_default_passes(&mut func);\n");
    out.push_str("    }\n");
    out.push_str("    let linear = kajit::linearize::linearize(&mut func);\n");
    out.push_str("    let dec = kajit::compile_decoder_linear_ir(&linear, false);\n");
    out.push_str("    kajit::deserialize::<u8>(&dec, input).expect(\"decoder should execute\")\n");
    out.push_str("}\n\n");
    out.push_str("fn postreg_artifacts(ir: &str) -> (String, String, usize) {\n");
    out.push_str("    let mut func = parse_case(ir);\n");
    out.push_str("    kajit::ir_passes::run_default_passes(&mut func);\n");
    out.push_str("    let linear = kajit::linearize::linearize(&mut func);\n");
    out.push_str("    let linear_text = format!(\"{linear}\");\n");
    out.push_str("    let ra = kajit::regalloc_mir::lower_linear_ir(&linear);\n");
    out.push_str("    let ra_text = format!(\"{ra}\");\n");
    out.push_str("    let alloc = kajit::regalloc_engine::allocate_program(&ra)\n");
    out.push_str("        .expect(\"regalloc should allocate post-reg corpus case\");\n");
    out.push_str("    let edits: usize = alloc.functions.iter().map(|f| f.edits.len()).sum();\n");
    out.push_str("    (linear_text, ra_text, edits)\n");
    out.push_str("}\n\n");

    for case in IR_POSTREG_CASES {
        let snap_test = format!("ir_postreg_snapshot_{}", case.name);
        let assert_test = format!("ir_postreg_asserts_{}", case.name);
        let exec_test = format!("ir_postreg_exec_{}", case.name);

        write!(
            out,
            "#[test]\nfn {snap_test}() {{\n    let (linear, ra, edits) = postreg_artifacts(r#\"{ir}\"#);\n    insta::assert_snapshot!(\"generated_ir_postreg_linear_{name}\", linear);\n    insta::assert_snapshot!(\"generated_ir_postreg_ra_{name}\", ra);\n    insta::assert_snapshot!(\"generated_ir_postreg_edits_{name}\", format!(\"{{edits}}\"));\n}}\n\n",
            snap_test = snap_test,
            ir = case.ir,
            name = case.name
        )
        .unwrap();

        write!(
            out,
            "#[test]\nfn {assert_test}() {{\n    let (linear, _ra, edits) = postreg_artifacts(r#\"{ir}\"#);\n    assert!(edits <= {max_edits}, \"expected edit budget <= {max_edits}, got {{edits}}\");\n",
            assert_test = assert_test,
            ir = case.ir,
            max_edits = case.max_total_edits
        )
        .unwrap();
        for needle in case.must_contain_linear {
            writeln!(
                out,
                "    assert!(linear.contains(r#\"{needle}\"#), \"expected linear artifact to contain: {{}}\", r#\"{needle}\"#);",
                needle = needle
            )
            .unwrap();
        }
        out.push_str("}\n\n");

        out.push_str(&format!(
            "#[test]\nfn {exec_test}() {{\n",
            exec_test = exec_test
        ));
        out.push_str("    let before = run_exec(r#\"");
        out.push_str(case.ir);
        out.push_str("\"#, &[");
        for (idx, b) in case.input.iter().enumerate() {
            if idx > 0 {
                out.push_str(", ");
            }
            out.push_str(&b.to_string());
        }
        out.push_str("], false);\n");
        out.push_str("    let after = run_exec(r#\"");
        out.push_str(case.ir);
        out.push_str("\"#, &[");
        for (idx, b) in case.input.iter().enumerate() {
            if idx > 0 {
                out.push_str(", ");
            }
            out.push_str(&b.to_string());
        }
        out.push_str("], true);\n");
        out.push_str(&format!(
            "    assert_eq!(after, {}u8, \"optimized output mismatch against expected\");\n",
            case.expected
        ));
        out.push_str(
            "    assert_eq!(after, before, \"optimized and baseline outputs diverged\");\n",
        );
        out.push_str("}\n\n");
    }

    out
}
