// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

//! Pilot schema for the ASM representation family.
/// Preserved doc-comment lines collected from leading `///` comments.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct DocBlock(pub Vec<String>);

pub use kajit_types::{Prov, Span};

/// A decimal immediate value in canonical ASM text.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Imm(pub String);

/// A symbolic label name.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct LabelName(pub String);

/// AArch64 labels and instructions.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum A64Item {
    /// Add an immediate to a register.
    AddImm {
        /// Immediate value.
        imm: Imm,

        /// Source provenance for the item.
        prov: Prov,

        /// Destination register.
        rd: Box<A64Reg>,

        /// Base register.
        rn: Box<A64Reg>,
    },

    /// Branch to a symbolic label.
    B {
        /// Source provenance for the item.
        prov: Prov,

        /// Branch target label.
        target: LabelName,
    },

    /// A symbolic label definition.
    Label {
        /// Label name.
        name: LabelName,

        /// Source provenance for the item.
        prov: Prov,
    },

    /// Move a register into another register.
    Mov {
        /// Source provenance for the item.
        prov: Prov,

        /// Destination register.
        rd: Box<A64Reg>,

        /// Source register.
        rm: Box<A64Reg>,
    },

    /// Move an immediate into a register.
    Movz {
        /// Immediate value.
        imm: Imm,

        /// Source provenance for the item.
        prov: Prov,

        /// Destination register.
        rd: Box<A64Reg>,
    },

    /// A no-op instruction.
    Nop {
        /// Source provenance for the item.
        prov: Prov,
    },

    /// A return instruction.
    Ret {
        /// Source provenance for the item.
        prov: Prov,
    },
}

/// The AArch64 register subset supported by the pilot.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum A64Reg {
    Sp {},

    X0 {},

    X1 {},

    X2 {},

    X3 {},
}

/// The root ASM program, with an explicit in-file dialect.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Program {
    /// An AArch64 assembly unit.
    AArch64 {
        /// Optional program-level docs.
        docs: Option<DocBlock>,

        /// Ordered labels and instructions.
        items: Vec<A64Item>,
    },

    /// An x86-64 assembly unit.
    X86_64 {
        /// Optional program-level docs.
        docs: Option<DocBlock>,

        /// Ordered labels and instructions.
        items: Vec<X64Item>,
    },
}

/// x86-64 labels and instructions.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum X64Item {
    /// Add an immediate to a register.
    AddImm {
        /// Immediate value.
        imm: Imm,

        /// Source provenance for the item.
        prov: Prov,

        /// Destination register.
        rd: Box<X64Reg>,
    },

    /// Jump to a symbolic label.
    Jmp {
        /// Source provenance for the item.
        prov: Prov,

        /// Jump target label.
        target: LabelName,
    },

    /// A symbolic label definition.
    Label {
        /// Label name.
        name: LabelName,

        /// Source provenance for the item.
        prov: Prov,
    },

    /// Move an immediate into a register.
    MovImm {
        /// Immediate value.
        imm: Imm,

        /// Source provenance for the item.
        prov: Prov,

        /// Destination register.
        rd: Box<X64Reg>,
    },

    /// Move a register into another register.
    MovReg {
        /// Source provenance for the item.
        prov: Prov,

        /// Destination register.
        rd: Box<X64Reg>,

        /// Source register.
        rm: Box<X64Reg>,
    },

    /// A no-op instruction.
    Nop {
        /// Source provenance for the item.
        prov: Prov,
    },

    /// A return instruction.
    Ret {
        /// Source provenance for the item.
        prov: Prov,
    },
}

/// The x86-64 register subset supported by the pilot.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum X64Reg {
    Rax {},

    Rbp {},

    Rbx {},

    Rcx {},

    Rdx {},

    Rsp {},
}
