// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#![allow(dead_code)]
use super::*;
pub fn format_root_text(node: &Program) -> String {
    format_program(node)
}
pub fn format_program_text(node: &Program) -> String {
    format_root_text(node)
}

impl std::fmt::Display for Program {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&format_root_text(self))
    }
}
const INDENT_WIDTH: usize = 4;
struct Writer {
    out: String,

    indent: usize,

    at_line_start: bool,
}

impl Writer {
    fn new() -> Self {
        Self {
            out: String::new(),
            indent: 0,
            at_line_start: false,
        }
    }
    fn text(&mut self, text: &str) {
        for ch in text.chars() {
            if self.at_line_start && ch != '\n' {
                for _ in 0..self.indent {
                    self.out.push(' ');
                }
                self.at_line_start = false;
            }
            self.out.push(ch);
            if ch == '\n' {
                self.at_line_start = true;
            }
        }
    }
    fn with_indent(&mut self, f: impl FnOnce(&mut Self)) {
        self.indent += INDENT_WIDTH;
        f(self);
        self.indent -= INDENT_WIDTH;
    }
    fn finish(self) -> String {
        self.out
    }
}
pub fn format_a64_item(node: &A64Item) -> String {
    let mut w = Writer::new();
    write_a64_item(&mut w, node);
    w.finish()
}
fn write_a64_item(w: &mut Writer, node: &A64Item) {
    match node {
        A64Item::AddImm { imm, rd, rn, .. } => {
            w.text("add ");
            write_a64_reg(w, &rd);
            w.text(", ");
            write_a64_reg(w, &rn);
            w.text(", ");
            w.text(&imm.0);
        }
        A64Item::B { target, .. } => {
            w.text("b ");
            w.text(&target.0);
        }
        A64Item::Label { name, .. } => {
            w.text(&name.0);
            w.text(":");
        }
        A64Item::Mov { rd, rm, .. } => {
            w.text("mov ");
            write_a64_reg(w, &rd);
            w.text(", ");
            write_a64_reg(w, &rm);
        }
        A64Item::Movz { imm, rd, .. } => {
            w.text("movz ");
            write_a64_reg(w, &rd);
            w.text(", ");
            w.text(&imm.0);
        }
        A64Item::Nop { .. } => {
            w.text("nop");
        }
        A64Item::Ret { .. } => {
            w.text("ret");
        }
    }
}
pub fn format_a64_reg(node: &A64Reg) -> String {
    let mut w = Writer::new();
    write_a64_reg(&mut w, node);
    w.finish()
}
fn write_a64_reg(w: &mut Writer, node: &A64Reg) {
    match node {
        A64Reg::Sp { .. } => {
            w.text("sp");
        }
        A64Reg::X0 { .. } => {
            w.text("x0");
        }
        A64Reg::X1 { .. } => {
            w.text("x1");
        }
        A64Reg::X2 { .. } => {
            w.text("x2");
        }
        A64Reg::X3 { .. } => {
            w.text("x3");
        }
    }
}
pub fn format_program(node: &Program) -> String {
    let mut w = Writer::new();
    write_program(&mut w, node);
    w.finish()
}
fn write_program(w: &mut Writer, node: &Program) {
    match node {
        Program::AArch64 { items, .. } => {
            w.text("asm aarch64 ");
            w.text("{");
            w.text("\n");
            for (idx, value) in items.iter().enumerate() {
                if idx != 0 {
                    w.text("\n");
                }
                w.with_indent(|w| {
                    write_a64_item(w, &value);
                });
            }
            w.text("\n}");
        }
        Program::X86_64 { items, .. } => {
            w.text("asm x86_64 ");
            w.text("{");
            w.text("\n");
            for (idx, value) in items.iter().enumerate() {
                if idx != 0 {
                    w.text("\n");
                }
                w.with_indent(|w| {
                    write_x64_item(w, &value);
                });
            }
            w.text("\n}");
        }
    }
}
pub fn format_x64_item(node: &X64Item) -> String {
    let mut w = Writer::new();
    write_x64_item(&mut w, node);
    w.finish()
}
fn write_x64_item(w: &mut Writer, node: &X64Item) {
    match node {
        X64Item::AddImm { imm, rd, .. } => {
            w.text("add ");
            write_x64_reg(w, &rd);
            w.text(", ");
            w.text(&imm.0);
        }
        X64Item::Jmp { target, .. } => {
            w.text("jmp ");
            w.text(&target.0);
        }
        X64Item::Label { name, .. } => {
            w.text(&name.0);
            w.text(":");
        }
        X64Item::MovImm { imm, rd, .. } => {
            w.text("mov ");
            write_x64_reg(w, &rd);
            w.text(", ");
            w.text(&imm.0);
        }
        X64Item::MovReg { rd, rm, .. } => {
            w.text("mov ");
            write_x64_reg(w, &rd);
            w.text(", ");
            write_x64_reg(w, &rm);
        }
        X64Item::Nop { .. } => {
            w.text("nop");
        }
        X64Item::Ret { .. } => {
            w.text("ret");
        }
    }
}
pub fn format_x64_reg(node: &X64Reg) -> String {
    let mut w = Writer::new();
    write_x64_reg(&mut w, node);
    w.finish()
}
fn write_x64_reg(w: &mut Writer, node: &X64Reg) {
    match node {
        X64Reg::Rax { .. } => {
            w.text("rax");
        }
        X64Reg::Rbp { .. } => {
            w.text("rbp");
        }
        X64Reg::Rbx { .. } => {
            w.text("rbx");
        }
        X64Reg::Rcx { .. } => {
            w.text("rcx");
        }
        X64Reg::Rdx { .. } => {
            w.text("rdx");
        }
        X64Reg::Rsp { .. } => {
            w.text("rsp");
        }
    }
}
