// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TokenSpec {
    pub name: &'static str,

    pub kind: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RuleSpec {
    pub name: &'static str,

    pub kind: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TypeUseSpec {
    pub name: &'static str,

    pub kind: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NodeSpec {
    pub name: &'static str,

    pub kind: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PrintSpec {
    pub name: &'static str,

    pub template: &'static str,
}

pub const REPR_NAME: &str = "ASM";

pub const REPR_FILE_EXT: &str = ".k-asm";

pub const REPR_ROOT: &str = "Program";

pub const REPR_PURPOSE: &str = "Symbolic architecture-specific assembly";

pub const REPR_ROUND_TRIP: &str = "canonical-print";

pub const REPR_PROVENANCE: &str = "required";

pub static REPR_CANONICAL_IDENTITIES: &[&str] = &["dialect", "label-name", "register-name"];

pub static TOKENS: &[TokenSpec] = &[
    TokenSpec {
        name: "ident",
        kind: "ident",
    },
    TokenSpec {
        name: "int",
        kind: "int",
    },
];

pub static RULES: &[RuleSpec] = &[
    RuleSpec {
        name: "A64Item",
        kind: "choice",
    },
    RuleSpec {
        name: "A64Reg",
        kind: "choice",
    },
    RuleSpec {
        name: "Program",
        kind: "choice",
    },
    RuleSpec {
        name: "X64Item",
        kind: "choice",
    },
    RuleSpec {
        name: "X64Reg",
        kind: "choice",
    },
];

pub static COMMON_TYPES: &[TypeUseSpec] = &[
    TypeUseSpec {
        name: "docs",
        kind: "DocBlock",
    },
    TypeUseSpec {
        name: "provenance",
        kind: "Prov",
    },
];

pub static NODES: &[NodeSpec] = &[
    NodeSpec {
        name: "A64Item",
        kind: "enum",
    },
    NodeSpec {
        name: "A64Reg",
        kind: "enum",
    },
    NodeSpec {
        name: "Program",
        kind: "enum",
    },
    NodeSpec {
        name: "X64Item",
        kind: "enum",
    },
    NodeSpec {
        name: "X64Reg",
        kind: "enum",
    },
];

pub static CANONICAL_PRINT: &[PrintSpec] = &[
    PrintSpec {
        name: "A64Item.AddImm",
        template: "add {rd}, {rn}, {imm}",
    },
    PrintSpec {
        name: "A64Item.B",
        template: "b {target}",
    },
    PrintSpec {
        name: "A64Item.Label",
        template: "{name}:",
    },
    PrintSpec {
        name: "A64Item.Mov",
        template: "mov {rd}, {rm}",
    },
    PrintSpec {
        name: "A64Item.Movz",
        template: "movz {rd}, {imm}",
    },
    PrintSpec {
        name: "A64Item.Nop",
        template: "nop",
    },
    PrintSpec {
        name: "A64Item.Ret",
        template: "ret",
    },
    PrintSpec {
        name: "A64Reg.Sp",
        template: "sp",
    },
    PrintSpec {
        name: "A64Reg.X0",
        template: "x0",
    },
    PrintSpec {
        name: "A64Reg.X1",
        template: "x1",
    },
    PrintSpec {
        name: "A64Reg.X2",
        template: "x2",
    },
    PrintSpec {
        name: "A64Reg.X3",
        template: "x3",
    },
    PrintSpec {
        name: "Program.AArch64",
        template: "asm aarch64 {\n{items}\n}",
    },
    PrintSpec {
        name: "Program.X86_64",
        template: "asm x86_64 {\n{items}\n}",
    },
    PrintSpec {
        name: "X64Item.AddImm",
        template: "add {rd}, {imm}",
    },
    PrintSpec {
        name: "X64Item.Jmp",
        template: "jmp {target}",
    },
    PrintSpec {
        name: "X64Item.Label",
        template: "{name}:",
    },
    PrintSpec {
        name: "X64Item.MovImm",
        template: "mov {rd}, {imm}",
    },
    PrintSpec {
        name: "X64Item.MovReg",
        template: "mov {rd}, {rm}",
    },
    PrintSpec {
        name: "X64Item.Nop",
        template: "nop",
    },
    PrintSpec {
        name: "X64Item.Ret",
        template: "ret",
    },
    PrintSpec {
        name: "X64Reg.Rax",
        template: "rax",
    },
    PrintSpec {
        name: "X64Reg.Rbp",
        template: "rbp",
    },
    PrintSpec {
        name: "X64Reg.Rbx",
        template: "rbx",
    },
    PrintSpec {
        name: "X64Reg.Rcx",
        template: "rcx",
    },
    PrintSpec {
        name: "X64Reg.Rdx",
        template: "rdx",
    },
    PrintSpec {
        name: "X64Reg.Rsp",
        template: "rsp",
    },
];
