// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

use super::*;
use chumsky::prelude::*;
type ParseExtra<'src> = extra::Err<Rich<'src, char>>;
fn ws<'src>() -> impl Parser<'src, &'src str, (), ParseExtra<'src>> + Clone {
    any()
        .filter(|c: &char| c.is_whitespace())
        .repeated()
        .ignored()
}
fn token_ident<'src>() -> impl Parser<'src, &'src str, String, ParseExtra<'src>> + Clone {
    text::ident::<_, ParseExtra<'src>>().map(str::to_owned)
}
fn token_int<'src>() -> impl Parser<'src, &'src str, String, ParseExtra<'src>> + Clone {
    text::int::<_, ParseExtra<'src>>(10).map(str::to_owned)
}
fn prov_from_span(span: chumsky::span::SimpleSpan<usize>, file_id: Option<u32>) -> Prov {
    Prov {
        file_id,
        span: Some(Span {
            start: span.start as u32,
            end: span.end as u32,
        }),
    }
}
pub fn parse_root_text_rich(
    source: &str,

    file_id: Option<u32>,
) -> Result<Program, Vec<Rich<'_, char>>> {
    let a64_reg_parser = choice((
        (just("x0").to(()))
            .map_with(move |(), e| {
                A64Reg::X0(X0 {
                    prov: prov_from_span(e.span(), file_id),
                })
            })
            .then_ignore(ws()),
        (just("x1").to(()))
            .map_with(move |(), e| {
                A64Reg::X1(X1 {
                    prov: prov_from_span(e.span(), file_id),
                })
            })
            .then_ignore(ws()),
        (just("x2").to(()))
            .map_with(move |(), e| {
                A64Reg::X2(X2 {
                    prov: prov_from_span(e.span(), file_id),
                })
            })
            .then_ignore(ws()),
        (just("x3").to(()))
            .map_with(move |(), e| {
                A64Reg::X3(X3 {
                    prov: prov_from_span(e.span(), file_id),
                })
            })
            .then_ignore(ws()),
        (just("sp").to(()))
            .map_with(move |(), e| {
                A64Reg::Sp(Sp {
                    prov: prov_from_span(e.span(), file_id),
                })
            })
            .then_ignore(ws()),
    ))
    .boxed();
    let add_keyword_parser = (just("add").to(()))
        .map_with(move |(), e| AddKeyword {
            prov: prov_from_span(e.span(), file_id),
        })
        .then_ignore(ws())
        .boxed();
    let b_keyword_parser = (just("b").to(()))
        .map_with(move |(), e| BKeyword {
            prov: prov_from_span(e.span(), file_id),
        })
        .then_ignore(ws())
        .boxed();
    let mov_keyword_parser = (just("mov").to(()))
        .map_with(move |(), e| MovKeyword {
            prov: prov_from_span(e.span(), file_id),
        })
        .then_ignore(ws())
        .boxed();
    let movz_keyword_parser = (just("movz").to(()))
        .map_with(move |(), e| MovzKeyword {
            prov: prov_from_span(e.span(), file_id),
        })
        .then_ignore(ws())
        .boxed();
    let nop_keyword_parser = (just("nop").to(()))
        .map_with(move |(), e| NopKeyword {
            prov: prov_from_span(e.span(), file_id),
        })
        .then_ignore(ws())
        .boxed();
    let ret_keyword_parser = (just("ret").to(()))
        .map_with(move |(), e| RetKeyword {
            prov: prov_from_span(e.span(), file_id),
        })
        .then_ignore(ws())
        .boxed();
    let a64_item_parser = choice((
        ((token_ident()
            .map_with(move |text, e| LabelName {
                prov: prov_from_span(e.span(), file_id),
                text,
            })
            .then_ignore(ws()))
        .then_ignore(just(":").padded()))
        .map_with(move |name, e| A64Item::Label {
            name: name,
            prov: prov_from_span(e.span(), file_id),
        }),
        ((ret_keyword_parser.clone()).map(Box::new)).map_with(move |op, e| A64Item::Ret {
            op: op,
            prov: prov_from_span(e.span(), file_id),
        }),
        ((nop_keyword_parser.clone()).map(Box::new)).map_with(move |op, e| A64Item::Nop {
            op: op,
            prov: prov_from_span(e.span(), file_id),
        }),
        (((((movz_keyword_parser.clone()).map(Box::new))
            .then((a64_reg_parser.clone()).map(Box::new)))
        .then_ignore(just(",").padded()))
        .then(
            token_int()
                .try_map(move |text, span| match text.parse::<u64>() {
                    Ok(value) => Ok(Imm {
                        prov: prov_from_span(span, file_id),
                        value,
                    }),
                    Err(err) => Err(Rich::custom(
                        span,
                        format!("invalid integer literal {text:?}: {err}"),
                    )),
                })
                .then_ignore(ws()),
        ))
        .map_with(move |((op, rd), imm), e| A64Item::Movz {
            imm: imm,
            op: op,
            prov: prov_from_span(e.span(), file_id),
            rd: rd,
        }),
        (((((mov_keyword_parser.clone()).map(Box::new))
            .then((a64_reg_parser.clone()).map(Box::new)))
        .then_ignore(just(",").padded()))
        .then((a64_reg_parser.clone()).map(Box::new)))
        .map_with(move |((op, rd), rm), e| A64Item::Mov {
            op: op,
            prov: prov_from_span(e.span(), file_id),
            rd: rd,
            rm: rm,
        }),
        (((((((add_keyword_parser.clone()).map(Box::new))
            .then((a64_reg_parser.clone()).map(Box::new)))
        .then_ignore(just(",").padded()))
        .then((a64_reg_parser.clone()).map(Box::new)))
        .then_ignore(just(",").padded()))
        .then(
            token_int()
                .try_map(move |text, span| match text.parse::<u64>() {
                    Ok(value) => Ok(Imm {
                        prov: prov_from_span(span, file_id),
                        value,
                    }),
                    Err(err) => Err(Rich::custom(
                        span,
                        format!("invalid integer literal {text:?}: {err}"),
                    )),
                })
                .then_ignore(ws()),
        ))
        .map_with(move |(((op, rd), rn), imm), e| A64Item::AddImm {
            imm: imm,
            op: op,
            prov: prov_from_span(e.span(), file_id),
            rd: rd,
            rn: rn,
        }),
        (((b_keyword_parser.clone()).map(Box::new)).then(
            token_ident()
                .map_with(move |text, e| LabelName {
                    prov: prov_from_span(e.span(), file_id),
                    text,
                })
                .then_ignore(ws()),
        ))
        .map_with(move |(op, target), e| A64Item::B {
            op: op,
            prov: prov_from_span(e.span(), file_id),
            target: target,
        }),
    ))
    .boxed();
    let a_arch64_dialect_keyword_parser = (just("aarch64").to(()))
        .map_with(move |(), e| AArch64DialectKeyword {
            prov: prov_from_span(e.span(), file_id),
        })
        .then_ignore(ws())
        .boxed();
    let asm_keyword_parser = (just("asm").to(()))
        .map_with(move |(), e| AsmKeyword {
            prov: prov_from_span(e.span(), file_id),
        })
        .then_ignore(ws())
        .boxed();
    let jmp_keyword_parser = (just("jmp").to(()))
        .map_with(move |(), e| JmpKeyword {
            prov: prov_from_span(e.span(), file_id),
        })
        .then_ignore(ws())
        .boxed();
    let x64_reg_parser = choice((
        (just("rax").to(()))
            .map_with(move |(), e| {
                X64Reg::Rax(Rax {
                    prov: prov_from_span(e.span(), file_id),
                })
            })
            .then_ignore(ws()),
        (just("rbx").to(()))
            .map_with(move |(), e| {
                X64Reg::Rbx(Rbx {
                    prov: prov_from_span(e.span(), file_id),
                })
            })
            .then_ignore(ws()),
        (just("rcx").to(()))
            .map_with(move |(), e| {
                X64Reg::Rcx(Rcx {
                    prov: prov_from_span(e.span(), file_id),
                })
            })
            .then_ignore(ws()),
        (just("rdx").to(()))
            .map_with(move |(), e| {
                X64Reg::Rdx(Rdx {
                    prov: prov_from_span(e.span(), file_id),
                })
            })
            .then_ignore(ws()),
        (just("rsp").to(()))
            .map_with(move |(), e| {
                X64Reg::Rsp(Rsp {
                    prov: prov_from_span(e.span(), file_id),
                })
            })
            .then_ignore(ws()),
        (just("rbp").to(()))
            .map_with(move |(), e| {
                X64Reg::Rbp(Rbp {
                    prov: prov_from_span(e.span(), file_id),
                })
            })
            .then_ignore(ws()),
    ))
    .boxed();
    let x64_item_parser = choice((
        ((token_ident()
            .map_with(move |text, e| LabelName {
                prov: prov_from_span(e.span(), file_id),
                text,
            })
            .then_ignore(ws()))
        .then_ignore(just(":").padded()))
        .map_with(move |name, e| X64Item::Label {
            name: name,
            prov: prov_from_span(e.span(), file_id),
        }),
        ((ret_keyword_parser.clone()).map(Box::new)).map_with(move |op, e| X64Item::Ret {
            op: op,
            prov: prov_from_span(e.span(), file_id),
        }),
        ((nop_keyword_parser.clone()).map(Box::new)).map_with(move |op, e| X64Item::Nop {
            op: op,
            prov: prov_from_span(e.span(), file_id),
        }),
        (((((mov_keyword_parser.clone()).map(Box::new))
            .then((x64_reg_parser.clone()).map(Box::new)))
        .then_ignore(just(",").padded()))
        .then(
            token_int()
                .try_map(move |text, span| match text.parse::<u64>() {
                    Ok(value) => Ok(Imm {
                        prov: prov_from_span(span, file_id),
                        value,
                    }),
                    Err(err) => Err(Rich::custom(
                        span,
                        format!("invalid integer literal {text:?}: {err}"),
                    )),
                })
                .then_ignore(ws()),
        ))
        .map_with(move |((op, rd), imm), e| X64Item::MovImm {
            imm: imm,
            op: op,
            prov: prov_from_span(e.span(), file_id),
            rd: rd,
        }),
        (((((mov_keyword_parser.clone()).map(Box::new))
            .then((x64_reg_parser.clone()).map(Box::new)))
        .then_ignore(just(",").padded()))
        .then((x64_reg_parser.clone()).map(Box::new)))
        .map_with(move |((op, rd), rm), e| X64Item::MovReg {
            op: op,
            prov: prov_from_span(e.span(), file_id),
            rd: rd,
            rm: rm,
        }),
        (((((add_keyword_parser.clone()).map(Box::new))
            .then((x64_reg_parser.clone()).map(Box::new)))
        .then_ignore(just(",").padded()))
        .then(
            token_int()
                .try_map(move |text, span| match text.parse::<u64>() {
                    Ok(value) => Ok(Imm {
                        prov: prov_from_span(span, file_id),
                        value,
                    }),
                    Err(err) => Err(Rich::custom(
                        span,
                        format!("invalid integer literal {text:?}: {err}"),
                    )),
                })
                .then_ignore(ws()),
        ))
        .map_with(move |((op, rd), imm), e| X64Item::AddImm {
            imm: imm,
            op: op,
            prov: prov_from_span(e.span(), file_id),
            rd: rd,
        }),
        (((jmp_keyword_parser.clone()).map(Box::new)).then(
            token_ident()
                .map_with(move |text, e| LabelName {
                    prov: prov_from_span(e.span(), file_id),
                    text,
                })
                .then_ignore(ws()),
        ))
        .map_with(move |(op, target), e| X64Item::Jmp {
            op: op,
            prov: prov_from_span(e.span(), file_id),
            target: target,
        }),
    ))
    .boxed();
    let x86_64_dialect_keyword_parser = (just("x86_64").to(()))
        .map_with(move |(), e| X86_64DialectKeyword {
            prov: prov_from_span(e.span(), file_id),
        })
        .then_ignore(ws())
        .boxed();
    let program_parser = choice((
        ((((((asm_keyword_parser.clone()).map(Box::new))
            .then((a_arch64_dialect_keyword_parser.clone()).map(Box::new)))
        .then_ignore(just("{").padded()))
        .then((a64_item_parser.clone()).repeated().collect::<Vec<_>>()))
        .then_ignore(just("}").padded()))
        .map_with(move |((keyword, dialect), items), e| Program::AArch64 {
            dialect: dialect,
            docs: None,
            items: items,
            keyword: keyword,
            prov: prov_from_span(e.span(), file_id),
        }),
        ((((((asm_keyword_parser.clone()).map(Box::new))
            .then((x86_64_dialect_keyword_parser.clone()).map(Box::new)))
        .then_ignore(just("{").padded()))
        .then((x64_item_parser.clone()).repeated().collect::<Vec<_>>()))
        .then_ignore(just("}").padded()))
        .map_with(move |((keyword, dialect), items), e| Program::X86_64 {
            dialect: dialect,
            docs: None,
            items: items,
            keyword: keyword,
            prov: prov_from_span(e.span(), file_id),
        }),
    ))
    .boxed();
    program_parser
        .then_ignore(end())
        .parse(source)
        .into_result()
}
pub fn parse_root_text_with_file_id(source: &str, file_id: Option<u32>) -> Result<Program, String> {
    parse_root_text_rich(source, file_id).map_err(|errs| crate::format_rich_errors(source, errs))
}
pub fn parse_root_text(source: &str) -> Result<Program, String> {
    parse_root_text_with_file_id(source, None)
}
pub fn parse_program_text_rich(
    source: &str,

    file_id: Option<u32>,
) -> Result<Program, Vec<Rich<'_, char>>> {
    parse_root_text_rich(source, file_id)
}
pub fn parse_program_text_with_file_id(
    source: &str,

    file_id: Option<u32>,
) -> Result<Program, String> {
    parse_root_text_with_file_id(source, file_id)
}
pub fn parse_program_text(source: &str) -> Result<Program, String> {
    parse_root_text(source)
}
