// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

use super::*;
use chumsky::prelude::*;
type ParseExtra<'src> = extra::Err<Rich<'src, char>>;
fn ws<'src>() -> impl Parser<'src, &'src str, (), ParseExtra<'src>> + Clone {
    any()
        .filter(|c: &char| c.is_whitespace())
        .repeated()
        .ignored()
}
fn token_ident<'src>() -> impl Parser<'src, &'src str, String, ParseExtra<'src>> + Clone {
    text::ident::<_, ParseExtra<'src>>()
        .map(str::to_owned)
        .padded_by(ws())
}
fn token_int<'src>() -> impl Parser<'src, &'src str, String, ParseExtra<'src>> + Clone {
    text::int::<_, ParseExtra<'src>>(10)
        .map(str::to_owned)
        .padded_by(ws())
}
fn prov_from_span(span: chumsky::span::SimpleSpan<usize>, file_id: Option<u32>) -> Prov {
    Prov {
        file_id,
        span: Some(Span {
            start: span.start as u32,
            end: span.end as u32,
        }),
    }
}
pub fn parse_root_text_rich(
    source: &str,

    file_id: Option<u32>,
) -> Result<Program, Vec<Rich<'_, char>>> {
    let a64_reg_parser = choice((
        ((just("x0").padded()).to(())).map_with(move |(), _e| A64Reg::X0 {}),
        ((just("x1").padded()).to(())).map_with(move |(), _e| A64Reg::X1 {}),
        ((just("x2").padded()).to(())).map_with(move |(), _e| A64Reg::X2 {}),
        ((just("x3").padded()).to(())).map_with(move |(), _e| A64Reg::X3 {}),
        ((just("sp").padded()).to(())).map_with(move |(), _e| A64Reg::Sp {}),
    ))
    .boxed();
    let a64_item_parser = choice((
        ((token_ident().map(LabelName)).then_ignore(just(":").padded())).map_with(
            move |name, e| A64Item::Label {
                name: name,
                prov: prov_from_span(e.span(), file_id),
            },
        ),
        ((just("ret").padded()).to(())).map_with(move |(), e| A64Item::Ret {
            prov: prov_from_span(e.span(), file_id),
        }),
        ((just("nop").padded()).to(())).map_with(move |(), e| A64Item::Nop {
            prov: prov_from_span(e.span(), file_id),
        }),
        ((((just("movz").padded()).ignore_then((a64_reg_parser.clone()).map(Box::new)))
            .then_ignore(just(",").padded()))
        .then(token_int().map(Imm)))
        .map_with(move |(rd, imm), e| A64Item::Movz {
            imm: imm,
            prov: prov_from_span(e.span(), file_id),
            rd: rd,
        }),
        ((((just("mov").padded()).ignore_then((a64_reg_parser.clone()).map(Box::new)))
            .then_ignore(just(",").padded()))
        .then((a64_reg_parser.clone()).map(Box::new)))
        .map_with(move |(rd, rm), e| A64Item::Mov {
            prov: prov_from_span(e.span(), file_id),
            rd: rd,
            rm: rm,
        }),
        ((((((just("add").padded()).ignore_then((a64_reg_parser.clone()).map(Box::new)))
            .then_ignore(just(",").padded()))
        .then((a64_reg_parser.clone()).map(Box::new)))
        .then_ignore(just(",").padded()))
        .then(token_int().map(Imm)))
        .map_with(move |((rd, rn), imm), e| A64Item::AddImm {
            imm: imm,
            prov: prov_from_span(e.span(), file_id),
            rd: rd,
            rn: rn,
        }),
        ((just("b").padded()).ignore_then(token_ident().map(LabelName))).map_with(
            move |target, e| A64Item::B {
                prov: prov_from_span(e.span(), file_id),
                target: target,
            },
        ),
    ))
    .boxed();
    let x64_reg_parser = choice((
        ((just("rax").padded()).to(())).map_with(move |(), _e| X64Reg::Rax {}),
        ((just("rbx").padded()).to(())).map_with(move |(), _e| X64Reg::Rbx {}),
        ((just("rcx").padded()).to(())).map_with(move |(), _e| X64Reg::Rcx {}),
        ((just("rdx").padded()).to(())).map_with(move |(), _e| X64Reg::Rdx {}),
        ((just("rsp").padded()).to(())).map_with(move |(), _e| X64Reg::Rsp {}),
        ((just("rbp").padded()).to(())).map_with(move |(), _e| X64Reg::Rbp {}),
    ))
    .boxed();
    let x64_item_parser = choice((
        ((token_ident().map(LabelName)).then_ignore(just(":").padded())).map_with(
            move |name, e| X64Item::Label {
                name: name,
                prov: prov_from_span(e.span(), file_id),
            },
        ),
        ((just("ret").padded()).to(())).map_with(move |(), e| X64Item::Ret {
            prov: prov_from_span(e.span(), file_id),
        }),
        ((just("nop").padded()).to(())).map_with(move |(), e| X64Item::Nop {
            prov: prov_from_span(e.span(), file_id),
        }),
        ((((just("mov").padded()).ignore_then((x64_reg_parser.clone()).map(Box::new)))
            .then_ignore(just(",").padded()))
        .then(token_int().map(Imm)))
        .map_with(move |(rd, imm), e| X64Item::MovImm {
            imm: imm,
            prov: prov_from_span(e.span(), file_id),
            rd: rd,
        }),
        ((((just("mov").padded()).ignore_then((x64_reg_parser.clone()).map(Box::new)))
            .then_ignore(just(",").padded()))
        .then((x64_reg_parser.clone()).map(Box::new)))
        .map_with(move |(rd, rm), e| X64Item::MovReg {
            prov: prov_from_span(e.span(), file_id),
            rd: rd,
            rm: rm,
        }),
        ((((just("add").padded()).ignore_then((x64_reg_parser.clone()).map(Box::new)))
            .then_ignore(just(",").padded()))
        .then(token_int().map(Imm)))
        .map_with(move |(rd, imm), e| X64Item::AddImm {
            imm: imm,
            prov: prov_from_span(e.span(), file_id),
            rd: rd,
        }),
        ((just("jmp").padded()).ignore_then(token_ident().map(LabelName))).map_with(
            move |target, e| X64Item::Jmp {
                prov: prov_from_span(e.span(), file_id),
                target: target,
            },
        ),
    ))
    .boxed();
    let program_parser = choice((
        (((just("asm").padded()).ignore_then(
            (just("aarch64").padded()).ignore_then(
                (just("{").padded())
                    .ignore_then((a64_item_parser.clone()).repeated().collect::<Vec<_>>()),
            ),
        ))
        .then_ignore(just("}").padded()))
        .map_with(move |items, _e| Program::AArch64 {
            docs: None,
            items: items,
        }),
        (((just("asm").padded()).ignore_then(
            (just("x86_64").padded()).ignore_then(
                (just("{").padded())
                    .ignore_then((x64_item_parser.clone()).repeated().collect::<Vec<_>>()),
            ),
        ))
        .then_ignore(just("}").padded()))
        .map_with(move |items, _e| Program::X86_64 {
            docs: None,
            items: items,
        }),
    ))
    .boxed();
    program_parser
        .then_ignore(end())
        .parse(source)
        .into_result()
}
pub fn parse_root_text_with_file_id(source: &str, file_id: Option<u32>) -> Result<Program, String> {
    parse_root_text_rich(source, file_id).map_err(|errs| crate::format_rich_errors(source, errs))
}
pub fn parse_root_text(source: &str) -> Result<Program, String> {
    parse_root_text_with_file_id(source, None)
}
pub fn parse_program_text_rich(
    source: &str,

    file_id: Option<u32>,
) -> Result<Program, Vec<Rich<'_, char>>> {
    parse_root_text_rich(source, file_id)
}
pub fn parse_program_text_with_file_id(
    source: &str,

    file_id: Option<u32>,
) -> Result<Program, String> {
    parse_root_text_with_file_id(source, file_id)
}
pub fn parse_program_text(source: &str) -> Result<Program, String> {
    parse_root_text(source)
}
