// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

use super::ast::*;

pub trait HasProvenance {
    fn provenance(&self) -> Option<&Prov>;
}

impl HasProvenance for A64Item {
    fn provenance(&self) -> Option<&Prov> {
        match self {
            Self::AddImm { prov, .. } => Some(prov),
            Self::B { prov, .. } => Some(prov),
            Self::Label { prov, .. } => Some(prov),
            Self::Mov { prov, .. } => Some(prov),
            Self::Movz { prov, .. } => Some(prov),
            Self::Nop { prov, .. } => Some(prov),
            Self::Ret { prov, .. } => Some(prov),
        }
    }
}

impl HasProvenance for A64Reg {
    fn provenance(&self) -> Option<&Prov> {
        match self {
            Self::Sp(value) => Some(&value.prov),
            Self::X0(value) => Some(&value.prov),
            Self::X1(value) => Some(&value.prov),
            Self::X2(value) => Some(&value.prov),
            Self::X3(value) => Some(&value.prov),
        }
    }
}

impl HasProvenance for AArch64DialectKeyword {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}

impl HasProvenance for AddKeyword {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}

impl HasProvenance for AsmKeyword {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}

impl HasProvenance for BKeyword {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}

impl HasProvenance for JmpKeyword {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}

impl HasProvenance for MovKeyword {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}

impl HasProvenance for MovzKeyword {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}

impl HasProvenance for NopKeyword {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}

impl HasProvenance for Program {
    fn provenance(&self) -> Option<&Prov> {
        match self {
            Self::AArch64 { prov, .. } => Some(prov),
            Self::X86_64 { prov, .. } => Some(prov),
        }
    }
}

impl HasProvenance for RetKeyword {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}

impl HasProvenance for X64Item {
    fn provenance(&self) -> Option<&Prov> {
        match self {
            Self::AddImm { prov, .. } => Some(prov),
            Self::Jmp { prov, .. } => Some(prov),
            Self::Label { prov, .. } => Some(prov),
            Self::MovImm { prov, .. } => Some(prov),
            Self::MovReg { prov, .. } => Some(prov),
            Self::Nop { prov, .. } => Some(prov),
            Self::Ret { prov, .. } => Some(prov),
        }
    }
}

impl HasProvenance for X64Reg {
    fn provenance(&self) -> Option<&Prov> {
        match self {
            Self::Rax(value) => Some(&value.prov),
            Self::Rbp(value) => Some(&value.prov),
            Self::Rbx(value) => Some(&value.prov),
            Self::Rcx(value) => Some(&value.prov),
            Self::Rdx(value) => Some(&value.prov),
            Self::Rsp(value) => Some(&value.prov),
        }
    }
}

impl HasProvenance for X86_64DialectKeyword {
    fn provenance(&self) -> Option<&Prov> {
        Some(&self.prov)
    }
}
