// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

use super::ast::*;

pub trait HasProvenance {
    fn provenance(&self) -> Option<&Prov>;
}

impl HasProvenance for A64Item {
    fn provenance(&self) -> Option<&Prov> {
        match self {
            Self::AddImm { prov, .. } => Some(prov),
            Self::B { prov, .. } => Some(prov),
            Self::Label { prov, .. } => Some(prov),
            Self::Mov { prov, .. } => Some(prov),
            Self::Movz { prov, .. } => Some(prov),
            Self::Nop { prov, .. } => Some(prov),
            Self::Ret { prov, .. } => Some(prov),
        }
    }
}

impl HasProvenance for X64Item {
    fn provenance(&self) -> Option<&Prov> {
        match self {
            Self::AddImm { prov, .. } => Some(prov),
            Self::Jmp { prov, .. } => Some(prov),
            Self::Label { prov, .. } => Some(prov),
            Self::MovImm { prov, .. } => Some(prov),
            Self::MovReg { prov, .. } => Some(prov),
            Self::Nop { prov, .. } => Some(prov),
            Self::Ret { prov, .. } => Some(prov),
        }
    }
}
