// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

use super::*;

pub trait Visit {
    fn visit_a64_item(&mut self, node: &A64Item) {
        walk_a64_item(self, node);
    }
    fn visit_a64_reg(&mut self, node: &A64Reg) {
        walk_a64_reg(self, node);
    }
    fn visit_program(&mut self, node: &Program) {
        walk_program(self, node);
    }
    fn visit_x64_item(&mut self, node: &X64Item) {
        walk_x64_item(self, node);
    }
    fn visit_x64_reg(&mut self, node: &X64Reg) {
        walk_x64_reg(self, node);
    }
}

pub trait VisitMut {
    fn visit_a64_item_mut(&mut self, node: &mut A64Item) {
        walk_a64_item_mut(self, node);
    }
    fn visit_a64_reg_mut(&mut self, node: &mut A64Reg) {
        walk_a64_reg_mut(self, node);
    }
    fn visit_program_mut(&mut self, node: &mut Program) {
        walk_program_mut(self, node);
    }
    fn visit_x64_item_mut(&mut self, node: &mut X64Item) {
        walk_x64_item_mut(self, node);
    }
    fn visit_x64_reg_mut(&mut self, node: &mut X64Reg) {
        walk_x64_reg_mut(self, node);
    }
}
pub fn walk_a64_item<V: ?Sized + Visit>(v: &mut V, node: &A64Item) {
    match node {
        A64Item::AddImm { rd, rn, .. } => {
            v.visit_a64_reg(rd);
            v.visit_a64_reg(rn);
        }
        A64Item::B { .. } => {}
        A64Item::Label { .. } => {}
        A64Item::Mov { rd, rm, .. } => {
            v.visit_a64_reg(rd);
            v.visit_a64_reg(rm);
        }
        A64Item::Movz { rd, .. } => {
            v.visit_a64_reg(rd);
        }
        A64Item::Nop { .. } => {}
        A64Item::Ret { .. } => {}
    }
}
pub fn walk_a64_reg<V: ?Sized + Visit>(v: &mut V, node: &A64Reg) {
    match node {
        A64Reg::Sp {} => {}
        A64Reg::X0 {} => {}
        A64Reg::X1 {} => {}
        A64Reg::X2 {} => {}
        A64Reg::X3 {} => {}
    }
}
pub fn walk_program<V: ?Sized + Visit>(v: &mut V, node: &Program) {
    match node {
        Program::AArch64 { items, .. } => {
            for value in items.iter() {
                v.visit_a64_item(value);
            }
        }
        Program::X86_64 { items, .. } => {
            for value in items.iter() {
                v.visit_x64_item(value);
            }
        }
    }
}
pub fn walk_x64_item<V: ?Sized + Visit>(v: &mut V, node: &X64Item) {
    match node {
        X64Item::AddImm { rd, .. } => {
            v.visit_x64_reg(rd);
        }
        X64Item::Jmp { .. } => {}
        X64Item::Label { .. } => {}
        X64Item::MovImm { rd, .. } => {
            v.visit_x64_reg(rd);
        }
        X64Item::MovReg { rd, rm, .. } => {
            v.visit_x64_reg(rd);
            v.visit_x64_reg(rm);
        }
        X64Item::Nop { .. } => {}
        X64Item::Ret { .. } => {}
    }
}
pub fn walk_x64_reg<V: ?Sized + Visit>(v: &mut V, node: &X64Reg) {
    match node {
        X64Reg::Rax {} => {}
        X64Reg::Rbp {} => {}
        X64Reg::Rbx {} => {}
        X64Reg::Rcx {} => {}
        X64Reg::Rdx {} => {}
        X64Reg::Rsp {} => {}
    }
}
pub fn walk_a64_item_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut A64Item) {
    match node {
        A64Item::AddImm { rd, rn, .. } => {
            v.visit_a64_reg_mut(rd);
            v.visit_a64_reg_mut(rn);
        }
        A64Item::B { .. } => {}
        A64Item::Label { .. } => {}
        A64Item::Mov { rd, rm, .. } => {
            v.visit_a64_reg_mut(rd);
            v.visit_a64_reg_mut(rm);
        }
        A64Item::Movz { rd, .. } => {
            v.visit_a64_reg_mut(rd);
        }
        A64Item::Nop { .. } => {}
        A64Item::Ret { .. } => {}
    }
}
pub fn walk_a64_reg_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut A64Reg) {
    match node {
        A64Reg::Sp {} => {}
        A64Reg::X0 {} => {}
        A64Reg::X1 {} => {}
        A64Reg::X2 {} => {}
        A64Reg::X3 {} => {}
    }
}
pub fn walk_program_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut Program) {
    match node {
        Program::AArch64 { items, .. } => {
            for value in items.iter_mut() {
                v.visit_a64_item_mut(value);
            }
        }
        Program::X86_64 { items, .. } => {
            for value in items.iter_mut() {
                v.visit_x64_item_mut(value);
            }
        }
    }
}
pub fn walk_x64_item_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut X64Item) {
    match node {
        X64Item::AddImm { rd, .. } => {
            v.visit_x64_reg_mut(rd);
        }
        X64Item::Jmp { .. } => {}
        X64Item::Label { .. } => {}
        X64Item::MovImm { rd, .. } => {
            v.visit_x64_reg_mut(rd);
        }
        X64Item::MovReg { rd, rm, .. } => {
            v.visit_x64_reg_mut(rd);
            v.visit_x64_reg_mut(rm);
        }
        X64Item::Nop { .. } => {}
        X64Item::Ret { .. } => {}
    }
}
pub fn walk_x64_reg_mut<V: ?Sized + VisitMut>(v: &mut V, node: &mut X64Reg) {
    match node {
        X64Reg::Rax {} => {}
        X64Reg::Rbp {} => {}
        X64Reg::Rbx {} => {}
        X64Reg::Rcx {} => {}
        X64Reg::Rdx {} => {}
        X64Reg::Rsp {} => {}
    }
}
