[package]
name = "kajit-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kajit"
path = "src/main.rs"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[features]
default = []

[dependencies]
facet = "0.44"
figue = "2"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
