// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

use crate::{asm, hir, mir};

#[derive(Clone, Copy)]
pub struct ReprSpec {
    pub name: &'static str,

    pub file_ext: &'static str,

    pub validate: fn(&str) -> Result<(), String>,

    pub format: fn(&str) -> Result<String, String>,

    pub semantic_tokens: fn(&str) -> Vec<SemanticToken>,

    pub hover_entries: fn(&str) -> Vec<HoverEntry>,

    pub resolve: fn(&str) -> Result<ResolutionSet, String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SemanticToken {
    pub start: u32,

    pub end: u32,

    pub kind: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HoverEntry {
    pub start: u32,

    pub end: u32,

    pub markdown: String,

    pub priority: u8,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SymbolKind {
    Function,

    Type,

    Label,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SymbolDef {
    pub name: String,

    pub kind: SymbolKind,

    pub start: u32,

    pub end: u32,

    pub detail: Option<String>,

    pub docs: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SymbolRef {
    pub name: String,

    pub kind: SymbolKind,

    pub start: u32,

    pub end: u32,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvedRef {
    pub reference: SymbolRef,

    pub target: Option<usize>,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ResolutionSet {
    pub definitions: Vec<SymbolDef>,

    pub references: Vec<ResolvedRef>,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Pool<T>(pub Vec<T>);
impl<T> Pool<T> {
    pub fn new() -> Self {
        Self(Vec::new())
    }
}
impl<T> From<Vec<T>> for Pool<T> {
    fn from(value: Vec<T>) -> Self {
        Self(value)
    }
}
impl<T> std::ops::Deref for Pool<T> {
    type Target = Vec<T>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl<T> std::ops::DerefMut for Pool<T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl<T> IntoIterator for Pool<T> {
    type Item = T;
    type IntoIter = std::vec::IntoIter<T>;
    fn into_iter(self) -> Self::IntoIter {
        self.0.into_iter()
    }
}
impl<'a, T> IntoIterator for &'a Pool<T> {
    type Item = &'a T;
    type IntoIter = std::slice::Iter<'a, T>;
    fn into_iter(self) -> Self::IntoIter {
        self.0.iter()
    }
}
impl<'a, T> IntoIterator for &'a mut Pool<T> {
    type Item = &'a mut T;
    type IntoIter = std::slice::IterMut<'a, T>;
    fn into_iter(self) -> Self::IntoIter {
        self.0.iter_mut()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArenaStorage<Id, T>
where
    Id: Ord + Copy + std::fmt::Debug,
{
    by_id: std::collections::BTreeMap<Id, T>,
}
impl<Id, T> Default for ArenaStorage<Id, T>
where
    Id: Ord + Copy + std::fmt::Debug,
{
    fn default() -> Self {
        Self {
            by_id: std::collections::BTreeMap::new(),
        }
    }
}
impl<Id, T> ArenaStorage<Id, T>
where
    Id: Ord + Copy + std::fmt::Debug,
{
    pub fn new() -> Self {
        Self {
            by_id: std::collections::BTreeMap::new(),
        }
    }
    pub fn insert(&mut self, id: Id, value: T) -> Result<(), String> {
        if self.by_id.insert(id, value).is_some() {
            return Err(format!("duplicate arena id {id:?}"));
        }
        Ok(())
    }
    pub fn get(&self, id: Id) -> Option<&T> {
        self.by_id.get(&id)
    }
    pub fn get_mut(&mut self, id: Id) -> Option<&mut T> {
        self.by_id.get_mut(&id)
    }
    pub fn values(&self) -> impl Iterator<Item = &T> {
        self.by_id.values()
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Arena<T>(pub Vec<T>);
impl<T> Arena<T> {
    pub fn new() -> Self {
        Self(Vec::new())
    }
}
impl<T> From<Vec<T>> for Arena<T> {
    fn from(value: Vec<T>) -> Self {
        Self(value)
    }
}
impl<T> std::ops::Deref for Arena<T> {
    type Target = Vec<T>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl<T> std::ops::DerefMut for Arena<T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl<T> IntoIterator for Arena<T> {
    type Item = T;
    type IntoIter = std::vec::IntoIter<T>;
    fn into_iter(self) -> Self::IntoIter {
        self.0.into_iter()
    }
}
impl<'a, T> IntoIterator for &'a Arena<T> {
    type Item = &'a T;
    type IntoIter = std::slice::Iter<'a, T>;
    fn into_iter(self) -> Self::IntoIter {
        self.0.iter()
    }
}
impl<'a, T> IntoIterator for &'a mut Arena<T> {
    type Item = &'a mut T;
    type IntoIter = std::slice::IterMut<'a, T>;
    fn into_iter(self) -> Self::IntoIter {
        self.0.iter_mut()
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Order<T>(pub Vec<T>);
impl<T> Order<T> {
    pub fn new() -> Self {
        Self(Vec::new())
    }
}
impl<T> From<Vec<T>> for Order<T> {
    fn from(value: Vec<T>) -> Self {
        Self(value)
    }
}
impl<T> std::ops::Deref for Order<T> {
    type Target = Vec<T>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl<T> std::ops::DerefMut for Order<T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl<T> IntoIterator for Order<T> {
    type Item = T;
    type IntoIter = std::vec::IntoIter<T>;
    fn into_iter(self) -> Self::IntoIter {
        self.0.into_iter()
    }
}
impl<'a, T> IntoIterator for &'a Order<T> {
    type Item = &'a T;
    type IntoIter = std::slice::Iter<'a, T>;
    fn into_iter(self) -> Self::IntoIter {
        self.0.iter()
    }
}
impl<'a, T> IntoIterator for &'a mut Order<T> {
    type Item = &'a mut T;
    type IntoIter = std::slice::IterMut<'a, T>;
    fn into_iter(self) -> Self::IntoIter {
        self.0.iter_mut()
    }
}
fn validate_hir(source: &str) -> Result<(), String> {
    hir::validate_root_text(source)
}
fn format_hir(source: &str) -> Result<String, String> {
    let root = hir::parse_root_text(source)?;
    Ok(hir::format_root_text(&root))
}
fn semantic_tokens_hir(source: &str) -> Vec<SemanticToken> {
    hir::semantic_tokens(source)
}
fn hover_entries_hir(source: &str) -> Vec<HoverEntry> {
    hir::hover_entries(source)
}
fn resolve_hir(source: &str) -> Result<ResolutionSet, String> {
    hir::resolve(source)
}
fn validate_asm(source: &str) -> Result<(), String> {
    asm::validate_root_text(source)
}
fn format_asm(source: &str) -> Result<String, String> {
    let root = asm::parse_root_text(source)?;
    Ok(asm::format_root_text(&root))
}
fn semantic_tokens_asm(source: &str) -> Vec<SemanticToken> {
    asm::semantic_tokens(source)
}
fn hover_entries_asm(source: &str) -> Vec<HoverEntry> {
    asm::hover_entries(source)
}
fn resolve_asm(source: &str) -> Result<ResolutionSet, String> {
    asm::resolve(source)
}
fn validate_mir(source: &str) -> Result<(), String> {
    let mut graph = mir::Graph::new();
    let handle = mir::parse_root_into_graph(&mut graph, source)?;
    mir::validate_root_in_graph(&graph, handle)
}
fn format_mir(source: &str) -> Result<String, String> {
    let mut graph = mir::Graph::new();
    let handle = mir::parse_root_into_graph(&mut graph, source)?;
    mir::format_root_in_graph(&graph, handle)
}
fn semantic_tokens_mir(source: &str) -> Vec<SemanticToken> {
    let mut graph = mir::Graph::new();
    let Ok(handle) = mir::parse_root_into_graph(&mut graph, source) else {
        return Vec::new();
    };
    mir::semantic_tokens_in_graph(source, &graph, handle)
}
fn hover_entries_mir(source: &str) -> Vec<HoverEntry> {
    let mut graph = mir::Graph::new();
    let Ok(handle) = mir::parse_root_into_graph(&mut graph, source) else {
        return Vec::new();
    };
    mir::hover_entries_in_graph(&graph, handle)
}
fn resolve_mir(source: &str) -> Result<ResolutionSet, String> {
    mir::resolve(source)
}

pub static REPRS: &[ReprSpec] = &[
    ReprSpec {
        name: hir::REPR_NAME,
        file_ext: hir::REPR_FILE_EXT,
        validate: validate_hir,
        format: format_hir,
        semantic_tokens: semantic_tokens_hir,
        hover_entries: hover_entries_hir,
        resolve: resolve_hir,
    },
    ReprSpec {
        name: asm::REPR_NAME,
        file_ext: asm::REPR_FILE_EXT,
        validate: validate_asm,
        format: format_asm,
        semantic_tokens: semantic_tokens_asm,
        hover_entries: hover_entries_asm,
        resolve: resolve_asm,
    },
    ReprSpec {
        name: mir::REPR_NAME,
        file_ext: mir::REPR_FILE_EXT,
        validate: validate_mir,
        format: format_mir,
        semantic_tokens: semantic_tokens_mir,
        hover_entries: hover_entries_mir,
        resolve: resolve_mir,
    },
];
