// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

#![allow(dead_code, unused_variables)]
use super::*;
pub fn format_root_text(node: &Module) -> String {
    format_module(node)
}
pub fn format_module_text(node: &Module) -> String {
    format_root_text(node)
}

impl std::fmt::Display for Module {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&format_root_text(self))
    }
}
const INDENT_WIDTH: usize = 4;
struct Writer {
    out: String,

    indent: usize,

    at_line_start: bool,
}

impl Writer {
    fn new() -> Self {
        Self {
            out: String::new(),
            indent: 0,
            at_line_start: false,
        }
    }
    fn text(&mut self, text: &str) {
        for ch in text.chars() {
            if self.at_line_start && ch != '\n' {
                for _ in 0..self.indent {
                    self.out.push(' ');
                }
                self.at_line_start = false;
            }
            self.out.push(ch);
            if ch == '\n' {
                self.at_line_start = true;
            }
        }
    }
    fn with_indent(&mut self, f: impl FnOnce(&mut Self)) {
        self.indent += INDENT_WIDTH;
        f(self);
        self.indent -= INDENT_WIDTH;
    }
    fn finish(self) -> String {
        self.out
    }
}
pub fn format_block(node: &Block) -> String {
    let mut w = Writer::new();
    write_block(&mut w, node);
    w.finish()
}
fn write_block(w: &mut Writer, node: &Block) {
    w.text("{");
    w.text("\n");
    for (idx, value) in node.statements.iter().enumerate() {
        if idx != 0 {
            w.text("\n");
        }
        w.with_indent(|w| {
            write_stmt(w, value);
        });
    }
    w.text("\n}");
}
pub fn format_expr(node: &Expr) -> String {
    let mut w = Writer::new();
    write_expr(&mut w, node);
    w.finish()
}
fn write_expr(w: &mut Writer, node: &Expr) {
    match node {
        other @ Expr::Binary { .. } => {
            w.text(&format!("{:?}", other));
        }
        Expr::Call { args, callee, .. } => {
            w.text("call ");
            w.text(&callee.text);
            w.text("(");
            for (idx, value) in args.iter().enumerate() {
                if idx != 0 {
                    w.text(", ");
                }
                write_expr(w, value);
            }
            w.text(")");
        }
        other @ Expr::Field { .. } => {
            w.text(&format!("{:?}", other));
        }
        Expr::Literal { value, .. } => {
            w.text(&value.value.to_string());
        }
        Expr::Local { name, .. } => {
            w.text(&name.text);
        }
    }
}
pub fn format_function(node: &Function) -> String {
    let mut w = Writer::new();
    write_function(&mut w, node);
    w.finish()
}
fn write_function(w: &mut Writer, node: &Function) {
    w.text("fn ");
    w.text(&node.name.text);
    w.text("(");
    for (idx, value) in node.params.iter().enumerate() {
        if idx != 0 {
            w.text(", ");
        }
        write_param(w, value);
    }
    w.text(") -> ");
    w.text(&node.return_type.text);
    w.text(" ");
    write_block(w, &node.body);
}
pub fn format_local(node: &Local) -> String {
    format!("{:?}", node)
}
fn write_local(w: &mut Writer, node: &Local) {
    w.text(&format!("{:?}", node));
}
pub fn format_module(node: &Module) -> String {
    let mut w = Writer::new();
    write_module(&mut w, node);
    w.finish()
}
fn write_module(w: &mut Writer, node: &Module) {
    w.text("module ");
    w.text("{");
    w.text("\n");
    for (idx, value) in node.functions.iter().enumerate() {
        if idx != 0 {
            w.text("\n");
        }
        w.with_indent(|w| {
            write_function(w, value);
        });
    }
    w.text("\n}");
}
pub fn format_param(node: &Param) -> String {
    let mut w = Writer::new();
    write_param(&mut w, node);
    w.finish()
}
fn write_param(w: &mut Writer, node: &Param) {
    w.text(&node.name.text);
    w.text(": ");
    w.text(&node.ty.text);
}
pub fn format_place(node: &Place) -> String {
    let mut w = Writer::new();
    write_place(&mut w, node);
    w.finish()
}
fn write_place(w: &mut Writer, node: &Place) {
    match node {
        other @ Place::Field { .. } => {
            w.text(&format!("{:?}", other));
        }
        other @ Place::Local { .. } => {
            w.text(&format!("{:?}", other));
        }
    }
}
pub fn format_stmt(node: &Stmt) -> String {
    let mut w = Writer::new();
    write_stmt(&mut w, node);
    w.finish()
}
fn write_stmt(w: &mut Writer, node: &Stmt) {
    match node {
        other @ Stmt::Assign { .. } => {
            w.text(&format!("{:?}", other));
        }
        Stmt::Expr { value, .. } => {
            write_expr(w, value);
        }
        other @ Stmt::If { .. } => {
            w.text(&format!("{:?}", other));
        }
        other @ Stmt::Init { .. } => {
            w.text(&format!("{:?}", other));
        }
        Stmt::Return { value, .. } => {
            w.text("return");
            if let Some(value) = value.as_ref() {
                w.text(" ");
                write_expr(w, value);
            }
        }
    }
}
pub fn format_type_def(node: &TypeDef) -> String {
    format!("{:?}", node)
}
fn write_type_def(w: &mut Writer, node: &TypeDef) {
    w.text(&format!("{:?}", node));
}
pub fn format_binary_op(node: &BinaryOp) -> String {
    let mut w = Writer::new();
    write_binary_op(&mut w, node);
    w.finish()
}
fn write_binary_op(w: &mut Writer, node: &BinaryOp) {
    match node {
        BinaryOp::Add => {
            w.text("Add");
        }
        BinaryOp::Sub => {
            w.text("Sub");
        }
    }
}
pub fn format_local_kind(node: &LocalKind) -> String {
    let mut w = Writer::new();
    write_local_kind(&mut w, node);
    w.finish()
}
fn write_local_kind(w: &mut Writer, node: &LocalKind) {
    match node {
        LocalKind::Local => {
            w.text("Local");
        }
        LocalKind::Temp => {
            w.text("Temp");
        }
    }
}
pub fn format_type_def_kind(node: &TypeDefKind) -> String {
    let mut w = Writer::new();
    write_type_def_kind(&mut w, node);
    w.finish()
}
fn write_type_def_kind(w: &mut Writer, node: &TypeDefKind) {
    match node {
        TypeDefKind::Alias => {
            w.text("Alias");
        }
        TypeDefKind::Enum => {
            w.text("Enum");
        }
        TypeDefKind::Struct => {
            w.text("Struct");
        }
    }
}
