// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

use super::*;
use chumsky::prelude::*;
type ParseExtra<'src> = extra::Err<Rich<'src, char>>;
fn ws<'src>() -> impl Parser<'src, &'src str, (), ParseExtra<'src>> + Clone {
    any()
        .filter(|c: &char| c.is_whitespace())
        .repeated()
        .ignored()
}
fn line_ws<'src>() -> impl Parser<'src, &'src str, (), ParseExtra<'src>> + Clone {
    one_of(" \t").repeated().ignored()
}
fn doc_comment_line<'src>() -> impl Parser<'src, &'src str, String, ParseExtra<'src>> + Clone {
    line_ws()
        .ignore_then(just("///"))
        .ignore_then(just(' ').or_not())
        .ignore_then(
            any()
                .filter(|c: &char| *c != '\n')
                .repeated()
                .collect::<String>(),
        )
        .then_ignore(just('\n').or_not())
}
fn doc_block<'src>() -> impl Parser<'src, &'src str, Option<DocBlock>, ParseExtra<'src>> + Clone {
    doc_comment_line()
        .repeated()
        .collect::<Vec<_>>()
        .map(|lines| {
            if lines.is_empty() {
                None
            } else {
                Some(DocBlock(lines))
            }
        })
}
fn token_ident<'src>() -> impl Parser<'src, &'src str, String, ParseExtra<'src>> + Clone {
    text::ident::<_, ParseExtra<'src>>().map(str::to_owned)
}
fn token_int<'src>() -> impl Parser<'src, &'src str, String, ParseExtra<'src>> + Clone {
    text::int::<_, ParseExtra<'src>>(10).map(str::to_owned)
}
fn token_symbol<'src>() -> impl Parser<'src, &'src str, String, ParseExtra<'src>> + Clone {
    just('@')
        .then(text::ident::<_, ParseExtra<'src>>().map(str::to_owned))
        .then(
            just('.')
                .ignore_then(text::ident::<_, ParseExtra<'src>>().map(str::to_owned))
                .repeated()
                .collect::<Vec<_>>(),
        )
        .map(|((_, head), tail)| {
            let mut out = format!("@{head}");
            for part in tail {
                out.push('.');
                out.push_str(&part);
            }
            out
        })
}
fn prov_from_span(span: chumsky::span::SimpleSpan<usize>, file_id: Option<u32>) -> Prov {
    Prov {
        file_id,
        span: Some(Span {
            start: span.start as u32,
            end: span.end as u32,
        }),
    }
}
fn parse_root_value_rich(
    source: &str,

    file_id: Option<u32>,
) -> Result<Module, Vec<Rich<'_, char>>> {
    let expr_parser = recursive(move |expr_parser| {
        choice((
            (((((just("call").padded()).ignore_then(
                token_symbol()
                    .map_with(move |text, e| Symbol {
                        prov: prov_from_span(e.span(), file_id),
                        text,
                    })
                    .then_ignore(ws()),
            ))
            .then_ignore(just("(").padded()))
            .then(
                (expr_parser.clone())
                    .separated_by(just(",").padded())
                    .allow_trailing()
                    .collect::<Vec<_>>(),
            ))
            .then_ignore(just(")").padded()))
            .map_with(move |(callee, args), e| Expr::Call {
                args,
                callee,
                prov: prov_from_span(e.span(), file_id),
            }),
            (token_ident()
                .map_with(move |text, e| Symbol {
                    prov: prov_from_span(e.span(), file_id),
                    text,
                })
                .then_ignore(ws()))
            .map_with(move |name, e| Expr::Local {
                name,
                prov: prov_from_span(e.span(), file_id),
            }),
            (token_int()
                .try_map(move |text, span| match text.parse::<u64>() {
                    Ok(value) => Ok(Literal {
                        prov: prov_from_span(span, file_id),
                        value,
                    }),
                    Err(err) => Err(Rich::custom(
                        span,
                        format!("invalid integer literal {text:?}: {err}"),
                    )),
                })
                .then_ignore(ws()))
            .map_with(move |value, e| Expr::Literal {
                prov: prov_from_span(e.span(), file_id),
                value,
            }),
        ))
        .boxed()
    });
    let stmt_parser = choice((
        ((just("return").padded()).ignore_then(((expr_parser.clone()).map(Box::new)).or_not()))
            .map_with(move |value, e| Stmt::Return {
                prov: prov_from_span(e.span(), file_id),
                value,
            }),
        ((expr_parser.clone()).map(Box::new)).map_with(move |value, e| Stmt::Expr {
            prov: prov_from_span(e.span(), file_id),
            value,
        }),
    ))
    .boxed();
    let block_parser = (((just("{").padded())
        .ignore_then((stmt_parser.clone()).repeated().collect::<Vec<_>>()))
    .then_ignore(just("}").padded()))
    .map_with(move |statements, e| Block {
        prov: prov_from_span(e.span(), file_id),
        statements,
    })
    .boxed();
    let param_parser = (((token_ident()
        .map_with(move |text, e| Symbol {
            prov: prov_from_span(e.span(), file_id),
            text,
        })
        .then_ignore(ws()))
    .then_ignore(just(":").padded()))
    .then(
        token_ident()
            .map_with(move |text, e| Type {
                prov: prov_from_span(e.span(), file_id),
                text,
            })
            .then_ignore(ws()),
    ))
    .map_with(move |(name, ty), e| Param {
        name,
        prov: prov_from_span(e.span(), file_id),
        ty,
    })
    .boxed();
    let function_parser = (((((((((doc_block()).then_ignore(just("fn").padded())).then(
        token_ident()
            .map_with(move |text, e| Symbol {
                prov: prov_from_span(e.span(), file_id),
                text,
            })
            .then_ignore(ws()),
    ))
    .then_ignore(just("(").padded()))
    .then(
        (param_parser.clone())
            .separated_by(just(",").padded())
            .allow_trailing()
            .collect::<Vec<_>>(),
    ))
    .then_ignore(just(")").padded()))
    .then_ignore(just("->").padded()))
    .then(
        token_ident()
            .map_with(move |text, e| Type {
                prov: prov_from_span(e.span(), file_id),
                text,
            })
            .then_ignore(ws()),
    ))
    .then((block_parser.clone()).map(Box::new)))
    .map_with(
        move |((((docs, name), params), return_type), body), e| Function {
            body,
            docs,
            locals: Vec::new(),
            name,
            params,
            prov: prov_from_span(e.span(), file_id),
            return_type,
        },
    )
    .boxed();
    let module_parser = (((((doc_block()).then_ignore(just("module").padded()))
        .then_ignore(just("{").padded()))
    .then((function_parser.clone()).repeated().collect::<Vec<_>>()))
    .then_ignore(just("}").padded()))
    .map_with(move |(docs, functions), e| Module {
        docs,
        functions,
        prov: prov_from_span(e.span(), file_id),
        type_defs: Vec::new(),
    })
    .boxed();
    module_parser.then_ignore(end()).parse(source).into_result()
}
pub fn parse_root_text_rich(
    source: &str,

    file_id: Option<u32>,
) -> Result<Module, Vec<Rich<'_, char>>> {
    parse_root_value_rich(source, file_id)
}
pub fn parse_root_text_with_file_id(source: &str, file_id: Option<u32>) -> Result<Module, String> {
    parse_root_value_rich(source, file_id).map_err(|errs| crate::format_rich_errors(source, errs))
}
pub fn parse_root_text(source: &str) -> Result<Module, String> {
    parse_root_text_with_file_id(source, None)
}
pub fn parse_module_text_rich(
    source: &str,

    file_id: Option<u32>,
) -> Result<Module, Vec<Rich<'_, char>>> {
    parse_root_text_rich(source, file_id)
}
pub fn parse_module_text_with_file_id(
    source: &str,

    file_id: Option<u32>,
) -> Result<Module, String> {
    parse_root_text_with_file_id(source, file_id)
}
pub fn parse_module_text(source: &str) -> Result<Module, String> {
    parse_root_text(source)
}
pub fn parse_root_into_graph_rich<'src>(
    graph: &mut Graph,

    source: &'src str,

    file_id: Option<u32>,
) -> Result<ModuleHandle, Vec<Rich<'src, char>>> {
    let root = parse_root_value_rich(source, file_id)?;
    Ok(graph.insert_root(root))
}
pub fn parse_root_into_graph_with_file_id(
    graph: &mut Graph,

    source: &str,

    file_id: Option<u32>,
) -> Result<ModuleHandle, String> {
    parse_root_into_graph_rich(graph, source, file_id)
        .map_err(|errs| crate::format_rich_errors(source, errs))
}
pub fn parse_root_into_graph(graph: &mut Graph, source: &str) -> Result<ModuleHandle, String> {
    parse_root_into_graph_with_file_id(graph, source, None)
}
pub fn parse_module_into_graph_rich<'src>(
    graph: &mut Graph,

    source: &'src str,

    file_id: Option<u32>,
) -> Result<ModuleHandle, Vec<Rich<'src, char>>> {
    parse_root_into_graph_rich(graph, source, file_id)
}
pub fn parse_module_into_graph_with_file_id(
    graph: &mut Graph,

    source: &str,

    file_id: Option<u32>,
) -> Result<ModuleHandle, String> {
    parse_root_into_graph_with_file_id(graph, source, file_id)
}
pub fn parse_module_into_graph(graph: &mut Graph, source: &str) -> Result<ModuleHandle, String> {
    parse_root_into_graph(graph, source)
}
