// @generated by kajit-foundation::generate_repr_poc. Do not edit manually.

use super::*;
#[test]
fn parse_module_smoke() {
    let module = parse_root_text("module { fn main() -> Value { return } }").unwrap();
    assert_eq!(module.functions.len(), 1);
    assert_eq!(module.functions[0].name.text, "main");
    assert_eq!(module.functions[0].return_type.text, "Value");
    assert!(matches!(
        module.functions[0].body.statements.as_slice(),
        [Stmt::Return { value: None, .. }]
    ));
}
#[test]
fn parse_module_into_graph_smoke() {
    let mut graph = Graph::new();
    let handle =
        parse_root_into_graph(&mut graph, "module { fn main() -> Value { return } }").unwrap();
    let module = graph.root(handle).unwrap();
    assert_eq!(module.functions.len(), 1);
    assert_eq!(module.functions[0].name.text, "main");
}
#[test]
fn format_module_smoke() {
    let text = "module { fn main() -> Value { return } }";
    let module = parse_root_text(text).unwrap();
    let formatted = format_root_text(&module);
    assert_eq!(
        formatted,
        "module {\n    fn main() -> Value {\n        return\n    }\n}"
    );
    let reparsed = parse_root_text(&formatted).unwrap();
    assert_eq!(reparsed, module);
}
