[package]
name = "kajit-mir"
version = "0.1.0"
edition = "2024"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
kajit-ir = { path = "../kajit-ir" }
kajit-lir = { path = "../kajit-lir" }
kajit-reprs = { path = "../kajit-reprs" }
kajit-types = { path = "../kajit-types" }
indexmap = "2"
tracing = "0.1"

[dev-dependencies]
facet = "0.44"
kajit-ir-text = { path = "../kajit-ir-text" }
